### ISSUE TITLE
Sugestão de função nova: zzmonitor

### ISSUE THREAD

**Issue by frankjuniorr** [funcoeszz/funcoeszz#104]
Olá pessoal, 

Tive uma ideia hj, de uma nova zz, que seria um monitor do sistema. Eu não sei se se encaixa na filosofia das funcoeszz, mas enfim, resolvi dá essa sugestão.
Eu fiz um esboço do código bem rapidão no trabalho, com um exemplo, de como seria +/- isso, que pode ser acessado aqui: 
https://github.com/frankjuniorr/MeusScripts/blob/master/monitor.sh

De cara esse código já tem um monte de melhoria. Eu rodei no Ubuntu no trabalho e funcionou, mas nem fiz a validação pra Mac (aqui em casa não rodou, hahha), enfim, mas idéia seria +/- essa. O que vcs acham?

**Comment by itamarnet** [comment]
São quase 3 anos sem atividade, acho que não há mais o interesse na produção dessa nova zz.
Portanto acredito que podemos fechar esse issue.

**Comment by aureliojargas** [comment]
Concordo. Qualquer coisa é só reabrir.
