### ISSUE TITLE
Sugestão: zzconversor

### ISSUE THREAD

**Issue by igorsantos07** [funcoeszz/funcoeszz#115]
Seria legal ter um acesso rápido ao conversor de medidas mágico do Google: por exemplo, quando digitamos ["1400ft in km" e ele retorna "0.42672km"](https://www.google.ca/search?client=opera&q=1400ft+in+km&sourceid=opera&ie=utf-8&oe=utf-8&channel=suggest)

**Comment by itamarnet** [comment]
Aqui também completa mais de 3 anos de inatividade, e não houve uma proposta e nem esboço da zzconversor sugerida.
Reforço a ideia do uso da ``` zzconverte ``` que já existe, em conjunto com a ``` zzcalcula ``` para atender a ideia original.
Esse é mais um issue que acredito podermos fechar.
