### ISSUE TITLE
Amenizar a quebradeira que o testador novo mostrou

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#121]
Agora que a migração para o testador novo foi finalizada (veja #118 ), temos uma nova tarefa grande pela frente.

Ao rodar o testador, agora várias funções que antes estavam OK aparecem quebradas. Os motivos basicamente são dois:

1) **Brancos**

No processo de migração, eu removi os espaços em branco inúteis dos resultados esperados. Seja espaços em branco no início ou fim das linhas, seja linhas em branco. Estes são erros menores, para arrumar quando der.

2) **Erros de portabilidade**

O testador usa a shebang `#!/bin/sh`, em vez de `#!/bin/bash`. Isso significa que, mesmo em sistemas onde o Bash é o shell padrão, ao executar este arquivo o Bash entra em modo de compatibilidade POSIX. Então, algumas coisas que funcionam no Bash normal, deixam de funcionar neste modo, pois são Bashismos e não são portáveis.

O exemplo mais notável é o `echo -n` que para de funcionar, e ainda é usado em várias funções. Mas há várias outras particularidades. Recomendo a leitura do https://github.com/aureliojargas/funcoeszz/wiki/Portabilidade

**O que fazer**

Só a troca do `echo -n` por `printf` já resolverá boa parte dos problemas. No wiki Portabilidade linkado anteriormente há instruções de como fazer, o link direto é https://github.com/aureliojargas/funcoeszz/wiki/Portabilidade#comando-echo

Os erros de espaço em branco devem ser simples de resolver também. Se no algoritmo ficar complicado remover os espaços, coloque um `sed` no final pra limpar e pronto. **Update:** Use a `zztrim`.

Ao fazer correções, favor **referenciar este issue** para podermos acompanhar o andamento.

O lado bom é que tornaremos as funções mais robustas e portáveis neste processo, o que é algo sempre desejado. Também é um primeiro passo para tornar as funções compatíveis com outros shells além do Bash (que hoje não é prioridade, mas a longo prazo é).

**Resumo dos problemas**

Aqui está o relatório final do testador, resumido e mostrando somente as funções com problemas. Minha máquina: Mac OS X Mountain Lion (BSD).

````
$ cd testador
$ ./run
...
     ok  fail  skip
     11     1     -    zzbeep.sh
     44     3     -    zzconverte.sh
      1     1     -    zzdicasl.sh
      1     1     -    zzdicjargon.sh
      1     1     -    zzdicportugues.sh
      1     1     -    zzenglish.sh
      7     3     -    zzextensao.sh
      2     1     -    zzfeed.sh
      2     1     -    zzhoracerta.sh
      1     1     -    zzhowto.sh
      -     3     -    zzjquery.sh
     28     1     -    zzjuntalinhas.sh
      -     1     -    zzlinux.sh
      1     6     -    zzloteria.sh
     52     7     -    zzmat.sh
      2     1     -    zzminiurl.sh
      1     3     -    zzmoeda.sh
      -     1     -    zznatal.sh
      2     1     -    zznome.sh
      1     1     -    zzora.sh
      2     4     -    zzpalpite.sh
      -     1     -    zzpiada.sh
      -     2     -    zzrpmfind.sh
     14    10     -    zzsenha.sh
      1     1     -    zzsigla.sh
      2     3     -    zztabuada.sh
      1     1     -    zztempo.sh
    221     2     -    zztool.sh
      2     1     -    zzwikipedia.sh

FAIL: 64 of 3144 tests failed
$
````

**Comment by itamarnet** [comment]
EU acho que esse issue pode ser fechado. Apesar de no momento que escrevo haver 9 funções sem testes, os testes existentes estão em pleno funcionamento e cobrindo bem as possibilidades de cada função.
O que fazemos agora é manutenção e correções provenientes de mudanças, principalmente em funções que dependem de consulta on-line, ou comportamento inesperados em novos SOs.
