### ISSUE TITLE
O core deve ser portável

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#122]
> Nota: Este issue deve ser reaberto caso alguma alteração futura volte a comprometer a portabilidade do core.

O core das Funções ZZ (arquivo funcoeszz) precisa ser portável. Fazer uma auditoria completa e resolver qualquer problema de portabilidade que exista. Mencionar este issue nos commits, para acompanhamento.

**Motivo:** O testador novo (clitest) usa `/bin/sh` e pode não funcionar em alguns ambientes caso usemos comandos não portáveis no core. Isso acontece porque o script `testador/run` usa a opção `--pre-flight` para incluir todo o ambiente das ZZ (e as funções em si) na shell de execução do testador. Caso algum comando não portável seja encontrado no core, a execução dos testes será interrompida já neste passo inicial, dependendo de qual shell esteja atrelada a `/bin/sh` na máquina do usuário.

Obs.: A portabilidade das funções individuais ainda não é prioridade, mas no core a portabilidade passa a ser obrigatória.

**Comment by itamarnet** [comment]
Acredito que o core esteja realmente multi-plataforma
Apenas tenho dúvidas no uso do ``` type ```, mas aparentemente isso não é um problema.
Podemos considerar plenamente portável?

**Comment by aureliojargas** [comment]
Espera só mais um pouco, eu colocar o Travis pra funcionar, aí teremos testes automatizados em Linux e Mac. Vou passar o shellcheck no core também, pra garantir.

**Comment by aureliojargas** [comment]
Travis OK. Rodei o shellcheck, mas ele reclamou de várias coisas que são usos avançados nossos, e é melhor não mexer.

Então acho que podemos considerar essa issue cumprida também.

**Comment by itamarnet** [comment]
:+1:
