### ISSUE TITLE
Mensagem de erro opcional na zztool

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#127]
Dentro do core das Funções ZZ, na função zztool para as opções "arquivo_vago" e "arquivo_legivel", colocar a mensagem de erro como opcional, assim como nos demais testes, trocando respectivamente:
```
echo "Arquivo $1 já existe. Abortando."
echo "Não consegui ler o arquivo $1"
```
por:
```
test -n "$erro" && echo "Arquivo $1 já existe. Abortando."
test -n "$erro" && echo "Não consegui ler o arquivo $1"
```

**Comment by aureliojargas** [comment]
Concordo @itamarnet, já temos um mecanismo padrão e estas funções estão fora dele.

Porém, ao fazer esta mudança, no mesmo commit todas as funções que hoje usam estas duas `zztool` devem ser também atualizadas para usar a opção `-e`, mantendo o comportamento atual de mostrar a mensagem padrão em todas elas.

Se alguma dessas função precisar omitir a mensagem de erro padrão, que isso seja feito em um outro commit.

**Comment by itamarnet** [comment]
Feito!
Vide commit b0d447ce413f0ab8669ba878bfd02c3898e239be

**Comment by aureliojargas** [comment]
:+1:

**Comment by aureliojargas** [comment]
Só faltou atualizar os testes, fiz no 79c237356ba1769c4cdf16939533f0a77e537f51
