### ISSUE TITLE
zzcriptomoeda: Cotações divergentes em fontes variadas.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#142]
O site original de consulta do bitcoin (www.bitinvest.com.br) na função, deixou de informar cotações da moeda litecoin.
Ao procurar alternativas para suprir esse recurso, constatei em vários sites cotações diferentes da moeda bitcoin para o Real, a saber: www.basebit.com.br, www.mercadobitcoin.com.br, http://bitcoinhoje.com, http://www.brascoins.com.

Portanto me limitei apenas a corrigir a não exibição do bitcoin com referência ao site já em uso no commit 077296e160ac73b68fab3cddcf516b03fd6cdf48, mas vejo que é necessário uma avaliação dessas diferenças, que chegam a ser significativas.

Para não ser injusto, há diferenças, por exemplo, na cotação do dolar, mas tem diferenças pequenas, que podem ser comprovadas em:
```
$ zzbolsas moedas
$ zzcotacao
$ zzdolar
$ zzmoeda
```
Caso seja relevante, acredito que também possamos colocar em pauta essas diferenças na cotação do dolar.

**Comment by itamarnet** [comment]
Os múltiplos sites que apresentavam divergências estão ou sem atualização, fecharam ou estão na iminência de interromper as atividades.
Os sites usados como referência continuam ativos.
Esse issue então não mais procede, pois os dados comparativos não correspondem a uma realidade estável do mercado virtual.

**Comment by aureliojargas** [comment]
:+1:
