### ISSUE TITLE
zzglobo não funciona, url fora!

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#148]
A url da zzglobo não fornece mais nenhum retorno, e acredito que esteja assim desde a reformulação do portal do Terra.
Não encontrei uma nova url para substitui-la, mas considerando o contexto planejo desativá-la, visto que a zztv pode substituir a função como um todo.
Se acaso alguém encontrar um link que possa ser usado para esse fim, a zzglobo permanece, caso contrário o desfecho será sua descontinuidade.

**Comment by aureliojargas** [comment]
Desativada nos commits e31240c e 44e4888
