### ISSUE TITLE
Função para mensurar a velocidade da Internet via speedtest.net

### ISSUE THREAD

**Issue by IgorIsaiasBanlian** [funcoeszz/funcoeszz#149]
Existe um programa/script em Python que faz exatamente isso:

=> https://raw.github.com/sivel/speedtest-cli/master/speedtest_cli.py

Ele roda via linha de comando, você pode passar ou não parâmetros opcionais para ele (como selecionar o local do servidor de destino, por exemplo), ele exibe os resultados de ping, taxa de download e taxa de upload de uma forma amigável, e me parece que não tem nada nele que não possa ser feito em Shell Script!

Portanto este ticket é para propor o port de tal programa/script em Python para Shell Script e a inclusão do mesmo nas funcoeszz!

Atenciosamente,
Igor Isaias Banlian

**Comment by itamarnet** [comment]
A ideia está parada a mais de 3 anos, e não há perspectiva que um "dono" apareça.
Caso surja um voluntário, reabrirei esse issue com muito prazer.
