### ISSUE TITLE
Formatação de cpf/cnpj utilizando as funçoes zzcpf e zzcnpj

### ISSUE THREAD

**Issue by rennanzera** [funcoeszz/funcoeszz#153]
Sugiro que, além de validar um cpf e cnpj, as funções zzcpf e zzcnpj possam formatar, quando válido, um cpf 00000000000 para 00.000.000-00, da mesma forma para o cnpj. Basta colocar uma opção -f para o comando, que irá passar a saída pelo sed, com as regex a seguir.

cpf: sed 's:\(...\)\(...\)\(...\)\(.*\):\1.\2.\3-\4:'
cnpj antigo: sed 's:\(...\)\(...\)\(...\)\(....\)\(.*\):\1.\2.\3/\4-\5:'
cnpj novo: sed 's:\(..\)\(...\)\(...\)\(....\)\(.*\):\1.\2.\3/\4-\5:'

[]'s

**Comment by aureliojargas** [comment]
Ué, o GitHub ficou louco. Só agora que vi essa festa de assigned/unassigned mês passado. Eu não fiz nada :)

**Comment by aureliojargas** [comment]
Feito, vide commits relacionados para mais detalhes.
