### ISSUE TITLE
Função para listar quantidade de vezes de um número sorteado na mega-sena

### ISSUE THREAD

**Issue by ghost** [funcoeszz/funcoeszz#154]
Oi. Eu fiz um script aqui para listar quantas vezes um número foi sorteado na mega-sena. Minha pergunta é se acham que vale a pena criar uma função zz assim. Abaixo segue o código que ele tem hoje. Se acharem que vale a pena, que seria interessante, posso ler o coding style para ver como acrescentar ele ao Funções ZZ.

wget http://www1.caixa.gov.br/loterias/_arquivos/loterias/D_megase.zip && unzip D_megase.zip && cat D_MEGA.HTM | grep -E -a -A 6 '[0-9]{2}/[0-9]{2}/[0-9]{4}' | sed 's/<td>// ; s/<\/td>// ; s/--//' | grep -E '[0-9]{2}' | grep -vE '[0-9]{2}\/[0-9]{2}\/[0-9]{4}' | sed 's/.*>//' | sort | uniq -c | sort

**Comment by aureliojargas** [comment]
@ghtp25 Dica: Primeiro faça a função funcionar corretamente, só depois se preocupe com o coding style. Você já pode iniciar o Pull Request com uma versão inicial dela, que vamos te auxiliando e nos commits seguintes você vai ajeitando até ficar 100% e daí fazemos o merge.

**Comment by itamarnet** [comment]
Já que o tópico aparentemente foi "esquecido" ou "abandonado", inclui a funcionalidade na ``` zzloteria ```.
Vide commit 86378646ff53a5a392831245f1b85e5da5593d2f
