### ISSUE TITLE
zzsigla quebrou novamente

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#157]
Parece que o site http://www.acronymfinder.com foi remodelado.

Alguém arrisca tentar recuperá-la?

**Comment by pvital** [comment]
Corrigido! Pull request com o fix em instantes.

**Comment by pvital** [comment]
Fix em https://github.com/funcoeszz/funcoeszz/pull/162

**Comment by pvital** [comment]
V2 em https://github.com/funcoeszz/funcoeszz/pull/165 após feedback do @aureliojargas

**Comment by aureliojargas** [comment]
Corrigido no PR #165
