### ISSUE TITLE
zzsenha: opção -u/--uniq para não usar letras repetidas

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#158]
Historicamente, a zzsenha gerava senhas sem caracteres repetidos. Recentemente ela foi alterada para mostrar caracteres repetidos (vide PR #147).

Porém, seria interessante ter ambas as possibilidades.

Sugiro mesclar o código anterior com o atual e ter uma opção `-u` e `--uniq` para forçar o uso de letras não repetidas. O comportamento padrão continua sendo o atual de mostrar repetidos.

**Comment by pvital** [comment]
Feito. Pull request em https://github.com/funcoeszz/funcoeszz/pull/163

**Comment by aureliojargas** [comment]
PR aceito, valeu! :+1:
