### ISSUE TITLE
zzloteria quebrou

### ISSUE THREAD

**Issue by kemelzaidan** [funcoeszz/funcoeszz#159]
zzloteria parou de funcionar... :cry:

**Comment by itamarnet** [comment]
Consulte a zzloteria2 e veja se ela te atende.

Já tive uma conversa com @oreio a muito tempo sobre esse assunto, e mais recentemente (2013) com o Gustavo no grupo de discussão zztabtab ( https://br.groups.yahoo.com/neo/groups/zztabtab/conversations/messages/1031 ), e tem ligação com o lynx, que é usado no "$ZZWWWDUMP".

O zzloteria2 testa a existência do links, dando preferência a ele para usar como navegador textual.

Mas esse problema do lynx, também acontece com o w3m e curl.

**Comment by kemelzaidan** [comment]
Também não funciona. Pelo que eu percebi do link que vc enviou, é pela falta de suporte a javascript no lynxs e outros browsers cli. Não conheço muito, mas o [elinks](http://elinks.or.cz/) parece ter suporte a javascript. Não sei se é solução, porém...

Abaixo o erro:

```bash
 zzloteria2

Procurando www1.caixa.gov.br
Making HTTP connection to www1.caixa.gov.br
Enviando requisição HTTP.
Enviada requisição HTTP; aguardando resposta.
HTTP/1.1 302 Found
Transferência completada
HTTP/1.1 302 Found

lynx: Arquivo inicial não pode ser encontrado ou não é texto/HTML
      Saindo...

Procurando www1.caixa.gov.br
Making HTTP connection to www1.caixa.gov.br
Enviando requisição HTTP.
Enviada requisição HTTP; aguardando resposta.
HTTP/1.1 302 Found
Transferência completada
HTTP/1.1 302 Found

lynx: Arquivo inicial não pode ser encontrado ou não é texto/HTML
      Saindo...

Procurando www1.caixa.gov.br
Making HTTP connection to www1.caixa.gov.br
Enviando requisição HTTP.
Enviada requisição HTTP; aguardando resposta.
HTTP/1.1 302 Found
Transferência completada
HTTP/1.1 302 Found

lynx: Arquivo inicial não pode ser encontrado ou não é texto/HTML
      Saindo...

Procurando www1.caixa.gov.br
Making HTTP connection to www1.caixa.gov.br
Enviando requisição HTTP.
Enviada requisição HTTP; aguardando resposta.
HTTP/1.1 302 Found
Transferência completada
HTTP/1.1 302 Found

lynx: Arquivo inicial não pode ser encontrado ou não é texto/HTML
      Saindo...

Procurando www1.caixa.gov.br
Making HTTP connection to www1.caixa.gov.br
Enviando requisição HTTP.
Enviada requisição HTTP; aguardando resposta.
HTTP/1.1 302 Found
Transferência completada
HTTP/1.1 302 Found

lynx: Arquivo inicial não pode ser encontrado ou não é texto/HTML
      Saindo...

Procurando www1.caixa.gov.br
Making HTTP connection to www1.caixa.gov.br
Enviando requisição HTTP.
Enviada requisição HTTP; aguardando resposta.
HTTP/1.1 302 Found
Transferência completada
HTTP/1.1 302 Found

lynx: Arquivo inicial não pode ser encontrado ou não é texto/HTML
      Saindo...
federal:
   1º Prêmio
   2º Prêmio
   3º Prêmio
   4º Prêmio
   5º Prêmio
   Concurso  ()


Procurando www1.caixa.gov.br
Making HTTP connection to www1.caixa.gov.br
Enviando requisição HTTP.
Enviada requisição HTTP; aguardando resposta.
HTTP/1.1 302 Found
Transferência completada
HTTP/1.1 302 Found

lynx: Arquivo inicial não pode ser encontrado ou não é texto/HTML
      Saindo...
timemania:

   Time:
   Concurso  ()
   Acumulado em R$  para
     Faixa       Qtde.          Prêmio
     7 ptos
     6 ptos
     5 ptos
     4 ptos
     3 ptos


Procurando www1.caixa.gov.br
Making HTTP connection to www1.caixa.gov.br
Enviando requisição HTTP.
Enviada requisição HTTP; aguardando resposta.
HTTP/1.1 302 Found
Transferência completada
HTTP/1.1 302 Found

lynx: Arquivo inicial não pode ser encontrado ou não é texto/HTML
      Saindo...
awk: trying to access out of range field -4
 input record number 1, file
 source line number 1
awk: trying to access out of range field -1
 input record number 1, file
 source line number 1
awk: trying to access out of range field -5
 input record number 1, file
 source line number 1
awk: trying to access out of range field -2
 input record number 1, file
 source line number 1
```

**Comment by itamarnet** [comment]
Realmente não funcionaria mesmo, pois provavelmente não tem instalado o links ou elinks, se acaso tivesse usaria-o no lugar do lynx, mas na falta o comportamento é igual o zzloteria.
Tente instalar o links e veja se o problemas persiste, normalmente instalando o elinks ou o links2, costuma gerar um link simbólico usando links.
Mas não é o caso de javascript, mas de redirecionamento de quadros, que apenas o links no caso da caixa resolveu, ao menos detre as opções que conheço e que citei antes.

**Comment by aureliojargas** [comment]
É, mesmo erro aqui no Mac, usando lynx:

```
$ zzloteria sena
sena:

Looking up www1.caixa.gov.br
Making HTTP connection to www1.caixa.gov.br
Sending HTTP request.
HTTP request sent; waiting for response.
HTTP/1.1 302 Found
Data transfer complete
HTTP/1.1 302 Found

lynx: Start file could not be found or is not text/html or text/plain
      Exiting...
```

**Comment by aureliojargas** [comment]
Achei este outro link: http://www.caixa.gov.br/wap/r_megasena.asp

Traz o resultado num formato diferente, me animei, mas dá o mesmo problema pelo lynx :/

**Comment by aureliojargas** [comment]
Mais um, em XML, mesmo problema: http://www1.caixa.gov.br/rss/asp/geraXML_rss_loterias.asp?canal=megasena

É legal que eles disponibilizam o resultado de várias maneiras, mas poderia ter uma direta, sem frescura que quebra o lynx :/

**Comment by aureliojargas** [comment]
Tentei, sem sucesso, usar o `curl` como alternativa. Tentei também mudar o User Agent pra simular acesso de um navegador normal, pensando que poderia ser algum tipo de bloqueio específico pra ferramentas de linha de comando, mas não é:

```
$ curl -A "Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.2.3) Gecko/20100401 Firefox/3.6.3" -v http://www.caixa.gov.br/wap/r_megasena.asp
* Hostname was NOT found in DNS cache
*   Trying 200.201.162.223...
* Connected to www.caixa.gov.br (200.201.162.223) port 80 (#0)
> GET /wap/r_megasena.asp HTTP/1.1
> User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.2.3) Gecko/20100401 Firefox/3.6.3
> Host: www.caixa.gov.br
> Accept: */*
> 
< HTTP/1.1 302 Found
< Location: http://www.caixa.gov.br/wap/r_megasena.asp
< Set-Cookie: security=true; path=/
< Connection: close
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< 
* Closing connection 0
```

Estranho que parece que está tudo normal e o retorno foi um documento vazio.

**Comment by aureliojargas** [comment]
Em último caso, tem esse serviço alternativo: http://servicos.albertino.eti.br/Loteria.asmx?op=GetLotoFacil_UltimoConcurso_JSON

Pelo que vi o cara mantém os resultados atualizados. Há saídas em outros formatos, como XML. Mas o melhor é consultar direto a fonte, a Caixa.

Por falar nisso, uma `zzjson` não seria uma má ideia :)

**Comment by kemelzaidan** [comment]
Tem uma ferramenta bem legal que talvez possa ser usada com o funçõeszz que
é o jq https://stedolan.github.io/jq/
É um processador de json em linha de commando. Talvez seja a solução para
utilizar apis ao invés de páginas web e se livrar desses problemas de
alteração na página, contudo, seria uma dependência a mais para o programa.



Kemel Zaidan - @kemelzaidan
http://about.me/kemel

Eu prefiro receber documentos em Open Document Format
<http://pt.wikipedia.org/wiki/OpenDocument>.

Em 1 de fevereiro de 2015 09:04, Aurelio Jargas <notifications@github.com>
escreveu:

**Comment by kemelzaidan** [comment]
Tb encontrei essa página que tb tem uma api: http://developers.agenciaideias.com.br/loterias

**Comment by aureliojargas** [comment]
@itamarnet como a Caixa está cada vez mais fechando o cerco aos robôs, de repente a solução será escolhermos um site alternativo :/

**Comment by itamarnet** [comment]
@aureliojargas Parece ser um caminho inevitável.
Mas os links alternativos, por exemplo, que passou nos comentários anteriores, nenhum funcionou!
Mal sinal :/

Cheguei a fazer testes baixando os arquivos zipados, e extraindo os arquivos "htm".
São fáceis de trabalhar, sem frescuras e individualmente nem são tão pesados, mas são cumulativos.
E como já comentei no issue #178, essa é uma opção que não me agrada, mas ainda sim é uma opção.

Ainda fica a pergunta: alguma sugestão adicional?

**Comment by aureliojargas** [comment]
A `zzloteria2` tornou-se a `zzloteria` oficial (veja issue #36). Com isso, agora temos uma `zzloteria` funcional e este issue pode ser fechado.

A pegadinha é que ela requer o navegador `links` para funcionar. Não é o ideal, mas é melhor do que nada. Abri o issue #206 para tentarmos resolver isso no futuro.
