### ISSUE TITLE
zzcinemais e zzcinemark15h: Resultados irregulares

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#169]
A lista de filmes apresentadas por ambas zzs tem apresentados dados irregulares.
Nem todas as cidades retornam resultados.
No caso da zzcinemais, algumas das salas Cinemais foram transferidas Cinépolis.
No caso do zzcinemark15h, que enfatiza o horário de 15h para uma sessão mais barata, parece não corresponder a uma realidade atual, visto que algumas promoções tem dias e horários diferentes.
Possíveis soluções:
 - Apenas corrigir ambas zzs no escopo atual, retirando o que não atende.
 - Corrigir ambas zzs e criar uma zz adicional para incluir as salas do Cinépolis.
 - Apenas desativar ambas zz.
 - Descartar ambas as zzs e criar uma zz nova que englobe as 3 empresas.

Particularmente prefiro a última opção, mas é uma questão aberta.

**Comment by aureliojargas** [comment]
Se a das 15h não traz resultados confiáveis/úteis, eu a desativaria.

O resto eu não sei. Também não adianta termos muito trabalho para manter algumas funções, não compensa. Fique à vontade para reformar ou desativar.

**Comment by itamarnet** [comment]
Estou pensando em mudar o enfoque, ao invés de ser apenas 15h, trazer a programação completa.

A noite vou ver se fica bom dessa forma, mas já temos por conta disso, além dessa, mais 3 zzs que tratam de programação de cinema, a saber:  zzcinemais, zzcinepolis, zzcineuci.

Eu preferiria que todas estivessem em uma zz única, por exemplo: zzcinema, mas as particularidades de cada site faz ser uma tarefa ingrata.

Vou pensar melhor no assunto, mas no momento ainda as manterei separadas.

**Comment by itamarnet** [comment]
Solução adotada:
 - zzcinemark15k renomeada para zzcinemark, trazendo programação mais ampla da programação, veja commit 01d87d1a0480bf4681299a1848a6a509e036a55a
 - zzcinemais refeita para ajuste ao site, veja commit a54bb670d0126695b26afcfd0bf00d5e93604546
 - zzcinepolis criada para suprir as mudanças que ocorreram na zzcinemais commit cb2423789d75ee76f6480597d61590c86bc94381

**Comment by aureliojargas** [comment]
:+1:
