### ISSUE TITLE
Redirecionar mensagens de erro e avisos.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#171]
As inúmeras funções existentes podem ser usadas isoladamente, sem depender de outra função.

Contudo há um número consideráveis de funções que dependem de outras funções para seu bom funcionamento, tanto que há no cabeçalho um campo específico para isso: "Requisitos:" 

Sob esse ótica e também na possibilidade de alguma função ser usada dentro de outro Script, quero sugerir que todas as informações que não sejam o retorno esperado, como forma de uso e mensagens de erro, fossem redirecionadas para a saída de erro padrão (stderr).

Muitas das funções exibem essas mensagens na saída padrão (stdout), o que pode ser um problema dependendo o contexto onde esteja sendo empregado.

Dessa forma poderá ser usada a sintaxe "2>/dev/null" para omissão das mensagens de erro, sem comprometer o retorno da informação realmente.

Ao meu ver essa abordagem faz sentido.

**Comment by aureliojargas** [comment]
Concordo!

Porém, esta como é uma mudança grande e estrutural, recomendo fazer somente depois de lançada a versão 2015, senão não vamos terminar nunca :)

**Comment by itamarnet** [comment]
Aurelio

Lamento, mas eu já tinha feito quase tudo quande li essa mensagem.
Apenas conclui alguns poucos que faltavam.
Mas fiz os testes aqui e tudo funcionou conforme esperado. Os erros e acertos antes das modificações se mantiveram.
Só falta redirecionar as mensagens de erro quando tem a opção '-e' selecionada nas ferramentas da zztool.

**Comment by itamarnet** [comment]
Feito nos commits:
 - 14d8bbf810fb013d7f6fd6d334118904682a83bc
 - 6b01d13694dc28f55fdf21d93781c2fc68c56a02
 - c70df8b1b9fa288927309099f41548d60e8190c2

**Comment by itamarnet** [comment]
Está certo @aureliojargas , realmente vc já havia comentado, mas como eu estava com quase 90% da mudança feita, resolvi concluir.

Mas ainda acho que o ganho com o redirecionamento das mensagens de erro valeu o esforço.

Hoje a noite eu faço a verificação, testo e providencio as alterações em todas as funções afetadas.
Existem algumas que não foram usadas a ferramenta "zztool erro".
E a construção:
```
 test -n "$1" || { zztool uso funcao > /dev/stderr; return 1; }
```
mudo para:
```
 test -n "$1" || { zztool uso funcao >&2; return 1; }
```

**Comment by aureliojargas** [comment]
Ah sim, essa mudança é muito bem-vinda e torna as funções mais alinhadas com os padrões do Unix. Só não era a hora certa de se fazer isso, pois em fechamento de release devemos estabilizar o software. Logo após o release seria a hora ideal para essa mudança. Eu deveria ter sido mais enfático na minha resposta inicial. Mas enfim, agora já foi, a gente resolve :)

**Comment by aureliojargas** [comment]
Tava aqui pensando, talvez seria bom criar um `zztool uso -e funcao`. Essa opção `-e` serviria pra mandar a mensagem de uso pra STDERR, evitando ter que fazer isso em cada função.

``` 
test -n "$1" || { zztool uso feed >&2; return 1; }
```

Ficaria:

``` 
test -n "$1" || { zztool uso -e feed; return 1; }
```

Que tal?

Pena que não dá pra centralizar o `return 1` também...

**Comment by itamarnet** [comment]
Boa pedida!
É só mudar de:

```
	uso)
		# Extrai a mensagem de uso da função $1, usando seu --help
		zzzz -h "$1" -h | grep Uso
```
para:
```
	uso)
		# Extrai a mensagem de uso da função $1, usando seu --help
		if $erro -eq 1
		then
			zzzz -h "$1" -h | grep Uso 2>&1
		else
			zzzz -h "$1" -h | grep Uso
		fi
```

Quer que eu faça essa mudança? Ou prefere testar antes?
Eu tenho certeza que funciona, mas só mais tarde terei a comprovação.

Se assim for, apenas retiro ``` /dev/stderr ``` que foram inclusas.

O return 1 é uma pena, mas acho que não há outra forma mesmo.

**Comment by aureliojargas** [comment]
Show! :+1: 

Tinha esquecido que já temos o `$erro` pronto, na mão. Massa!

Já que você vai mexer nisso, pode mandar bala. Depois temos que adicionar mais testes pra essas mensagens de erro com stderr.

Ah, só não esquece do `test` depois do `if` ;)

**Comment by itamarnet** [comment]
Essa é boa!! Até tu esqueceu!!!
Pode deixar que não esqueço. É que na hora que escrevi foi apenas pra ilustrar onde seria o mais adequado alterar, e estava em meio a correria do "trampo"

**Comment by itamarnet** [comment]
Perfeito aqui também!
Usar ``` >&2 ``` no lugar ``` /dev/stderr ``` eliminou os erros. Desde o problema da codificação até ao fenômeno de cortar 2 caracteres iniciais da mensagem de erro.
Não entendi o motivo que gerou o problema, mas a solução foi eficaz.

**Comment by aureliojargas** [comment]
Corrigido nos commits dfe4b090e677f887f34464048f2d26138bc844f0 e be12f721cfcb4b2a999bbd66ab7d8648f29b92c7

**Comment by aureliojargas** [comment]
Somente para concluir, vou fazer um resumo do problema.

O problema de usar `> /dev/stderr` em vez de `>&2` foi discutido e investigado nos comentários do commit 0b804cc0a0c33c79ed6486781d54560d749f943d. Em resumo:

```bash
printf "%b\n" "$*" > /dev/stderr          # bug acontece
printf "%b\n" "$*" >&2                    # tudo certo
```

Este problema acontece somente ao executar os testes com o [clitest](https://github.com/aureliojargas/clitest), no uso normal da função ele não ocorre. Os testes que falhavam são do tipo deste:

```console
$ zzascii 1000; echo $?
O número máximo de colunas é 20
1
$
```

Havia dois comandos na linha de teste, e a função ZZ emitia a mensagem de erro diretamente para `/dev/stderr`.

Esta é a linha crucial dentro do clitest, que executa o teste:

```bash
# Execute the test command, saving output (STDOUT and STDERR)
eval "$tt_test_command" > "$tt_test_output_file" 2>&1
```

Que expandidas as variáveis, fica assim:

```bash
# Execute the test command, saving output (STDOUT and STDERR)
eval "zzascii 1000; echo $?" > "output.txt" 2>&1
```

Ou seja, a saída do `eval` (`stdout` e `stderr`) é sempre direcionada para um arquivo, porém o comando executado pelo `eval` havia mandado a saída normal para `/dev/stderr`. Isso funcionou bem no BSD, mas não no Linux. Trocando pra `>&2` deu certo em todos.
