### ISSUE TITLE
Função nova para limpar os brancos do resultado

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#172]
Um erro muito comum de encontrar, principalmente em funções que pesquisam na internet, são os espaços inúteis no resultado

* Linhas em branco no início
* Linhas em branco no final
* Espaços no início da linha
* Espaços no fim da linha

Para ajudar as funções a se manterem dentro do [Coding Style](https://github.com/funcoeszz/funcoeszz/wiki/Coding-Style), podemos criar uma função que se encarrega de fazer esta limpeza automaticamente.

Ainda não sei qual seria o nome ideial, e se deve ser uma função normal ou uma zztool. Mas a funcionalidade será remover os quatro itens da lista.

**Comment by itamarnet** [comment]
A idéia é boa e acredito que já tenhamos algumas funções que já façam parte do trabalho.
Temos:
 - zztool trim, zztool ltrim e zztool rtrim
 - zzlblank
 - zzlimpalixo

Aproveitando a combinação dessas ferramentas já disponíveis, ou ao menos com base nelas, seja viável e até relativamente fácil criar uma nova função com esse objetivo.

Que tal zzlimpablank ou zztrim? :)

**Comment by itamarnet** [comment]
Lancei uma nova função com o nome zzvtrim (a9dce5a8da351028e084df100e7966ad82d9da4b).
Não sou muito criativo, então ainda fica em aberto o nome e se quiser mudamos depois.

Veja se funciona direito ai contigo, e como sempre não resisti em usar uma boa dose de AWK.

Se tudo correr bem ai sim fechamos esse issue.

**Comment by aureliojargas** [comment]
Nossa, já fez? Isso é que é eficiência! :) E ainda está lotada de opções!

Espero que não fique chateado, mas essa função eu queria discutir o conceito, pra que o foco fique bem definido. A função que você fez é trim + squeeze + expand-tab, mas acho que deveria fazer somente trim.

O nome poderia ser `zztrim` mesmo, para cuidar tanto do trim vertical quanto horizontal.

O trim no meio acho que não deveria ter, pois quando se pretende fazer um trim, você não espera que se mexa em seu conteúdo, somente nos brancos ao redor. E o trim do meio, às vezes pode ser um squeeze (juntar brancos consecutivos) ou um trim (remover brancos), então já complica o conceito inicial.

O comportamento padrão, sem opções, seria remover todos: top, bottom, left, right. Assim, pro propósito de limpar a saída de outras funções, seria simplesmente:

```
$ZZWWWDUMP url | sed '...' | zztrim
```

Ao especificar opções, ela limita-se às opções informadas:

```
zztrim --top                            # somente remove linhas do início
zztrim --top --bottom                   # remove linhas do início e fim
zztrim --top --bottom --left --right    # início, fim, direita, esquerda (default quando sem opções)
```

As opções em inglês:

```
-t, --top
-b, --bottom
-l, --left
-r, --right
```

Fiquei na dúvida se em vez de `top/bottom` não seria melhor `head/tail`, pra manter-se na nomenclatura dos comandos Unix. Mas vai ter problema com a opção curta `-h` que já está tomada pelo `--help`.

As opções em português poderiam ser:

* topo
* rodape (?)
* direita
* esquerda

Mas não sei se é uma boa ideia. Se for fazer opções curtas vai confundir com as em inglês, e não gosto do nome rodapé. Talvez nessa seja melhor ser somente em inglês mesmo.

Também poderia ter `--horizontal` (igual a `-r -l`) e `--vertical` (igual a `-t -b`), porém a versão curta `-h` já está tomada pelo `--help`. Só se fizesse somente as longas, ou talvez `-H` e `-V` em maiúsculas.

O que você acha?

**Comment by itamarnet** [comment]
Que isso! Ficar chateado jamais.

Eu justamente deixei em aberto tanto o nome quanto o conteúdo para termos um rumo inicial. e qualquer consideração é proveitosa, mesmo que precise mudar tudo.

Quanto ao comportamento padrão atualmente elimina no topo, no final, à direita.
Espaços à esquerda por padrão são mantidos, pois temos 2 cenários no caso de apaga-los:
 - Elimina-se todos à esquerda ( -ll ).
 - Ou elimina um excedente, mas deixa o layout original intacto (-l ).
Acho essa uma questão mais delicada.

Esse dilema das opções em inglês ou português, curtas e longas eu também tive e sinceramente esperava sugestões para qual rumo seguir, tanto que a dúvida no ``` -h ``` foram quase idênticas.

A idéia das opções ``` --horizontal ``` e ``` --vertical ``` acho perfeita, e fácil de implementar.
Mas particularmente não curto as opções ``` -H ``` e ``` -V ``` em maiúsculas, apesar de parecer bem funcional ( Isso é só uma "frescura" minha, apenas não aprecio, mas sem motivo racional ).

**Comment by aureliojargas** [comment]
Essa questão do trim à esquerda mantendo o layout já foi muito bem resolvida pela zzlblank, não? Aí sobra pra zztrim o trim normal, de sempre apagar tudo. Se o cara quiser ambos, basta usar ambas funções:

```
cat texto | zztrim -t -b -r | zzlblank
```

Fiz o commit 929400174220d14eab9ebfe83b850df265c3b166 com uma versão inicial da zztrim, fazendo apenas as 4 operações originais de corte: cima, baixo, esquerda, direita. Sem espertezas, sempre apaga tudo o que encontrar. Não coloquei `-H` nem `-V` conforme requisitado :)

Demorou, mas consegui 4 comandos mágicos do sed que fazem as operações de maneira independente, então ficou fácil de combiná-los em um único script, o que simplificou muito o código da função e ficou bem flexível.

Os quatro comandos de corte até poderiam ser awk, por mim tanto faz. Mas acho que essa estrutura e escopo mais simples ficou melhor.

**Comment by itamarnet** [comment]
Ficou legal Aurelio.

Cara era apenas um comentário solto, podia ter deixado o ``` -H ``` e o ``` -V ```, é uma frescura sem justificativa lógica. hehe!

A função ficou massa, simples, direta e funcional.

Se puder faça as honras de apagar a nati-morta "zzvtrim" e seus arquivos de teste.

Valeu!

**Comment by itamarnet** [comment]
Aurelio

Antes de apagar os testadores da zzvtrim, testa a zztrim com o arquivo zzvtrim.in.txt, sem argumento.

Aqui em minha máquina os espaços à esquerda não são removidos em algumas linhas.

Acontece o mesmo contigo?

**Comment by aureliojargas** [comment]
Putz, é mesmo! :(

Vou arrumar, ainda bem que você pegou essa!

**Comment by aureliojargas** [comment]
Beleza, resolvido! Aproveitei e renomeei teu arquivos de testes pra zztrim.in.txt e tou usando ele também. Deveria ter feito isso desde o início...

**Comment by aureliojargas** [comment]
E já que não há restrições, então vou adicionar `-H` e `-V` :)
