### ISSUE TITLE
Trocar 'zztool [rl]?trim' por zztrim.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#175]
Com a chegada da zztrim as "zztool trim", "zztool rtrim" e "zztool ltrim" perderam o sentido, visto que fica uma redundância de função.
A troca das ocorrências dessas zztool pela nova função faz mais sentido e com ganhos adicionais.

**Comment by itamarnet** [comment]
Feito. Commit 984cf5669b26958d9f570c4ffd0568f7eddd6ddd

**Comment by aureliojargas** [comment]
@itamarnet vi que você trocou ocorrências de `zztool trim` por `zztrim` em vez de `zztrim -H`.

Lembra que a `zztrim` por padrão também faz o trim vertical. Isso não afeta o comportamento das funções alteradas?

**Comment by itamarnet** [comment]
Não afeta a funcionalidade.
Aliás até melhora nas que foram aplicadas, pois o trim vertical é até desejável.
E se houver necessidade, o que nos testes comigo não mostrou ser o caso, altero o código para adequar, mas o uso do zztrim será mantido.

**Comment by aureliojargas** [comment]
:+1:
