### ISSUE TITLE
Considerar a utilização do Travis

### ISSUE THREAD

**Issue by henriquemoody** [funcoeszz/funcoeszz#177]
Reparei que os testes estão quebrados, acho que seria uma boa idéia usar uma ferramenta de continuous integration  para evitar que isso aconteça.

O [Travis](https://travis-ci.org/) é gratuito e se integra perfeitamente com o GitHub.

**Comment by itamarnet** [comment]
Não cheguei a analisar profundamente o travis, (talvez o @aureliojargas  quem sabe!) mas os testes estão justamente ai para corrigir as funcoeszzz.
Na verdade os resultados do testes são os esperados e as funçoes é que deveriam fornecer as respostas no formato esperado, então as quebras são um alerta que alguma correção é que deve ser feita na função geradora.
Com certeza há casos em que os testes é que estão com problemas, mas cada caso é um item a ser analisado em particular, o que não é algo ruim, pois a capilaridade e especificidade é que tornam o cuidado ainda mais importante.

**Comment by henriquemoody** [comment]
Sim, @itamarnet, o que eu quiz  dizer com _testes quebrados_ é que eles não estão passando.
Provavelmente o que houve foi que as funções mudaram de comportamento mas os testes não foram atualizados, utilizar uma ferramenta de continuous integration evita que esse tipo de problema aconteça, pois sempre que os testes _quebrarem_ (começar a não passar mais) significa que algo, não esperado mudou.

Eu uso nos meus projetos pessoais, mas tem bem mais gente que usa, como o [Bats](https://github.com/sstephenson/bats), por exemplo.

**Comment by aureliojargas** [comment]
@henriquemoody está na minha lista de tarefas aprender sobre e usar CI em meus projetos. Como você já tem experiência com o Travis, o que precisa ser feito para as ZZ utilizarem ele?

**Comment by henriquemoody** [comment]
Após criar um cadastro no Travis com a conta do GitHub, é só ir em _Accounts_, clicar em _funcoeszz_ e habilitar o repositório (provavelmente será esse o link: https://travis-ci.org/profile/funcoeszz).

Pra dar pra vocês um background de como o Travis funciona: 1 build pode ter vários jobs, cada job é uma VM com o sistema operacional de sua escolha (Linux, sendo o Ubuntu o padrão, ou o OSX; Windows ainda não é suportado, até onde eu sei). Nessa VM você pode rodar **qualquer** comando com sudo por padrão.

Uma vez habilitado é só criar um arquivo `.travis.yml` na raiz do repositório com as diretivas. Veja http://docs.travis-ci.com/user/build-configuration/.

**Comment by henriquemoody** [comment]
PS.: O que determina que o build teve sucesso é o exit code do(s) comando(s) executado na chave `script` do arquivo `.travis.yml` de todos os jobs.

**Comment by aureliojargas** [comment]
Muito obrigado pelas informações @henriquemoody! Legal que dá pra testar em sistemas diferentes, isso será muito útil pra pegar problemas de portabilidade.

No momento estamos tentando fechar um release novo, então não dá pra ver isso agora. Mas depois do release, quero ver se implementamos o tal do Travis. Vou deixar esse issue aqui aberto para continuarmos o papo quando formos implementar.

**Comment by itamarnet** [comment]
:+1:

**Comment by itamarnet** [comment]
Puxa agora que entendi melhor a concepção do Travis.
Realmente é uma baita ferramenta e pode economizar muito de nossas dores de cabeça.
Valeu @henriquemoody! Grande sacada.

**Comment by aureliojargas** [comment]
[Usei o Travis no clitest](https://github.com/aureliojargas/clitest/blob/master/.travis.yml) e é excelente mesmo! Pode deixar que eu vou colocar aqui na ZZ também.

**Comment by aureliojargas** [comment]
Beleza, Travis adicionado no commit fd26111f5d88129781fa03fc01f5b0261b0bfb14.

Atualmente, o resultado não é muito animador, temos 104 erros no testador :cry:  Agora é tentar ir atrás e arrumá-los.

Depois que conseguirmos zerar isso, dá pra bloquear os futuros commits que quebrem os testes.

**Comment by aureliojargas** [comment]
Vou deixar esta issue aberta até que consigamos implementar o Travis totalmente, com testes passando 100% no Linux e Mac.

**Comment by itamarnet** [comment]
Uma coisa que considero fonte de erros seja a diferença como ``` lynx ``` e ``` links ``` exibem seu resultados.
Um bom ponto de partida é verificar essas diferenças, que provavelmente também existem em relação ao ``` w3m ``` também.

**Comment by aureliojargas** [comment]
É, isso será uma dor de cabeça :(

**Comment by itamarnet** [comment]
Um paliativo que pode ser feito a priori seria na linha 80 das ``` funcoeszz ``` trocar:
``` for ZZBROWSER in lynx links w3m ```
por:
``` for ZZBROWSER in links lynx w3m ```

**Comment by aureliojargas** [comment]
Bem, no momento, estou querendo ver a test-suite rodar 100% na minha máquina (Mac), usando o lynx mesmo, que é o browser para o qual os testes foram escritos.

Olha como está o status atual:

```
FAIL: 48 of 4401 tests failed
```

Vou abrir issues para os problemas que encontrei.

Na tua máquina os testes estão 100%? Era bom deixar redondo aí também, antes de começarmos a adaptar as coisas para o `links`.

**Comment by itamarnet** [comment]
Na minha máquina só há problemas efetivamente com a ``` zzjuntalinhas ``` e a ``` zzarrumanome ```.
Com a ``` zzpiada ``` também mas é instabilidade do site, por isso no momento a ignoro.

**Comment by aureliojargas** [comment]
Acabei de subir a alteração da `zzjuntalinhas`, confere aí se resolveu. As demais que quebrarem abra uma issue, por favor.

**Comment by aureliojargas** [comment]
Testes passando "quase" 100% no Linux: https://travis-ci.org/funcoeszz/funcoeszz

Coloquei o badge (a imagem tipo botão) lá no README do projeto, pra ter uma maneira rápida de saber o status atual. Clicar no botão vai pra página de log do último build, pra ver o que quebrou.

**Comment by itamarnet** [comment]
Opa, isso facilita em muito.
No Linux os erros que aparecem são devido a mudanças nos sites consultados, na velha história de ajustar-se a mudanças de layout ou conteúdo. Esse é um "problema" recorrente e permanente, mas que nada impede a continuidade do processo.
A exceção é ``` zzhora ``` que, pela segunda vez que me lembro, apresentou erro apenas por causa do momento do resultado feito pela função e o estabelecimento do tempo no testador.
Isso nem considero erro, é apenas um "circusntancial", que se aparecer no MAC, também não deve ser considerado.

**Comment by aureliojargas** [comment]
Nesse caso da `zzhora` é só ir no Travis e disparar o teste de novo, aí vai passar. Mas bom saber, nunca peguei esse caso :)

**Comment by aureliojargas** [comment]
@itamarnet Estou configurando o Travis pra rodar no Mac também. Lá o nome do executável do elinks é `elinks` mesmo, enquanto nas ZZ está como `links`. Rola mudar pra `elinks` e vai continuar funcionando em todos os lugares?

**Comment by itamarnet** [comment]
Nas distros que consultei, sempre havia a criação de um link simbólico para ``` links ```, então imaginava ser um comportamento padrão tanto no uso do ``` elinks ``` como do ``` links2 ```.
Melhor então é colocar como uma opção também no core, e torcer que as opções sejam as mesmas do ``` links ```.

**Comment by itamarnet** [comment]
@aureliojargas Como eu temia o ``` elinks ``` tem um comportamento diferente do ``` links ``` com opções diferentes inclusive.

Inusitado no Travis o Linux tem ``` links ``` e o Mac tem ``` elinks ```!
Eles podiam ter padronizado isso, mas vale como um novo desafio.

Então posso ir fazendo alterações aqui em um novo branch?
Ou você quer cuidar disso pessoalmente para acompanhar o processo em paralelo no seu Mac?

**Comment by aureliojargas** [comment]
Sério que será mais um navegador diferente pra suportar? Que saco isso...

Meu tempo está bem escasso, se você puder ir tocando será bom, senão vou emperrar as coisas :(

**Comment by itamarnet** [comment]
Sério mesmo camarada! Mais um navegador para configurar!

Mas deixa comigo, vou adequar para ter o ``` elinks ``` como uma nova opção, repetir os mesmos testes que fiz nos demais e aproveitar para corrigir os testes que voltaram a falhar.

Se a coisa "pegar" grito por um "help", mas toca tranquilo por ai.

No momento tudo está funcional no contexto que havia antes, exceto por alguns testes, então o que está sendo feito agora é uma evolução.

Como diria um bom coveiro: são ossos do ofício.

**Comment by aureliojargas** [comment]
Quanta disposição, que bonito de ver! Vai fundo então @itamarnet, o bom é que com o Travis você não depende mais de mim pra saber como as coisas funcionam (ou não) no Mac 😄

**Comment by aureliojargas** [comment]
Vi que você já atualizou o core para suportar o `elinks`, muito massa! :+1:

Tava olhando o [build do Travis no Mac](https://travis-ci.org/funcoeszz/funcoeszz/jobs/126527845), parece que não tem `-width` no elinks:

```
[FAILED #336, line 3] zzblist 200.199.198.197
@@ -1 +1,2 @@
+ELinks: Unknown option -width
 O IP não está em nenhuma blacklist
```

Arrumado isso, acho que podemos considerar o Travis implantado com sucesso.

**Comment by itamarnet** [comment]
Isso eu já tinha visto meu camarada, e não é só ``` -width ``` tem bem mais itens, como ``` user-agent ```, ``` cookie ```, lista de links e outros detalhes.

Estou trabalhando nisso!

Tea for me!

**Comment by itamarnet** [comment]
@aureliojargas Meu camarada, essa jornada do ``` elinks ``` está sendo árdua!

Em primeiro lugar a versão do ``` elinks ``` estável disponível para instalação no Mac tinha problemas com vários sites, onde reportava erro de socket, especialmente em sites com conexão segura.
Precisei trocar pela versão ``` devel ``` que não apresenta esse bug.

Em segundo lugar, a ``` zzloteria ``` não funcionava de jeito nenhum, mas na tentativa de fazer funcionar descobri que há ``` links ``` para o Mac usando o ``` Homebrew ```. Através do site http://braumeister.org/ foi possível pesquisar e comprovar a disponibilidade do ``` links ```. Com isso refiz os testes que já havia feito com ``` elinks ```.

Nesse momento, não vou corrigir nesse branch o problema com ``` zzmariadb ``` que você já fez no master, e nem corrigir a ``` zzcut ``` pois a natureza do problema não é escopo. Outros itens que foram corrigidos no processo, e que não faziam consulta diretamente a internet, eram de certa forma requisitos ou dependentes indiretos desses que precisaram dessas alterações.

Então assim que possível confira o que foi feito,  e com seu "de acordo" faço um Pull Request. No momento que escrevo só tenho pendência com a ``` zzcoin ```, mas o site está em manutenção então vou aguardar para conferir se essa função vai precisar de ajustes e depois uma checagem final com uso de ``` links ``` e ``` elinks ``` no Mac.

Está quase!

**Comment by aureliojargas** [comment]
Putz cara, eu estou preocupado com esse caminho multi browser que estamos tomando. Está tornando nosso software mais complexo.

Tem certeza que não prefere tentar centralizar tudo num ` curl` , que é universal, do que investir em suportar diversos softwares diferentes, cada um com seus bugs e limitações?

Quanto à branch, pode abrir o Pull Request desde o início dos trabalhos, pra ficar mais fácil discutir e ver o diff. Só coloca um WIP: no início do título pra deixar claro que é um work in progress.

**Comment by itamarnet** [comment]
Cara, você leu meus pensamentos. Nesse fim de semana foi justamente nisso que pensei quando encarei a diversidade de problemas que a situação apresentou.

Nesse branch que estou trabalhando, o ``` zztool source ``` apenas usa o ``` curl ```, e o ``` zztool download ``` opta apenas entre ``` wget ``` e ``` curl ```. Já é um passo nessa direção que sugere.

Mas nem tudo são "flores" nesse caminho também.
Quando fiz as últimas alterações na ``` zztv ``` observava que as vezes funcionava e as vezes falhava, sem que houvesse qualquer alteração no código. O que comprovei, foi que a tag ``` a ``` aleatoriamente alterava as posições dos atributos ``` title ``` e ``` href ```, mas isso apenas acontecia na linha de comando e não usando navegadores tradicionais como Firefox e Chrome.
Acredito que a engine por trás do site por alguma razão faça essa jogada, e os navegadores corrijam isso internamente. Mesmo usando o ``` user-agent ``` para mascarar a identidade o problema se repetia.
Mesmo assim usei o ``` curl ``` junto de um artifício com ``` awk ``` para contornar essa variação.

O que sugiro é fechar como está, e depois realizo testes apenas usando o ``` curl ``` num outro "branch". Mas já prevejo que a ``` zzloteria ``` não terá chance, mas se for o caso restringimos o uso do ``` links ``` apenas nela.

Mas de positivo nisso tudo, foi ver a versatilidade que o uso do Travis proporciona podendo explorar amplamente cada possibilidade, e vai um agradecimento ao @henriquemoody  pela oportuna sugestão.

De volta a "prancheta"?

**Comment by aureliojargas** [comment]
Dei uma olhada lá no PR, muita alteração mesmo, que trabalheira! :(

Mesmo que uma ou outra função como a `zzloteria` ainda dependam de um browser específico, quanto mais conseguirmos migrar de browser pra `curl`, menos chances de quebrar coisas em um browser específico. A longo prazo deve compensar.

Aí nos filtros que parseiam HTML o lance é fazer eles bem robustos, evitando matches muito precisos que quebram se alterar um único caractere. Aí o lance é ir "grepando" aos poucos, fazendo mais comandos, mas que resistam a mudanças mais simples no HTML. Talvez a `zzxml` dar uma boa ajuda no processo.

Quanto ao Travis, é show de bola mesmo!

**Comment by itamarnet** [comment]
Beleza @aureliojargas .

Vou aguardar ver se o site http://www.linuxsecurity.com.br/ volta a ativa até hoje a noite.
Então faço as alterações necessárias, e na sequência o "merge".

Antes da empreitada pela uso do ``` curl ```, vou avaliar a implementação do ``` zztestar ``` e assim deixar o core mais leve.

Pode ser?

**Comment by itamarnet** [comment]
Acho que com esse resultado podemos considerar esse issue concluído. 
O que acha?

https://travis-ci.org/funcoeszz/funcoeszz/builds/127582506

**Comment by aureliojargas** [comment]
Que coisa linda esses builds verdinhos!
🎉  🎉  🎉  🎉  🎉

**Comment by aureliojargas** [comment]
O que acha de integrarmos o Travis "de verdade" em nosso fluxo? No sentido de ele sempre verificar cada mudança e não deixar mergear algo se isso fizer os testes quebrarem?

**Comment by itamarnet** [comment]
Essa é uma ótima ideia! Ia evitar muita dor de cabeça.
Se quiser já pode integrar agora.

**Comment by aureliojargas** [comment]
O Travis já está integrado, mas para que ele realmente faça seu papel, nós temos que mudar nosso fluxo de trabalho. Ele trabalha em cima de Pull Requests somente, não de commits individuais.

A ideia é que toda e qualquer mudança sempre venha de uma branch específica, a ser mergeada na master. O Travis irá avisar se algum teste estiver falhando.

Então, em nosso caso, não poderia mais fazer o que fazemos hoje, de fazer push direto pra master. Teria que sempre fazer as alterações em uma branch separada, subir esta branch pro GitHub e abrir um Pull Request. Aí o Travis fará a sua mágica e avisará se tudo está ok.

É mais burocrático, mas organiza melhor as mudanças, e acabam os comentários em commits isolados. Dessa maneira, cada conjunto de mudanças é agrupado em um único PR, onde podemos discutir, melhorar, e testar automaticamente.

Como eu não estou tendo muito tempo pra me dedicar ao projeto, você mesmo pode abrir seus PRs e mergeá-los sem esperar pelo meu OK. No fim não afeta tanto, é mais a disciplina de sempre criar branches diferentes para cada tipo de mudança.

O que acha?

**Comment by itamarnet** [comment]
Fechou então.
Toda e qualquer alteração será com base em branch separado sempre!

Eu particularmente nessa última empreitada vi a enorme vantagem de trabalhar assim.
É mais organizado, não há conflitos de mudanças pontuais feitas por cada um, e conflitos se ocorrerem podem ser melhor gerenciados.

E excepcionalidades, se forem necessárias, trataremos a parte.

Combinado!

**Comment by aureliojargas** [comment]
Maravilha, fechado então! Travis verdinho daqui pra frente 👍

**Comment by henriquemoody** [comment]
Maravilha! 🎉

**Comment by aureliojargas** [comment]
@henriquemoody Muito obrigado pela issue e pelas informações sobre o Travis, demorou mas conseguimos :)
