### ISSUE TITLE
zzloteria: Erro em concursos antigos.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#178]
Resultados de concursos antigos não respondem mais para as seguintes loterias:
 - quina
 - megasena
 - lotomania
 - lotofacil

**Comment by itamarnet** [comment]
Não consegui uma alternativa no portal da caixa para os resultados antigos das loterias citadas.
Os últimos resultados funcionam perfeitamente, e as outras loterias não citadas continuam funcionando do modo antigo.
Especulo que o site da Caixa esteja numa fase de transição, e que em breve as demais loterias também deixem de funcionar na pesquisa de concursos anteriores.
Há duas possíveis saídas:
 - Deixar de pesquisar concursos anteriores, ficando apenas com o resultados mais recentes.
 - Ou usar os arquivos "zipados" disponíveis para download para realizar essa pesquisa.

Confesso que nenhuma das alternativas me agrada, porém a segunda parece mais promissora.
Alguma sugestão?

**Comment by aureliojargas** [comment]
Eu acredito que a imensa maioria dos usuários só quer saber o resultado mais recente, pra ver se ganhou ou não. Por mim pode desativar os anteriores sem problema.

**Comment by itamarnet** [comment]
Cara por falar nisso e a zzloteria?
Eu continuo tendo problemas com retorno dela, e vi que há mais casos de gente reclamando conforme issue #159.
Tentei algumas alternativas usando configurações diferentes tanto com o curl, w3m, wget e lynx e nada funcionou.
Apenas com o links, que é usado na zzloteria2, tive retorno.
E na sua máquina, alguma novidade? Alguma perspectiva nova?

**Comment by aureliojargas** [comment]
Aqui não funciona nenhuma :(

**Comment by itamarnet** [comment]
Optei por corrigir algumas pequenas falhas de filtro e usar o arquivo zipado para concursos anteriores.
Deixei apenas com a opção de uso o ``` links ``` ao invés do ``` lynx ```, que é utilizado na variável ``` $ZZWWDUMP ``` e em outras.
Se não tiver no sistema, sai com mensagem sugestionando a instalação.
Andei pesquisando as opções de links alternativos nos comentários feitos no issue #159, mas no momento da consulta estavam todos inoperantes.
@aureliojargas se puder testar e ver como está, pois não tenho muita certeza se consegui manter compatibilidade.
Aguardo retorno, mas de der certo, o que acho difícil logo de cara, pode fechar esse issue.

**Comment by aureliojargas** [comment]
@itamarnet nossa, estou vendo o diff aqui, foi uma reforma geral! Você pode atualizar os testes para contemplar também as opções de concursos anteriores para todas as loterias? Nestes testes o resultado será sempre igual, não? Aí não precisa filtrar com o sed. Enquanto isso vou ver como instalar o links aqui.

**Comment by aureliojargas** [comment]
Ah, nos testes atuais, tem que lembrar de colocar o `;` antes do `}` no sed, igual no issue #195.

```
sed: 1: "s|[0-9][0-9]/[0-9][0-9] ...": bad flag in substitute command: '}'
```

**Comment by itamarnet** [comment]
De novo esqueci!
Mas também fui me meter a querer fazer um ``` sed ``` tão comprido!
Isso é uma área de domínio sua e estou ousando a fazer um ``` sed ``` tão longo.
Eu ia fazer testes com os concursos anteriores, mas quando vi já era 3:00h da "madruga", e a "patroa" não ficou feliz com isso, então tive que parar. Acho que nesse contexto você me entende. :)

**Comment by aureliojargas** [comment]
Claro, sem problema :)

Não tem pressa, a hora que puder atualize, que daí eu testo aqui pra ver se bateu. E se bater, já tornamos ela oficial e encerra de vez essa novela das `zz*2`.

**Comment by aureliojargas** [comment]
Rodei os testes aqui.

Deu problema de alinhamento na duplasena (printf + ª). Talvez só trocar `1ª` por `1a` pra ser rápido, ou usar logo a `zzpad`.

```
--------------------------------------------------------------------------------------------------------------------------------------------------------------
[FAILED #3, line 24] zzloteria2 duplasena | sed '2,3{s/[0-9][0-9]/99/g;};4{s/[0-9]\{1,\}/NUM/;};s|[0-9][0-9]/[0-9][0-9]/[0-9][0-9][0-9][0-9]|DATA|;5,${s/[123]ª/Pª/;s/ [0-9.]\{1,\} \{1,\}/ QTDE           /;s/ [0-9.,]\{1,\}/ VALOR/;}'
@@ -4,11 +4,11 @@
    Concurso NUM (DATA)
    Acumulado em R$ VALOR para DATA
      Faixa       Qtde.          Prêmio
-     Pª Sena    QTDE           VALOR
-     Pª Quina   QTDE           VALOR
-     Pª Quadra  QTDE           VALOR
+     Pª Sena     QTDE           VALOR
+     Pª Quina    QTDE           VALOR
+     Pª Quadra   QTDE           VALOR
                  
-     Pª Sena    QTDE           VALOR
-     Pª Quina   QTDE           VALOR
-     Pª Quadra  QTDE           VALOR
+     Pª Sena     QTDE           VALOR
+     Pª Quina    QTDE           VALOR
+     Pª Quadra   QTDE           VALOR
--------------------------------------------------------------------------------------------------------------------------------------------------------------
[FAILED #12, line 179] zzloteria2 duplasena 1000
@@ -4,11 +4,11 @@
    Concurso 1000 (06/09/2011)
    Acumulado em R$ 1.950.000,00 para 09/09/2011
      Faixa       Qtde.          Prêmio
-     1ª Sena    0              0,00
-     1ª Quina   55             2.224,60
-     1ª Quadra  2368           49,20
+     1ª Sena     0              0,00
+     1ª Quina    55             2.224,60
+     1ª Quadra   2368           49,20
                  
-     2ª Sena    1              163.137,83
-     2ª Quina   77             1.589,00
-     2ª Quadra  2560           45,51
+     2ª Sena     1              163.137,83
+     2ª Quina    77             1.589,00
+     2ª Quadra   2560           45,51
```

**Comment by aureliojargas** [comment]
A data da timemania (e somente dela), veio sem o zero no mês:

```
[FAILED #10, line 153] zzloteria2 timemania 600
@@ -1,8 +1,8 @@
 timemania:
    13 - 19 - 27 - 29 - 42 - 44 - 57 
    Time: YPIRANGA/AP
-   Concurso 600 (15/07/2014)
-   Acumulado em R$ 4.200.000,00 para 17/07/2014
+   Concurso 600 (15/7/2014)
+   Acumulado em R$ 4.200.000,00 para 17/7/2014
      Faixa       Qtde.          Prêmio
      7 ptos      0              0,00
      6 ptos      12             8.895,15
```

**Comment by aureliojargas** [comment]
quina, megasena, lotofacil e lotomania deu erro no `mv`:

```
$ zzloteria2 quina 3000
mv: rename /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/D_QUINA.HTM to /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.quina.htm: No such file or directory
No such file or directory
awk: trying to access out of range field -2
 input record number 1, file 
 source line number 1
awk: trying to access out of range field -7
 input record number 1, file 
 source line number 1
awk: trying to access out of range field -8
 input record number 1, file 
 source line number 1

$ zzloteria2 megasena 1111
mv: rename /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/d_megasc.htm to /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.mega.htm: No such file or directory
No such file or directory
awk: trying to access out of range field -2
 input record number 1, file 
 source line number 1
awk: trying to access out of range field -7
 input record number 1, file 
 source line number 1
awk: trying to access out of range field -8
 input record number 1, file 
 source line number 1
megasena:
    -  -  -  -  - 
   Concurso 1111 ()
     Faixa       Qtde.          Prêmio
     Sena                       
     Quina                      
     Quadra                     

$ zzloteria2 lotofacil 1099
mv: rename /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/D_LOTFAC.HTM to /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.lotofacil.htm: No such file or directory
No such file or directory
awk: trying to access out of range field -2
 input record number 1, file 
 source line number 1
awk: trying to access out of range field -11
 input record number 1, file 
 source line number 1
awk: trying to access out of range field -7
 input record number 1, file 
 source line number 1

$ zzloteria2 lotomania 750
mv: rename /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/D_LOTMAN.HTM to /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.lotomania.htm: No such file or directory
No such file or directory
^C      <-------- congelou
```

**Comment by aureliojargas** [comment]
Fora estes problemas, os demais testes passaram! Estamos chegando lá :)

**Comment by itamarnet** [comment]
Vamos por parte:
 - Essa da data no timemania foi bem inesperada, mas pelo que me lembro não é difícil, apenas usar como mais um requisito a ``` zzdata ``` ou ``` zzdatafmt ```, mas é bom considerar que pode acontecer com outras loterias, visto que comigo todos os testes tiveram sucesso.
 - Considerei usar o ``` zzpad ```, mas temi que poderia ser mais uma fonte de problema, e pelo visto foi justamente o não uso é que deu problema. Concordo com essa solução.
 - O erro do ``` mv ``` não acredito ser dele, mas dos comandos que o antecedem. Tem um ``` wget -q ``` e um ``` unzip -q -o -d "${ZZTMP%/*}" ```, e provavelmente um deles é que falha, mas como redireciono a saída de erro para ``` /dev/null ``` isso não aparece. Poderia ver a parte se a sintaxe deles funciona ai em sua máquina?

E a instalação do ``` links ```? Tem pacotes nativos para o Mac ou foi a partir do código fonte?

**Comment by itamarnet** [comment]
Estava olhando um manpage on-line do unzip para MAC ( https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/unzip.1.html ) e parece que a opção ``` -d "${ZZTMP%/*}" ``` precisa estar após o nome do arquivo a ser descompactado.
Pode confirmar isso? No meu caso o posicionamento dessa opção não influencia.

**Comment by aureliojargas** [comment]
Opa, desculpe, somente agora pude voltar. Os dois primeiros problemas se foram, valeu! Mas o problema do `mv` continua :( Vou investigar por aqui hoje.

Apareceu um detalhe aqui que não sei se é bug ou comportamento esperado do site:

```
$ zzloteria2 lotomania
lotomania:
   02 - 07 - 17 - 18 - 28 - 35 - 46 - 47 - 50 - 55
   59 - 63 - 64 - 65 - 69 - 71 - 74 - 85 - 86 - 90
   Concurso 1541 (25/03/2015)
   Acumulado em R$ 28/03/2015
     Faixa       Qtde.          Prêmio
     20 ptos     0              0,00
     19 ptos     7              30.290,36
     18 ptos     102            2.078,75
     17 ptos     920            144,04
     16 ptos     5.677          23,34
      0 ptos     0              0,00
```

O acumulado veio uma data em vez de um valor.

**Comment by itamarnet** [comment]
Rapaz! Essa da lotomania é mais um mistério!
Não me lembro de ter mexido no trecho que cuida do acumulado da lotomania de concurso mais recente.
Só posso imaginar 2 coisas:
 - Mudança de ontem pra hoje do layout de onde vem a informação.
 - Ou o erro já existia e eu não havia percebido.

No atual momento não descarto nenhuma das possibilidades. Vou verificar.

**Comment by aureliojargas** [comment]
O acumulado na lotomania ainda tem alguma coisa errada:

```console
$ zzloteria2 lotomania
lotomania:
   10 - 12 - 13 - 15 - 16 - 17 - 21 - 22 - 27 - 39
   40 - 61 - 67 - 68 - 72 - 75 - 85 - 88 - 92 - 97
   Concurso 1543 (04/04/2015)
   Acumulado em R$ 39 para 39
     Faixa       Qtde.          Prêmio
     20 ptos     3              11.731.899,50
     19 ptos     79             33.192,13
     18 ptos     1.242          2.111,25
     17 ptos     11.189         146,47
     16 ptos     68.020         24,09
      0 ptos     5              262.217,83
$
```

Acumulou em R$39? :)

**Comment by itamarnet** [comment]
É a segunda vez faço correção no valor do acumulado para a lotomania.
A caixa está de brincadeira :/
Acho que dessa vez contornei o problema agora e futuramente.
Vide commit 70c074212fff7522b31bcb83c3af8d8e88afe9d1

**Comment by aureliojargas** [comment]
Aeeeee, agora sim:

```console
$ zzloteria lotomania
lotomania:
   10 - 12 - 13 - 15 - 16 - 17 - 21 - 22 - 27 - 39
   40 - 61 - 67 - 68 - 72 - 75 - 85 - 88 - 92 - 97
   Concurso 1543 (04/04/2015)
   Acumulado em R$ 400.000,00 para 08/04/2015
     Faixa       Qtde.          Prêmio
     20 ptos     3              11.731.899,50
     19 ptos     79             33.192,13
     18 ptos     1.242          2.111,25
     17 ptos     11.189         146,47
     16 ptos     68.020         24,09
      0 ptos     5              262.217,83

$
```

Por sinal, boa solução usando `$NF`!

O problema do `mv` não sei se vou conseguir investigar hoje. Mas está na minha lista.

**Comment by itamarnet** [comment]
Por falar em ``` mv ```, eu não consegui reproduzir o problema aqui mesmo usando o FreeBSD.
Portanto não tenho sugestão para dar sobre esse problema em especial.
Vou procurar ver se em uma variante tipo PC-BSD, GhostBSD ou DragonFlyBSD aparece.
Vamos ver!

**Comment by aureliojargas** [comment]
Sabe qual era o problema do `mv`? Eu não tinha o `wget` instalado... Instalei e tudo funcionou normal :/ Como a saída de erro estava indo pra `/dev/null`, não pude ver o problema antes.

O `wget` não é instalado por padrão no Mac (nem o `links`). Tem que instalar via métodos alternativos, como o [homebrew](http://brew.sh/). A zzloteria usa ambos, então ela é um caso especial que só funciona por padrão no Linux.

De qualquer forma, assim como tem a mensagem explicativa do `links`, era bom fazer a verificação pelo `wget` também quando for pesquisar concursos antigos (para pesquisa dos concursos atuais ele não é necessário). Também era bom condicionar a execução do `unzip`, `mv` e `rm` subsequentes ao sucesso do comando anterior, pois qualquer erro ali o resto deixa de funcionar.

@itamarnet você que conhece bem o código da `zzloteria`, pode cuidar disso?

**Comment by aureliojargas** [comment]
Ah, tentei baixar o `.zip` da Caixa com outros comandos além do `wget`, como o `lynx` e o `curl`, mas não funcionou. Esse site é uma djanha mesmo...

Ei, olha só, com o `links -source` funcionou pra baixar o `.zip`! Então não precisamos adicionar outra dependência à `zzloteria`, basta só o `links` mesmo. Pra acessar os HTML e baixar o ZIP.

Pode deixar que essa alteração eu faço, já que é mais simples.

**Comment by itamarnet** [comment]
Ainda bem que avisou, eu já tinha feito algumas alterações em função do que havia dito, mas vou aguardar.

Bom saber que o ``` links ``` também pode ser usado assim. Show!
Mas confesso que me surpreendeu saber que o ``` wget ``` não vem por padrão no Mac.
Vivendo e aprendendo.
Modo "stand by".

**Comment by aureliojargas** [comment]
Beleza, já fiz o commit na `zzloteria` e não vou mais mexer nela. Unlocked :)

**Comment by aureliojargas** [comment]
Ah, olha só:

```
rm -f ${ZZTMP}.lotofacil.zip ${ZZTMP%/*}/*.GIF
```

Essa parte final de apagar `*.GIF` na pasta temporária das ZZ é meio perigosa, pois pode apagar possíveis arquivos de outras funções.

Não tem como especificar os arquivos que foram criados somente? Ou quem sabe guardar todos estes arquivos temporários dentro de uma pasta `${ZZTMP}.lotofacil` e depois só apagar a pasta?

**Comment by itamarnet** [comment]
Pois é @aureliojargas 

Estava verificando a ``` zzloteria ``` em concursos antigos da lotofácil, lotomania, megasena e quina e notei que se existir o arquivo ``` .htm ``` antes ele não era mais sobre-escrito.
Então preventivamente procedo com a remoção do arquivo, e já aproveitei para atualizar a remoção dos arquivos ``` .GIF ``` correspondentes.

Ver em 52dd6c002fe6e891093956a65757604f5018dea5

**Comment by itamarnet** [comment]
@aureliojargas Tudo não passou de um alias esquecido que modificava o comportamento do ``` mv ```.
Devidamente testado, e funcionando 100%.
Vou fechar esse issue, se encontrar algum problema ( acredito que não tenha mais ) reabrimos.

Ver commit: f2541ffae410293c561a574e3bbf32167b8636c3

**Comment by aureliojargas** [comment]
Showwwwwwwww! Nem acredito que depois de tantos anos de novela, resolvemos todos os problemas da zzloteria :)
