### ISSUE TITLE
zzascii: caracteres UTF-8 saindo escapados no Ubuntu e Mint.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#179]
As seguintes construções para obtenção de caracteres UTF-8, no Ubuntu e Mint falham durante os testes apenas.
Em seu lugar aparece codificado em sua forma hexadecimal.
```
caractere=$(printf "\x$hexa")
```
```
caractere=$(printf "\xC2\x$hexa")
```
```
hexa_conversao=$(printf '%X' $((decimal - 64)))
caractere=$(printf "\xC3\x$hexa_conversao")
```
Obs.: A versão do Mint é baseado no Ubuntu
Mas funcionam perfeitamente no Slackware, CentOS e Debian.

Mas o antigo formato, baseado em awk, funciona em todas as distribuições
```
caractere=$(awk 'BEGIN { printf "%c", '$decimal' }')
```

Desconfio que tenha relação com o Dash, que é o shell usado no Ubuntu.

Testes em outras distros poderiam ser mais conclusivas.
Obs.: O fato ocorre apenas durante os testes, no uso normal funciona sempre.

**Comment by aureliojargas** [comment]
No BSD, o awk não funciona, pois ele não entende os caracteres multibyte do UTF-8 (qualquer char cujo decimal é maior que 128)

```
$ awk 'BEGIN { printf "%c\n", 161 }'
?
```

**Comment by itamarnet** [comment]
Se não funciona, não podemos considerar como opção.

Todavia acho que talvez esse issue não caiba aqui, visto que o uso normal não é afetado.
Acredito que esteja mais ligado ao clitest quando roda no Ubuntu ou seus derivados.

Infelizmente estou limitado nas opções para testar em outras distros no momento, e não sei se posso dar um feedback melhor do que esse. :(

**Comment by aureliojargas** [comment]
Consegui reproduzir o erro. O problema é que o printf do dash não tem suporte ao `\x` para mostrar um caractere em hexadecimal. Trecho da man page:

```
\a      Write a <bell> character.
\b      Write a <backspace> character.
\f      Write a <form-feed> character.
\n      Write a <new-line> character.
\r      Write a <carriage return> character.
\t      Write a <tab> character.
\v      Write a <vertical tab> character.
\\      Write a backslash character.
\num    Write an 8-bit character whose ASCII value is the 1-, 2-, or 3-digit octal number num.
```

Ou seja, ele só aceita octal mesmo... :(

Quando você executa a função no prompt, está usando o teu shell padrão, bash. Já o clitest usa o `/bin/sh`, que no Debian aponta pra `/bin/dash`, por isso a diferença.

* A solução fácil é forçar o clitest a testar as ZZ sempre com o bash, que afinal, é nosso shell padrão.

* A solução portável é usar octal na `zzascii`, torcer pra funcionar, e torcer pra não ter problema de portabilidade entre os printf com octal :)

Vou tentar a solução portável antes, que é mais bacana.

**Comment by aureliojargas** [comment]
Feito no commit a623602. Agora usa octal em vez de hexa. @itamarnet pode testar pra ver se ficou ok?

**Comment by itamarnet** [comment]
Agora ficou beleza @aureliojargas .
Sem problemas agora :+1:
