### ISSUE TITLE
zzpad: repensar opções de linha de comando

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#181]
Hoje a zzpad é assim:

```
Uso: zzpad [-l | -e | -r | -d | -b | -a] <número> [string] texto
```

Ou seja, você informa:
* onde quer que o padding aconteça: direita, esquerda, ambos (default=direita) **[opcional]**
* qual o tamanho total da string resultante
* qual a string de preenchimento (default=espaço) **[opcional]**
* o texto orignal a ser preenchido **[opcional se via STDIN]**

O problema são os argumentos opcionais. Nem todas as combinações funcionam.

```
bash
# Preencha o texto "foo" com espaços à direita, no tamanho 10
zzpad 10 foo              # não funciona
zzpad -r 10 foo           # não funciona
zzpad 10 ' ' foo          # funciona
zzpad -r 10 ' ' foo       # funciona
echo foo | zzpad 10       # funciona
echo foo | zzpad -r 10    # funciona
```

Quando a função recebe os argumentos `10 foo`, não tem como ela saber se "foo" é o texto a ser processado ou se é o texto de preenchimento (quando o texto original vem pela STDIN), pois os parâmetros posicionais não deixam isso claro.

É melhor evitar parâmetros posicionais. Por causa desse tipo de problema e pela confusão do usuário. Devo colocar o número antes ou é a string de preenchimento? A solução é transformar o parâmetro posicional em uma opção normal (`-letra argumento`).

Sugiro adicionar uma nova opção `-x` para especificar a string de preenchimento, cujo valor padrão caso não informada, seja o espaço em branco. Por que X? Porque não achei outra letra mais intuitiva e porque já usamos XXXXX num texto normal no sentido de preencher lacunas.

```
Uso: zzpad [-l | -e | -r | -d | -b | -a | -x TEXTO] <número> [texto]
```

Assim, posso fazer:

```
zzpad 10 foo
zzpad -r 10 foo
zzpad -r -x ' ' 10 foo
zzpad -x ' ' -r 10 foo
echo foo | zzpad 10
echo foo | zzpad -r 10
echo foo | zzpad -r -x ' ' 10
echo foo | zzpad -x ' ' -r 10 foo
```

E todos irão funcionar da mesma forma. Que tal?

**Comment by itamarnet** [comment]
Apoiado.
Realmente não tinha percebido essa "brecha", mas faz todo o sentido evitando esse "dilema".
:+1:

**Comment by aureliojargas** [comment]
A opção `-x` foi adicionada no commit 0cbc8f6cc508684dadcad22836c99d7e8d1b5fb5

@itamarnet Nas próximas lembre de mencionar o número do issue (com a # na frente) na mensagem de commit, pra que o commit apareça aqui automaticamente.
