### ISSUE TITLE
Arrumar funções com saída desalinhada quando tem acentuação

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#182]
Conforme analisado no issue #180, usar o `printf` para formatar a saída em colunas é problemático com caracteres acentuados (UTF-8).

Chegamos a uma solução portável com a `zzpad`. Então agora temos que atualizar as funções que hoje usam `printf` (ou `awk`) para saída em colunas, para que passem a usar a `zzpad`. Exemplo:

```bash
printf "%10s %-20s\n" $nome $descricao                  # antes
echo "$(zzpad -l 10 $nome) $(zzpad -r 20 $descricao)"   # depois
```
 
Algumas funções que estão com este problema:

* zzfutebol
* zzpais
* zzquimica

Lembre de referenciar este issue na mensagem de commit da correção.

**Comment by itamarnet** [comment]
@aureliojargas fiz um teste de conceito com zzfutebol.
Aqui funcionou perfeitamente, apenas um pouco mais lento, mas obtive os mesmo resultados.
Não vou propagar em outras funções por enquanto, mas tendo um retorno positivo podemos considerar a estratégia para implementar nas demais.
Confere em 27376efbec9f5581aee2bf79387d550d7e112997

**Comment by itamarnet** [comment]
@aureliojargas Fiz a mesma modificação nas funçoes zzquimica e zzestado.
Há de novo o fato de ficar um pouco mais lerdo, mas funcionou bem.
Referência commit e15ff676da3336211120fb71b4a2705ffcbf6c39

**Comment by aureliojargas** [comment]
:+1: 

Estou rodando todos os testes aqui pra ver se aparece mais alguma função desalinhada.

**Comment by itamarnet** [comment]
Eu suponho que a zzlibertadores e a zzbrasileirao terão o mesmo problema.
Na minha máquia está "ok", mas como usa ainda "printf" a possibilidade de ser candidata a ter o problema é grande.
São duas que acredito que precisem ser readequadas, mas ainda não fiz ajustes pois a demora com o uso do zzpad requer uma atenção especial.
Mas acho que há mais além dessas.

**Comment by aureliojargas** [comment]
Pois é, essas 3 são difíceis de testar a saída, pois varia muito.

Executando agora na mão, confirmo que estão desalinhadas:

```console
$ zztv
Agora
 00h00 Encerramento da Programação                             NBR
 03h00 CNN Newsroom                                              CNN International
 04h30 Bom Dia Portugal                                          RTP Internacional
 05h00 Band News - Notícias                                     Band News
 05h00 Product Showcase                                          The Golf Channel 
 05h25 Os Miseráveis                                            Max HD 
 05h30 Sul-americano Sub-17: Uruguai x Brasil                    SporTV 
 05h35 Ladrão de Casaca                                         Telecine Cult 
 05h35 Meu Querido Presidente                                    Telecine Touch 
 05h45 Oz: Mágico e Poderoso                                    PPV 12 DLA
 05h45 Oz: Mágico e Poderoso                                    PPV 7 DLA
 05h45 O Lobo de Wall Street                                     PPV 3 DLA
 05h45 Oz: Mágico e Poderoso                                    PPV 9 DLA
 05h45 Oz: Mágico e Poderoso                                    PPV 10 DLA
 05h45 Oz: Mágico e Poderoso                                    PPV 11 DLA
 05h45 Oz: Mágico e Poderoso                                    PPV 8 DLA
 05h55 Cônicos e Cômicos                                       Telecine Fun 
 06h00 Jornal da Manhã                                          Globo - Rede Bahia 
 06h00 Invasão à Casa Branca                                   HBO Signature 
...

$ zzlibertadores 2
Grupo 1
                      Atlas 0 X 1 Ind. Santa Fe               Qua 18/02, 00h45
                  Colo-Colo 2 X 0 Atlético-MG                Qua 18/02, 22h00
               Atlético-MG 0 X 1 Atlas                       Qua 25/02, 19h45
              Ind. Santa Fe 3 X 1 Colo-Colo                   Qui 26/02, 22h30
                  Colo-Colo 2 X 0 Atlas                       Qua 04/03, 19h45
              Ind. Santa Fe 0 X 1 Atlético-MG                Qua 18/03, 22h00
                        Atlas X Colo-Colo                     Ter 07/04, 22h15
                        Atlas X Atlético-MG                  Qua 15/04, 22h00
                    Colo-Colo X Ind. Santa Fe                 Qua 15/04, 22h00
                Ind. Santa Fe X Atlas                         Qua 22/04, 19h45
```

Quem manda não usar sed :P

**Comment by itamarnet** [comment]
Opa, esteja a vontade se quiser mudar tudo pra ``` sed ```.
Mas já estou vendo já as mudanças com o uso do ``` zzpad ```, mas a demora é incômoda quando pega uma lista um pouco mais longa.
Mas qualquer alternativa que possa oferecer nesse momento é bem vinda, mesmo que precise mudar tudo.

**Comment by aureliojargas** [comment]
Pra esses casos de funções com saída mais complexa, talvez devêssemos mudar de postura e programar de um jeito mais "conservador". Em vez de querer fazer tudo de uma vez com sed/awk como normalmente fazendo (e fica muito rápido!), talvez seja melhor ir lendo linha a linha, guardando em variáveis, e mostrando o resultado no final. Fica mais lento, mas de repente fica mais fácil de manter. É uma ideia...

**Comment by aureliojargas** [comment]
Ah, esse issue não está no milestone do próximo release, então é melhor esperar pra mexer depois do lançamento e assim evitarmos trazer bugs novos.

**Comment by itamarnet** [comment]
Acho com o commit 30a90b7cf033c262d56dc4a9a1c4ae65d8d93be4 aplicado a ``` zztv ``` fechamos a questão do alinhamento.
Há algum ainda que ache que esteja pendente? Ou podemos considerar feito?

**Comment by aureliojargas** [comment]
Resolvido sim, os testes que estão quebrados agora aqui pra mim não têm a ver com alinhamento.
