### ISSUE TITLE
zzalinhar: Erro no awk: qtde = split(linha[i], campos, " >>>  ", <<<  espacos)

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#184]
```console
$ echo foo | zzalinhar -j
awk: syntax error at source line 39
 context is
							qtde = split(linha[i], campos, " >>>  ", <<<  espacos)
awk: illegal statement at source line 40
awk: illegal statement at source line 40
$
```

Acredito que o problema foi introduzido no commit 3365cd358af7e6ca711759c84a2fe6cb94984987

**Comment by itamarnet** [comment]
Verificar se essa solução atende.
O modo anterior é uma "feature" que se aplica ao gawk, e nem todos os sabores de awk suportam.
Referência commit c0cc4ad573fd2a0daddc037eeee6c4bb013c68c4

**Comment by aureliojargas** [comment]
Resolveu, show!
:+1:
