### ISSUE TITLE
zzquimica: teste falhando.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#186]
O último teste de zzquimica falhou.
Mas não creio que seja a função, apenas a chamada do teste.

Trocando  ``` cut -c 1-26 ``` por ``` sed 's/^\(.\{26\}\).*/\1/' ``` na linha do comando funcionou.

Confere no seu caso?

**Comment by aureliojargas** [comment]
Por falar nisso, você pode colocar um comentário no issue #180 repetindo os testes que fiz lá com cut, awk, wc, sed, echo pra deixar registrado a diferença de comportamento entre sistemas? Depois aquele issue pode virar uma wiki, pra que esse conhecimento não se perca.

**Comment by itamarnet** [comment]
Ok @aureliojargas, farei hoje a noite, assim posso colocar exemplos de fato.
Onde estou agora o problema não se repete, então pode ter relação também com a versão do cut ou do shell.

**Comment by aureliojargas** [comment]
:+1:
