### ISSUE TITLE
zzfeed: erro no awk (às vezes...)

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#191]
Preparado para um bug bizarro? Lá vai:

```
$ zznoticiaslinux u

* UnderLinux (https://under-linux.org/external.php?do=rss&type=newcontent):
Fraudes Bancárias: São Paulo Lidera em Número de Vítimas Dessas Práticas
"Cyber Crooks" Exploram Redes de Anúncios para Práticas de Ransomware
Disponível Oracle Linux 7.1

$ zznoticiaslinux u

* UnderLinux (https://under-linux.org/external.php?do=rss&type=newcontent):
awk: syntax error at source line 3 source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag
 context is
	 >>> BEGawk: IN <<< syntax error  at source line 3{  source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tagta
g[t context is
	i >>> tlBeE]G=I0N  <<< } 
{ awk: tillegal statementag at source line 4[ source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tagt
itle]=0 }
awk: illegal statement at source line 4 source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag
awk: syntax error at source line 12 source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag
awk: syntax error at source line 12 source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag

$ zznoticiaslinux u

* UnderLinux (https://under-linux.org/external.php?do=rss&type=newcontent):
Fraudes Bancárias: São Paulo Lidera em Número de Vítimas Dessas Práticas
"Cyber Crooks" Exploram Redes de Anúncios para Práticas de Ransomware
Disponível Oracle Linux 7.1
```

Fazendo execuções repetidas da mesma linha de comando, ora funciona, ora não.

@itamarnet  Isso acontece na tua máquina também ou é a minha que está encapetada? :)

**Comment by itamarnet** [comment]
Caracas!! Sua máquina deve estar possuída.
Testei aqui até mesmo dentro de um loop e não aconteceu isso.
Sinceramente nem sei o que dizer.
Hoje estive bem enrolado em outros projetos, mas vou montar uma máquina virtual com FreeBSD e repetir esse testes.
Mas no momento nem sei o que especular.

**Comment by aureliojargas** [comment]
O problema na verdade aparece na `zzfeed`, que é usada pela `zznoticiaslinux`. Mesma coisa, de várias execuções seguidas, uma ou outra dá erro, aleatoriamente:

```
$ zzfeed http://feeds.feedburner.com/linuxjournalcom
awk: syntax error at source line 12 source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag
 context is
	 >>>  END <<<  { for (lin=1;lin<=NR;lin++) { if (lin in linha) print linha[lin] } }
awk: illegal statement at source line 13 source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag
awk: syntax error at source line 12 source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag
 context is
	 >>>  END <<<  { for (lin=1;lin<=NR;lin++) { if (lin in linha) print linha[lin] } }
awk: illegal statement at source line 13 source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag
$
```

Note que a mensagem de erro é relativa aos arquivos temporários da `zzxml`. Eu ainda não parei para estudar todas as mudanças que você fez nela, mas eu desconfio que o problema está ali.

**Comment by itamarnet** [comment]
Quando rodar da próxima vez me envie o conteúdo desse desse arquivo temporário.
Assim posso tentar reproduzir o erro ou identificar o que acontece.
Ainda não consegui reproduzir esse erro em especial, então estou sem um horizonte

**Comment by aureliojargas** [comment]
Identifiquei a fonte do problema: `zzxml` e seus arquivos temporários.

Peguei um arquivo XML qualquer de exemplo:

``` console
# desliguei o `rm` no final da zzfeed e guardei o arquivo de cache baixado

$ zzfeed http://feeds.feedburner.com/linuxjournalcom > /dev/null
$ cp $ZZTMP.feed* foo.xml
```

Desliguei também o `rm` no final da `zzxml` para que os arquivos temporários não sejam apagados. Executei na mão o trecho de código que a `zzfeed` usa para parsear o XML:

```bash
zzxml --tag item foo.xml | zzxml --tag title | zzxml --tidy --untag
```

Quando a execução vai bem, são criados dois arquivos temporários, quando dá pau, é criado apenas um:

```console
$ l $ZZTMP.xml*
-rw-r--r--  1 aurelio  staff    587 May 16 10:51 /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag
-rw-r--r--  1 aurelio  staff    290 May 16 10:53 /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.1_tag
-rw-r--r--  1 aurelio  staff    297 May 16 10:53 /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.2_tag
```

No caso, o `zz.xml.0_tag` é o que deu pau, veja seu conteúdo:

```console
$ cat /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag
BEGIN { tag[title]=0 }
{

			if ($0 ~ /^<title[^><]*\/>$/) { linha[NR] = $0 }
			if ($0 ~ /^<title[^><]*[^\/><]+>/) { tag[title]++ }
			if (tag[title]>=1) { linha[NR] = $0 }
			if ($0 ~ /^<\/title >/) { tag[title]-- }
		
}
BEGIN { tag[item]=0 }
{
 END { for (lin=1;lin<=NR;lin++) { if (lin in linha) print linha[lin] } }

			if ($0 ~ /^<item[^><]*\/>$/) { linha[NR] = $0 }
			if ($0 ~ /^<item[^><]*[^\/><]+>/) { tag[item]++ }
			if (tag[item]>=1) { linha[NR] = $0 }
			if ($0 ~ /^<\/item >/) { tag[item]-- }
		
}
 END { for (lin=1;lin<=NR;lin++) { if (lin in linha) print linha[lin] } }
$
```

Pelo que estou vendo, ele concatenou dois scripts awk no mesmo arquivo. Este foi o erro dessa execução:

```console
$ zzxml --tag item foo.xml | zzxml --tag title | zzxml --tidy --untag
awk: syntax error at source line 12 source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag
 context is
	 >>>  END <<<  { for (lin=1;lin<=NR;lin++) { if (lin in linha) print linha[lin] } }
awk: illegal statement at source line 13 source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag
awk: syntax error at source line 12 source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag
 context is
	 >>>  END <<<  { for (lin=1;lin<=NR;lin++) { if (lin in linha) print linha[lin] } }
awk: illegal statement at source line 13 source file /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.0_tag
```

Já na execução normal, que não deu erro, foram gerados os dois arquivos temporários normalmente:

```console
$ cat /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.1_tag
BEGIN { tag[item]=0 }
{

			if ($0 ~ /^<item[^><]*\/>$/) { linha[NR] = $0 }
			if ($0 ~ /^<item[^><]*[^\/><]+>/) { tag[item]++ }
			if (tag[item]>=1) { linha[NR] = $0 }
			if ($0 ~ /^<\/item >/) { tag[item]-- }
		
}
 END { for (lin=1;lin<=NR;lin++) { if (lin in linha) print linha[lin] } }

$ cat /var/folders/ns/p897hcp56wjgjt61yr7tbd980000gn/T/zz.xml.2_tag
BEGIN { tag[title]=0 }
{

			if ($0 ~ /^<title[^><]*\/>$/) { linha[NR] = $0 }
			if ($0 ~ /^<title[^><]*[^\/><]+>/) { tag[title]++ }
			if (tag[title]>=1) { linha[NR] = $0 }
			if ($0 ~ /^<\/title >/) { tag[title]-- }
		
}
 END { for (lin=1;lin<=NR;lin++) { if (lin in linha) print linha[lin] } }
```

Como o erro às vezes dá, e às vezes não, parece ser problema de concorrência de processos. Acho que aquele algoritmo no início, que vai incrementando o número em `$i` está, às vezes, falhando. Ou talvez até pode ser algo relacionado com a `zztool cache` retornando o nome errado do arquivo, também por problemas de concorrência.

**Comment by itamarnet** [comment]
Aurelio,

O que pude entender com o retorno do seu cache do ``` zzxml ```, é que o bloco  " END " está sendo escrito dentro de um bloco que destina-se as linhas ou registros.
Os blocos " BEGIN " e " END " são especiais e destinam-se a pré e pós processamento dos registros respectivamente.
Podem existir vários blocos " BEGIN " ou " END ", que eles serão unidos internamente em um bloco.
Todavia a ocorrência deles dentro de um outro bloco gera um erro.

O que fiz foi colocar essa geração do script em awk num bloco ``` if then fi```, pois suponho que esteja havendo uma sobreposição de laços distintos.

Como disse anteriormente, não consigo reproduzir o erro aqui, então quando puder me de um retorno sobre o resultado com essa alteração.

E se for o caso, novamente, me enviar a saída do cache do ``` zzxml ```.

No aguardo.

Ver commit 1d1e550cf8be09761dbfca809309ad0d93763f43

**Comment by aureliojargas** [comment]
@itamarnet a sua atualização infelizmente não resolveu o problema.

Mexi por aqui e consegui resolver, era realmente na rotina de criação do temporário. Na verdade a `zzxml` estava "forçando a barra", usando uma ferramenta de **cache** para criar um arquivo **temporário** :)

Então criei uma ferramenta específica para arquivos temporários, a `zztool mktemp`. Ela usa o comando `mktemp` e garante o nome único do arquivo criado. Temos que ver se há outras funções nessa mesma situação. Abri o #210 pra isso.
