### ISSUE TITLE
zznoticiaslinux y: quebrada

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#192]
Pelo menos aqui na minha máquina, não retorna resultados:

```
$ zznoticiaslinux y

* Yahoo Linux (http://br.noticias.yahoo.com/rss/linux):
$
```

**Comment by itamarnet** [comment]
Nem aqui na minha máquina, mas acho que o feed não existe mais.
No browser aparece o "rss", mas com última informação de 30/jun/2014.
Talvez seja o caso de não mais considerar o Yahoo.

**Comment by aureliojargas** [comment]
Apoiado. Vou desativar o Yahoo.
