### ISSUE TITLE
zzxml: saída em formato diferente

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#196]
@itamarnet Você fez bastante mudanças na `zzxml`, que eu acabei não acompanhando.

O que percebi agora, é que o formato de saída mudou. Antes, cada linha do resultado era uma tag completa, agora cada tag vem sozinha na linha, com seu conteúdo na próxima linha:

```
$ $ZZWWWHTML http://www.linuxsecurity.com/linuxsecurity_advisories.rdf | ../funcoeszz.github.io/download/funcoeszz-13.2.sh zzxml --tag title
<title>LinuxSecurity.com - Security Advisories</title>
<title>Red Hat: 2015:0707-01: qpid: Moderate Advisory</title>
<title>Red Hat: 2015:0708-01: qpid: Moderate Advisory</title>
<title>Ubuntu: 2537-1: OpenSSL vulnerabilities</title>
<title>Debian: 3197-1: openssl: Summary</title>
<title>Red Hat: 2015:0700-01: unzip: Moderate Advisory</title>
<title>Red Hat: 2015:0699-01: postgresql92-postgresql: Moderate Advisory</title>
<title>Debian: 3196-1: file: Summary</title>
<title>Ubuntu: 2536-1: libXfont vulnerabilities</title>
<title>Ubuntu: 2535-1: PHP vulnerabilities</title>
<title>Debian: 3195-1: php5: Summary</title>
<title>Red Hat: 2015:0696-01: freetype: Important Advisory</title>
<title>Red Hat: 2015:0697-01: flash-plugin: Critical Advisory</title>

$ $ZZWWWHTML http://www.linuxsecurity.com/linuxsecurity_advisories.rdf | zzxml --tag title
<title>
LinuxSecurity.com - Security Advisories
</title>
<title>
Red Hat: 2015:0707-01: qpid: Moderate Advisory
</title>
<title>
Red Hat: 2015:0708-01: qpid: Moderate Advisory
</title>
<title>
Ubuntu: 2537-1: OpenSSL vulnerabilities
</title>
<title>
Debian: 3197-1: openssl: Summary
</title>
<title>
Red Hat: 2015:0700-01: unzip: Moderate Advisory
</title>
<title>
Red Hat: 2015:0699-01: postgresql92-postgresql: Moderate Advisory
</title>
<title>
Debian: 3196-1: file: Summary
</title>
<title>
Ubuntu: 2536-1: libXfont vulnerabilities
</title>
<title>
Ubuntu: 2535-1: PHP vulnerabilities
</title>
<title>
Debian: 3195-1: php5: Summary
</title>
<title>
Red Hat: 2015:0696-01: freetype: Important Advisory
</title>
<title>
Red Hat: 2015:0697-01: flash-plugin: Critical Advisory
</title>
```

Essa mudança de formato quebrou as funções que já usavam a `zzxml` e esperavam os resultados no formato anterior. Qual foi o motivo dessa mudança de formato?

**Comment by itamarnet** [comment]
@aureliojargas Desculpe a demora em responder, mas essa mudança é um efeito colateral quando foi colocada a possibilidade de selecionar múltiplas tags pela ``` zzxml ```.

Nesse caso é como se a opção ``` --tidy ``` fosse um pré-requisito para o uso da opção ``` --tag ```.
Revendo meus alfarrábios, acabei optando por isso por causa da permissividade que a estrutura de arquivos ``` XML ``` oferecem.

O aninhamentos de tags idênticas também tornaram-se um empecilho, cujo fechamento de uma tag interna comprometia a seleção desejada, e as opções que tentei na época não me davam muita margem, e ter mais de uma tag por linha tornava ainda mais incerto esse ajuste.
Já havia comentado algo sobre no issue #125.

Relendo o código não vi a priori, mesmo hoje, uma alternativa viável sem usar esse artifício e que seja funcional ao oferecer tags múltiplas. :/

**Comment by aureliojargas** [comment]
Ah, agora que vi o #125 entendi o porquê do uso dos arquivos temporários na `zzxml`. Caramba, você teve que praticamente criar um mini-parser XML em awk!

Parabéns pelos códigos novos na `zzxml`, deixaram ela bem poderosa, agora tem inclusive `--indent`. Neste caso, a quebra de compatibilidade com o formato de saída é justificada, vou fechar este issue.

Vou aproveitar e dar uma incrementada nos testes dela, para cobrir todas as funcionalidades novas.
