### ISSUE TITLE
zzcriptomoeda: Mudar da nome para zzcoin

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#198]
Via twitter já tive um retorno do autor original "Tárcio Zemel", que não se opõe a mudança de nome.
A grande maioria das moedas listadas, assim como as principais tem "coin" no nome.
Apesar do nome atual ser mais abrangente, me parece mais verborrágico, e um nome como "zzcoin" parece mais direto, mais intuitivo.
Deixo a questão da mudança para "zzcoin" como uma sugestão a ser apreciada.

**Comment by aureliojargas** [comment]
Concordo! Função renomeada nos commits já mencionados.
