### ISSUE TITLE
zzbrasileirao: sem $ZZCOR, não deve mostrar caracteres especiais

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#199]
Na `zzbrasileirao` há trechos como:

```awk
if (cor_awk==1) {
	if ($1 ~ /9°/ || $1 ~ /10°/) { cor="\033[41;30m" }
	else if ($1 ~ /[1-4]°/) { cor="\033[42;30m" }
	else { cor="\033[m" }
}

```

A ideia deste código é respeitar a `$ZZCOR` e não mostrar a saída colorida quando ela estiver desligada. Visualmente funciona, porém, a função continua emitindo os caracteres de controle `\033[m` no resultado.

Isso não é o desejado. Se `$ZZCOR` estiver desligada, é porque o usuário (ou o script) que está executando a função precisa do resultado puro, somente texto, sem caracteres de controle.

Vide `zzecho` para um exemplo.

**Comment by itamarnet** [comment]
Esse trecho está "OK", pois só vai abrir com caracteres de controle se estiver habilitada a saída colorida.

Mas a preocupação procede nesses pontos, onde o fechamento e abertura independe disso, e sempre vai ter:
```
/Grupo (A|B)/,/10°/ { if (serie_awk=="c") {
				cor="\033[m"
```
```
/Grupo A/,/Rodada 1/ { if (serie_awk=="d") {
				cor="\033[m"
```
```
printf "%s%-23s %3s %3s %3s %3s %3s %3s %3s %3s %4s \033[m\n", cor, time, $(NF-8), $(NF-7), $(NF-6), $(NF-5), $(NF-4), $(NF-3), $(NF-2), $(NF-1), $NF}'
```
Isso é fácil corrigir.
E se já houver tabela a consultar no site, vejo se precisa de retrabalho o restante do código

**Comment by aureliojargas** [comment]
Ok. Esse issue não está no milestone do próximo release, então se puder esperar antes de mexer, será melhor pra evitarmos trazer bugs novos.

**Comment by itamarnet** [comment]
Esse issue foi resolvido no commit a1531d631c07dd5a172ae8bf04f6e72ce212460e

**Comment by aureliojargas** [comment]
Ué, mas esse commit é de 24/fev! Então eu abri este issue um mês depois que o problema já estava corrigido? Caramba...

**Comment by itamarnet** [comment]
Que estranho! Eu não lembro disso assim nessa ordem.

O issue foi aberto antes, eu tenho certeza disso. Tanto que você citava o zzbrasileirao e a zzlibertadores apenas foi no embalo do contexto.

Confesso que fiquei confuso no caso das datas.

**Comment by aureliojargas** [comment]
Pegadinha do GitHub? :)
