### ISSUE TITLE
zzurlencode, zzurldecode: comportamento incorreto para UTF-8

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#201]
* Para caracteres ASCII (`<128`), está tudo certo, o mapeamento é `a` — `%61`.
* Para caracteres UTF-8 (`>=128`), está errado.

Atualmente, `á` vira `%E1`, que é uma conversão direta do valor decimal (`225`) para hexadecimal (`E1`).

Porém, como já discutido no issue #180 e aplicado na zzascii no commit ec5e5a5, caracteres UTF-8 são multibyte e isso deve ser levado em conta na conversão.

```javascript
// JavaScript
encodeURI('á');                // %C3%A1
encodeURI('♥');                // %E2%99%A5
```

```python
# Python 3
urllib.parse.quote('á')         # %C3%A1
urllib.parse.quote('♥')         # %E2%99%A5
```

```php
// PHP
echo urlencode('á');           // %C3%A1
echo urlencode('♥');           // %E2%99%A5
```

**Comment by aureliojargas** [comment]
@itamarnet a `zzurldecode` também usa `printf` com hexadecimais `\xHH`, então terá o mesmo problema de não passar no testador no Ubuntu. Abri o issue #207 para lidar com isso.

**Comment by itamarnet** [comment]
Nem vou usar o testador, vou apenas confirmar direto na linha de comando, e nesse caso tenho certeza que funciona.
Interessante que tenho o bom e velho Slackware e nele nunca deu problema.

**Comment by aureliojargas** [comment]
Qualquer sistema que tiver `/bin/sh` apontando pro bash vai funcionar normal. O problema foi o Ubuntu e amigos terem escolhido apontar pro dash :/
