### ISSUE TITLE
zzurlencode, zzurldecode: espaço deve virar + ou %20?

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#202]
```javascript
// JavaScript
encodeURI('a b');              // a%20b
```

```php
// PHP
echo urlencode('a b');         // a+b
```

```python
# Python 3
urllib.parse.quote('a b')       # a%20b
urllib.parse.quote_plus('a b')  # a+b
```

A diferença acontece porque há regras diferentes para escapar um texto para ser usado numa URL ou na parte query string (após a `?`) da URL.

Provavelmente precisaremos de uma opção de linha de comando para contemplar ambos. Há outras diferenças também, como não escapar a `/` se for pra uma URL, mas escapar se for query string.

A documentação do Python esclarece alguns pontos: https://docs.python.org/3.3/library/urllib.parse.html#url-quoting

**Comment by itamarnet** [comment]
A solução passa necessariamente pela separação da URL em 2 partes, onde ``` ? ``` é o delimitador.
 - Antes ou na ausência dele usar ``` %20 ``` para espaços e não codificar ``` / ```
 - Após usar ``` + ``` para espaços e codificar ``` / ```

**Comment by itamarnet** [comment]
Uma sugestão em código que pode dar uma das soluções para esse caso:
```
sed 's/%3F/?/' | awk -F'?' '{OFS="?";reserva=$1;$1=="";gsub("%20","+");gsub("%2F","/",reserva);$1=reserva;print}'
```

Note que nesse caso a primeira ocorrência de ``` ? ``` não é codificada e nem as ``` / ``` antes, e os espaços se mantém como ``` %20 ```, mas as demais ocorrências tanto ``` ? ``` e ``` / ``` são codificados e os espaços são convertidos para ``` + ```.

Como sempre uso o awk para solucionar a questão e acredito que funcione em qualquer plataforma esse código, mas sempre é bom testar.

**Comment by aureliojargas** [comment]
Testei aqui e o `%20` funciona normalmente no lugar do `+`. Então, para que nossa função fique mais simples, acho melhor ignorar esta exceção e sempre gerar `%20`. Vai funcionar do mesmo jeito.

**Comment by itamarnet** [comment]
Beleza! Um problema a menos então.
Mas e os demais caracteres?
O comportamento de ``` / ```, ``` : ``` e ``` ? ``` após e antes da primeira ocorrência do ``` ? ``` ?
Ou nem consideraremos essa diferença de comportamento, sendo válido para url por completo?

**Comment by aureliojargas** [comment]
Vejamos o que as outras ferramentas fazem:

```bash
zzurlencode :/?:/                 # %3A%2F%3F%3A%2F
```

```php
// PHP
echo urlencode(':/?:/');          // %3A%2F%3F%3A%2F
```

```javascript
// JavaScript
encodeURI(':/?:/');               // :/?:/
```

```ruby
URI.escape(':/?:/')               # :/?:/
```

```python
# Python
urllib.parse.quote(':/?:/')       # %3A/%3F%3A/
urllib.parse.quote_plus(':/?:/')  # %3A%2F%3F%3A%2F
```

Tá difícil de achar um padrão :/

O que dá pra perceber é que nenhuma se comporta diferente antes ou depois da `?`.

Sugiro que deixemos como está: converte tudo e pronto. Este é o mesmo comportamento do PHP. Vai funcionar do mesmo jeito quando colocar numa URL.

**Comment by aureliojargas** [comment]
Na `zzurldecode`, temos o mesmo dilema:

```php
// PHP
echo urldecode('%61+%62');       // a b
```

```python
# Python
urllib.parse.unquote('%61+%62')  # a+b
```

```ruby
# Ruby
URI.unescape('%61+%62')          # a+b
```

```javascript
// JavaScript
decodeURI('%61+%62')             // a+b
```

Aqui pelo menos é só o PHP que faz diferente, todos os demais decodificam somente os hexadecimais. Eu concordo que este deve ser o comportamento padrão, e alinha com a `zzurlencode` de não usar `+` como espaço.

**Comment by aureliojargas** [comment]
Bem, com estas investigações, descobrimos que não há padrão :(

Na falta dele, é melhor fazermos a solução mais simples: sem firulas, sem espertezas, sem exceções.

Ou seja, codifica e decodifica tudo. Este é o comportamento atual da `zzurlencode` e da `zzurldecode`, então fecharei este issue.

**Comment by itamarnet** [comment]
Também concordo! 
Acho importante ter esse alinhamento entre a ``` zzurlencode ``` e a ``` zzurldecode ```, ao menos mantemos uma coerência interna.
E a falta de uma padrão é um fato, e nesse caso não há muito o que fazer. :(
