### ISSUE TITLE
Comando test: trocar a ordem dos argumentos

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#203]
O comando `test` é mais seguro se trocada a ordem dos argumentos, sempre informando por primeiro o trecho **conhecido** de um teste, conforme explicado em https://github.com/funcoeszz/funcoeszz/wiki/Coding-Style#comando-test.

Um exemplo de correção deste tipo foi feita no commit 78e95f8e42505af0e121a1f368fd29a0a478d8da.

Essa é uma alteração grande, a ser feita com cautela e somente depois do release 2015.

**Comment by itamarnet** [comment]
Mudança feita na PR #532
