### ISSUE TITLE
Adicionar suporte ao -- em todas as funções

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#204]
É comum no mundo Unix, suportar o `--` para informar que não há mais opções de linha de comando daquele ponto em diante. Por exemplo, para procurar pela string `-i` em um arquivo:

```bash
grep -- -i arquivo.txt
```

Assim, o `-i ` não será confundido com uma opção do grep.

A `zzmoneylog` é a única função que atualmente suporta o `--`:

```bash
# Opções de linha de comando
while test "${1#-}" != "$1"
do
	case "$1" in
		-t | --tag    ) shift; tag="$1";;
		-d | --data   ) shift; data="$1";;
		-v | --valor  ) shift; valor="$1";;
		-a | --arquivo) shift; arquivo="$1";;
		--total) total=1;;
		--) shift; break;;
		-*) zztool erro "Opção inválida $1"; return 1;;
		*) break;;
	esac
	shift
done
```

A alteração é realmente simples, basta inserir uma linha linha dentro do `case` que cuida das opções de linha de comando e pronto.

```
--) shift; break;;
```

Porém, esta alteração deve ser feita de maneira gradual, e obrigatoriamente novos testes devem adicionados para assegurar-se que o `--` funciona como deveria.

Esta alteração deve ser feita após o release 2015.

**Comment by itamarnet** [comment]
Todos ajustes possíveis e nas funções aplicáveis são listados no PR #293
