### ISSUE TITLE
zztwitter: Parou de funcionar.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#205]
A função parou de funcionar.
Não mais há o envio da mensagem.

Talvez seja o caso de aposentar essa função, pois ela foge do senso comum das FuncoesZZ, pois necessita interagir com o usuário, pedindo o nome de usuário e senha.

Isso é algo que poderia ser contornado, mas a segurança nesse tipo de construção é frágil.
Recomendo que a deixemos de usar devido a essas características.

**Comment by aureliojargas** [comment]
:+1:  Concordo. Vou aposentá-la.
