### ISSUE TITLE
zzloteria: remover dependência do links

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#206]
Esta é a única função que depende de um navegador diferente do padrão `lynx`.

```

$ zzloteria
Para esta função funcionar, é necessário instalar o navegador de modo texto "links", "links2" ou "elinks".
$
```

Eliminar esta dependência exclusiva. Mesmo que com o `lynx` não seja possível, utilizar comandos mais comuns como `wget` ou `curl` já seria melhor.

No issue #159 há uma investigação de alternativas, mas que infelizmente não trouxe resultados :(

**Comment by itamarnet** [comment]
Tentei buscar alternativas a essa dependência e infelizmente decorrido tanto tempo o problema persiste.
O comentário https://github.com/funcoeszz/funcoeszz/issues/159#issuecomment-72391504  feito por @kemelzaidan foi que deu a melhor alternativa e ainda hoje parece a mais viável.

**Comment by itamarnet** [comment]
Com a nova abordagem que o commit b0d447ce413f0ab8669ba878bfd02c3898e239be mostra, esse issue não faz mais sentido.
Fechando!

**Comment by aureliojargas** [comment]
:+1:
