### ISSUE TITLE
Shell dash não suporta \x no printf

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#207]
O printf do dash não tem suporte ao `\x` para mostrar um caractere em hexadecimal. Trecho da man page:

```
\a      Write a <bell> character.
\b      Write a <backspace> character.
\f      Write a <form-feed> character.
\n      Write a <new-line> character.
\r      Write a <carriage return> character.
\t      Write a <tab> character.
\v      Write a <vertical tab> character.
\\      Write a backslash character.
\num    Write an 8-bit character whose ASCII value is the 1-, 2-, or 3-digit octal number num.
```

Ou seja, ele só aceita octal mesmo... :(

Isso causa bugs em funções que usam o `\x` no printf, como `zzurlencode` e `zzurldecode`. Elas funcionam normalmente no console, mas dão erro ao rodar o testador, em determinadas versões do Linux.

Quando você executa a função no prompt, está usando o teu shell padrão, bash. Aí tudo funciona, pois o printf do bash suporta o `\x`. Já ao rodar o testador (clitest), ele tem o shebang `/bin/sh`, que no Debian aponta pra `/bin/dash`, e aí é usado o printf capado, por isso a diferença.

* A solução fácil é forçar o clitest a testar as ZZ sempre com o bash, que afinal, é nosso shell padrão e o único suportado oficialmente pelas funções.

* A solução portável é usar octal em vez de hexadecimal no printf, o que nem sempre é fácil ou desejável. Na `zzascii` foi usada esta solução (vide commit a623602b06065705aefeb0347a03b05a4a75f677 e discussão em #179), pois já lidamos com octal nela. Já em `zzurl(en|de)code`, lidamos com hexadecimais o tempo todo, não faz sentido converter pra octal só por causa dessa limitação.

No futuro serial legal se as ZZ suportassem oficialmente outros shells, como o dash. Porém, atualmente, talvez seja melhor testar tudo no bash mesmo e não nos preocuparmos com estas diferenças.

**Comment by itamarnet** [comment]
É uma questão antiga, mas refletindo sobre o assunto recentemente faço as seguintes perguntas:
Esse é um problema mesmo das Funções ZZ?
 - Pelo que entendo as Funções não sofrem do problema em si, mas ao utilizar o ``` clitest ``` em seu testador.

Não é o caso de fechar esse issue e abrir um novo issue dentro do ``` clitest ```?
 - Afinal esse problema pode se repetir em outros programas que o utilizem para verificação, estando em uma distro Debian ou uma de suas variantes.

Não quero tirar foco do problema, apenas acho que não é aqui que teremos uma solução efetiva.
E vislumbro que uma solução específica nas Funções ZZ, corre o risco de ser uma solução temporária em caso de mudanças futuras no ``` clitest ```, ou pior uma solução não compartilhada, por aqueles que não usem as ZZ, mas fazem uso do ``` clitest ```.

Encaro como forma de atacar o problema em sua origem, e não solucionar apenas seus efeitos.

O que acham?

**Comment by aureliojargas** [comment]
Não é bem problema do clitest em si, mas da escolha do ambiente Debian que difere dos demais. Mas realmente, por enquanto ainda somos bash-only então não faz sentido nos preocuparmos com isso.

Pra resolver é fácil, é só chamar o clitest como `bash clitest`, aí o bash será usado e os testes passarão normalmente.

**Comment by itamarnet** [comment]
Com essa nova abordagem é melhor descartar o branch ``` zzascii-opcoes-d-x-o ```.
Afinal aquela solução era pontual para atender a ``` zzurlencode ``` nos testes que falhavam e que fez emergir o problema com o ``` Dash ```

**Comment by aureliojargas** [comment]
Concordo!

**Comment by aureliojargas** [comment]
Agora que o testador está sempre usando o bash #234, podemos fechar essa issue. Se no futuro quisermos que as ZZ também suportem o dash, já está aqui a referência de um problema que precisaremos resolver.
