### ISSUE TITLE
zzlibertadores: quebrou no BSD (comando date não portável)

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#209]
```console
$ zzlibertadores 2
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
-bash: test: !=: unary operator expected
Grupo 1
...
```

O trecho que quebrou é o que checa a data do arquivo de cache. Foi usada uma opção não portável do comando `date`. Em geral, é bom evitar usar o `date`, ele é bem problemático. O commit que o introduziu é o c15102fe69d29d75bb8855b83797c2db01e2aa4e.

```console
$ cache=$(zztool cache libertadores)
$ date -r "$cache" +%F
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
$
```

**Comment by itamarnet** [comment]
Troquei o uso do ``` date ``` pelo ``` zzdatafmt ```, para evitar problemas de compatibilidade

E ao invés de tentar avaliar a data da modificação do arquivo cache, salvo a data efetivamente na primeira linha, sendo consultada posteriormente, sem interferir no restante do conteúdo que procede so site.

Não é a solução mais elegante, mas pareceu a mais eficiente.

Ver comit: 9a40b35a9759e46f2913c5305dd3bec868b9f074

**Comment by aureliojargas** [comment]
Gostei da solução, essa é bem portável. :+1:
