### ISSUE TITLE
Usar zztool mktemp para arquivos temporários

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#210]
Algumas funções que hoje usam `zztool cache` devem ser atualizadas para usar `zztool mktemp`, caso o seu uso seja realmente de um arquivo temporário (que deve ser apagado) e não de um arquivo de cache (que deve permanecer na pasta após o uso).

Para encontrar os candidatos: 

```
grep 'zztool cache' zz/*
```

O uso é similar:

```
local cache=$(zztool cache foobar)

local tmp=$(zztool mktemp foobar)
```

**Comment by aureliojargas** [comment]
@itamarnet coloquei este issue na meta do release, pois acho que é importante resolver isso para o release oficial, evitando problemas bizarros como o da zzxml no #191.

Por enquanto vou trabalhar no bug da zzloteria #178, fique à vontade se quiser atacar este.

**Comment by itamarnet** [comment]
@aureliojargas
Fiz uma varredura nas funções e alterei várias ocorrências do ``` zztool cache ``` por ``` zztool mktemp ``` naquelas que considerei onde os arquivos tenham tempo de vida limitado pelo processo.

Os que possuem testadores continuam funcionando, e os demais não notei nenhum problema nos testes avulsos que realizei.
Se puder teste na sua máquina, e se tudo der certo pode fechar esse issue?

Ver commit e83f22b7b60ba6650147ec436063292f666d671a

**Comment by aureliojargas** [comment]
Show de bola! Rodei os testes por aqui e foi tudo 100% :+1:

**Comment by aureliojargas** [comment]
Achei mais a `zzdos2unix` e a `zzlembrete`. Agora acho que está tudo ok.

**Comment by itamarnet** [comment]
Ops. Falha minha. Valeu :+1:
