### ISSUE TITLE
zzxml: Erro com a opção --tag, em comandos aninhados.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#211]
O teste 21 do testador para zzxml:
```
cat zzxml.in.xml | zzxml --tag xml | zzxml --tag para | zzxml --tag strong
```

deveria retornar a saída:
```
<strong>
negrito
</strong>
```

Mas o retorno obtido é:
```
<strong>
  negrito  
</strong>
```

**Comment by aureliojargas** [comment]
Percebi que a cada comando aninhado, ele adiciona um espaço adicional no início.

```console
$ cat zzxml.in.xml | zzxml --tag xml | zzxml --tag para | zzxml --tag strong
<strong>
  negrito  
</strong>
$ cat zzxml.in.xml | zzxml --tag xml | zzxml --tag strong
<strong>
 negrito 
</strong>
$ cat zzxml.in.xml | zzxml --tag strong
<strong>
negrito
</strong>
$
```

**Comment by itamarnet** [comment]
@aureliojargas 
Acho que o problema na verdade é com a opção ``` --tidy ```, que se tornou um pré-requisito para ``` --tag ```.

Refazendo a chamada original para:
```
zzxml --tag strong zzxml.in.xml | zzxml --tidy | zzxml --tidy
```

Obteremos também:
```
<strong>
  negrito  
</strong>
```

Observe que o espaço adicional é tanto no início quanto no final do conteúdo da tag:
```
cat zzxml.in.xml | zzxml --tag strong | zzxml --tidy | cat -E
<strong>$
 negrito $
</strong>$
```

Observando o trecho que trata da opção ``` --tidy ``` também não consegui observar nada que justifique esse comportamento, assim como já não hava nada também na opção ``` --tag ```.
Mas como não manjo tanto de sed, solicito seu help. É um comportamento que sinceramente não sei explicar.
Alguma idéia?

**Comment by aureliojargas** [comment]
Boa! Conseguiu ir mais fundo no problema.

Dei uma olhada rápida aqui e não cheguei a nenhuma conclusão. Depois vejo isso com mais calma.

O que pude notar, é que o problema já existe na versão anterior também, então não tem a ver com as mudanças recentes:

```console
$ echo '<strong>negrito</strong>' | funcoeszz13 zzxml --tidy | funcoeszz13 zzxml --tidy | sed -n l
<strong>$
 negrito $
</strong>$
```

**Comment by itamarnet** [comment]
@aureliojargas 
Desconfio fortemente que o problema esteja nessa linha:
https://github.com/funcoeszz/funcoeszz/blob/master/zz/zzxml.sh#L210

O que acha?

**Comment by aureliojargas** [comment]
Na mosca!

```console
$ echo '<strong>negrito</strong>' | funcoeszz13 zzxml --tidy | zzjuntalinhas -d ' ' 
<strong> negrito </strong>
$
```

Bem, a ideia de delimitar com espaço ao juntar é para casos como:

```html
<a
href="foo.html">
```

Pra que não fique `<ahref="foo.html>`.

Vai ser difícil corrigir isso sem complicar demais o código. E já que esse é pra ser um parser bem simples, acho melhor deixarmos assim mesmo. Concorda?

**Comment by itamarnet** [comment]
Talvez após a passagem do tidy, possa ter um comando assim logo na sequência:
```
sed 's/^ //;s/ $//'
```
Não sei se isso serve para todos os casos, mas é um paliativo.
Se isso não der certo, é melhor deixar como esta, no máximo usamos a zztrim se for o caso.

**Comment by itamarnet** [comment]
Também pensei em trocar os trecho:
```
s/</\
</g
```
e
```
s/>/ >\
/g
```

por:
```
s/[[:blank:]]\{0,1\}</\
</g
```
e
```
s/>[[:blank:]]\{0,1\}/ >\
/g
```
Mas espaço pré-existentes no arquivo poderiam ser afetados também.

**Comment by aureliojargas** [comment]
É bom não mexer no conteúdo das tags, pois os espaços internos podem ser significativos. Teria que remover somente aqueles que nós mesmos inserimos com a `zzjuntalinhas`.

Mas olha só, isso é um bug pré-existente, desde a versão anterior, então neste momento acho melhor deixar como está. Vou remover este issue da milestone do release e deixamos ele pra depois, não é urgente.

**Comment by itamarnet** [comment]
:+1:

**Comment by itamarnet** [comment]
@aureliojargas Não sou versado no sed como você, mas olhando esse problema em especial acho que a solução pode não estar aqui na ``` zzxml ```, mas sim na  ``` zzjuntalinhas ```.

Veja se isso confere. 
```
				$fim {
					s/.*//
					x
					s/^\n//
					s/^$separador//  # <- Incluir esse trecho solucionaria?
					s/\n/$separador/g
					p
					d
				}
```

A inclusão comentada resolveria o problema da ``` zzxml `` sem prejudicar o funcionamento da ``` zzjuntalinhas ```? O que acha?

**Comment by itamarnet** [comment]
Alterando delimitador usado pela ``` zzjuntalinhas ``` que causa o problema do espaço adicional.
Ver commits e7d902f3ed9396598130a8a3e5805dca4047c33c e fd6e6499f236d0d5d02f950a5ae1e13377bdf88f
