### ISSUE TITLE
zzxml: testes de precedência

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#212]
@itamarnet vi estes comentários no cabeçalho da `zzxml`:

```
# Obs.: --notag tem precedência sobre --tag e --untag.
#       --untag tem precedência sobre --tag.
```

Tentei fazer testes para comprovar isso, mas não consegui. Talvez eu não tenha entendido exatamente o que estas frases significam. Me ajuda? :)

**Comment by itamarnet** [comment]
Testes para precedência do ``` --notag ``` e ``` --untag ```.

A idéia é justamente não haver conflito das opções, então se ``` --tag ``` for usado junto ``` --untag ``` ou ``` --notag ``` referenciando a mesma "tag", há a precedência das últimas, não ocorrendo a seleção.

O mesmo raciocínio se aplica no uso de ``` --untag ``` se for usado junto com ``` --notag ```, onde ``` --notag ``` tem a preferência de excluir primeiro.

Commit: 3eb664b2ac773b44b91b00aca210ec98c7eb1d34

**Comment by aureliojargas** [comment]
:+1:
