### ISSUE TITLE
zzquimica: linhas estranhas na saída

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#214]
O testador apontou que há duas linhas novas, “intrusas”, na saída da zzquimica:

```console
$ zzquimica | grep '</'
57-71 </Em>         </Abbr> </I>         </Small>           Lantanídeo ()
89-103 </Em>         </Abbr> </I>         </Small>           Actinídeo ()
```

**Comment by itamarnet** [comment]
Acho que o commit 3b56be7e00880dff4c6b6e0800b351bcdda3634c resolve esse problema.
Podem confirmar se ficou certo? No momento estou impossibilitado para testes.

**Comment by aureliojargas** [comment]
Não resolveu, a saída continua igual aqui.

Mas deixemos isso para depois do release, nem esquente.

**Comment by itamarnet** [comment]
A solução que mandei funcionou aqui.
Antes de chamar a zzquimica limpa o cache e verifica se funciona, acho que é por isso que o problema ainda persiste.

**Comment by aureliojargas** [comment]
Tem razão @itamarnet, era o cache. Eu odeio caches. E proxies. :)
