### ISSUE TITLE
zzglobo: o site consultado não traz a programação correta

### ISSUE THREAD

**Issue by gmgall** [funcoeszz/funcoeszz#217]
No momento em que escrevo essa mensagem, a ``zzglobo`` informa que está passando futebol.

```
$ date; zzglobo
Dom Jun 14 16:53:56 BRT 2015
Hoje [14-06-2015]

01:10 - Supercine
02:30 - Corujão
04:30 - Uma Família da Pesada
06:00 - Santa Missa
07:00 - Globo Comunidade
07:30 - Pequenas Empresas, Grandes Negócios
08:05 - Globo Rural
09:00 - Auto Esporte
09:30 - Esporte Espetacular
12:45 - Temperatura Máxima
14:40 - Esquenta!
16:00 - Futebol 2015
18:00 - Domingão do Faustão
20:45 - Fantástico
23:20 - SuperStar
```

Mas o site da Globo informa que está passando filme:

![screenshot - 14-06-2015 - 16 57 53](https://cloud.githubusercontent.com/assets/973834/8150200/99a6ed5e-12b6-11e5-943f-e00908ac32a5.png)

**Comment by itamarnet** [comment]
Esse é um problema recorrente de muitos sites que exibem programação da televisão.
Há problemas do mesmo gênero no site usado pela ``` zztv ```, todavia dos que eu consultei é o que dá menos problemas nesse sentido.
Não sei se esse issue pode ser efetivamente arrumado, exceto se consultar, assim como você fez, o site da própria Rede Globo.

**Comment by aureliojargas** [comment]
Será que a confusão não é por causa que o futebol ficou "no meio" do Domingão do Faustão? No site da Globo isso fica claro, enquanto no que a zzglobo consulta, o Domingão só aparece uma única vez. Talvez nesses casos especiais a programação sai diferente nos outros sites...

**Comment by itamarnet** [comment]
Voltando a tônica do assunto, acho que esse issue só se resolve de 2 maneiras possíveis:
 - Trocar o site consultado na função, pela site da própria Rede Globo, que pode ter problemas de mudanças futuras de layout ou uso de Ajax.
 - Não considerar isso um erro, visto que a função cumpre ao que foi proposto, e erros pontuais de quem administra o site não devem ser considerados.

O que acham?
