### ISSUE TITLE
FunçõesZZ não funciona

### ISSUE THREAD

**Issue by pekman1** [funcoeszz/funcoeszz#218]
Olá.

Instalei os scripts das FunçõesZZ conforme o guia de instalação do Git Hub. No entanto só retorna 
```comando não encontrado.```

*Uso Manjaro Linux*
*Shell: Bash*

**Comment by itamarnet** [comment]
Já verificou se a variável de ambiente ``` $ZZPATH ``` foi devidamente definida?

E fez a devida adequação da linha de exemplo do guia: ``` export ZZDIR="/Users/aurelio/funcoeszz/zz" ```
para:  ``` export ZZDIR="home/SEU_USUARIO/funcoeszz/zz" ``` ?

Verificou se essas linhas constam no final do ``` .bashrc ``` ?

**Comment by pekman1** [comment]
Sim. Fiz conforme o figurino

**Comment by pekman1** [comment]
Ok, agora funcionou.

Não sei se é um erro no how to de instalação

'export ZZDIR="/Users/aurelio/funcoeszz/zz"'

No lugar do user não sería $HOME?

Muito obrigado por responder. Irei divulgar as FunçõesZZ no nosso blog e fórum sobre o Manjaro.

**Comment by itamarnet** [comment]
Não creio que seja um erro, mas apenas uma informação incompleta.
O @aureliojargas usa MAC e provavelmente é essa a estrutura padrão neles, e no Linux comumente, mas não obrigatório, fica na pasta "/home"
Mas a idéia é boa, apenas é bom verificar se a variável "$HOME" atende a todas as plataformas, no caso Linux, MAC e BSD.
Valeu pelo retorno, e depois nos envie o link do blog e fórum.

**Comment by aureliojargas** [comment]
Tem que fazer conforme o guia manda:

```
./funcoeszz zzzz --bashrc
```

Que ele vai expandir o path corretamente.
