### ISSUE TITLE
zztv: não está funcionando

### ISSUE THREAD

**Issue by alexandre-mbm** [funcoeszz/funcoeszz#219]
Parece que houve mudança em URL.

**Comment by itamarnet** [comment]
Não consegui detectar qualquer problema com a função ou com a URL que é usada.
Nos testes que executei ela está funcionando perfeitamente.
Talvez tenha sido um problema transitório, uma indisponibilidade do link por um período.
Há a possibilidade de você testar de novo, e confirmar se a indisponibilidade permanece?
E se não estiver funcionando, poderia demonstrar com mais detalhes o erro que recebe e em que condições?

No aguardo.

**Comment by alexandre-mbm** [comment]
```console
$ zztv CUL
Agora
$ zztv CUL s
Agora
$ zztv
Agora
```

A palavra agora aparece colorida, de ciano.

**Comment by itamarnet** [comment]
Os caches costumam ser salvos em pasta temporárias, que normalmente descartam esses arquivos de tempos em tempos. Mas há casos que essa rotina pode está desabilitada, dependendo da distro ou do OS.

Para limpar o cache da zztv apenas pode digitar: ``` zztool cache rm tv ```, 
mas se quiser limpar todos os caches ligados as Funcões ZZ: ``` zztool cache rm '*' ```.

Veja se isso ajuda em algo.

**Comment by alexandre-mbm** [comment]
Nada mudou. Minha instalação está segundo instruções no README.md. Continuo achando que eu já lhe [apontei](#issuecomment-135377012) com acerto aonde está o bug.

**Comment by itamarnet** [comment]
Lamento, mas realmente não sei o que acontece.

A URL "http://meuguia.tv/programacao" sozinha realmente não funciona, mas ela é apenas uma parte das URLs conforme as opções são escolhidas, tendo agregada sufixos adicionais para cada caso.

Há 3 coisas que poderiam ser feitas para maiores subsídios:
 - Qual o shell que está sendo usado e o Sistema Operacional/Distro?
 - Verificar a existência do arquivo ``` zz.tv ``` na pasta temporária. Normalmente no Linux e BSD é a pasta ``` /tmp ```.
 - Executar o comando ``` zzzz --teste ```, para verificar se não há alguma pendência que eventualmente possa estar atrapalhando.

No momento estou longe do meu computador com as Funções ZZ, e por enquanto não tenho como executar mais testes, mas assim que possível farei novas verificações.

**Comment by alexandre-mbm** [comment]
```console
$ test -e /tmp/zz.tv ; echo $?
0

$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

$ ps -p $$
  PID TTY          TIME CMD
24924 pts/5    00:00:00 bash

$ bash --version
GNU bash, version 4.3.33(1)-release (i686-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
alexandre@notebook-itautec ~ $ zzzz --teste
Procurando o comando awk...   OK
Procurando o comando bc...    OK
Procurando o comando cat...   OK
Procurando o comando chmod... OK
Procurando o comando clear... OK
Procurando o comando cp...    OK
Procurando o comando cpp...   OK
Procurando o comando cut...   OK
Procurando o comando diff...  OK
Procurando o comando du...    OK
Procurando o comando find...  OK
Procurando o comando fmt...   OK
Procurando o comando grep...  OK
Procurando o comando iconv... OK
Procurando o comando lynx...  Comando ESSENCIAL 'lynx' não encontrado
Procurando o comando mktemp... OK
Procurando o comando mv...    OK
Procurando o comando od...    OK
Procurando o comando ps...    OK
Procurando o comando rm...    OK
Procurando o comando sed...   OK
Procurando o comando sleep... OK
Procurando o comando sort...  OK
Procurando o comando tail...  OK
Procurando o comando tr...    OK
Procurando o comando uniq...  OK

**Atenção**
Há pelo menos um comando essencial faltando.
Você precisa instalá-lo para usar as Funções ZZ.

Verificando a codificação do sistema... UTF-8
Verificando a codificação das Funções ZZ... UTF-8
```

Vou instalar o `lynx`, pra ver se corrige!

**Comment by alexandre-mbm** [comment]
Ótimo, corrigiu! :100:

**Comment by itamarnet** [comment]
:+1:

**Comment by aureliojargas** [comment]
Show esse troubleshooting! :+1: 

É bom sempre lembrar do `--teste` quando aparecem estes problemas estranhos (eu sempre esqueço!)
