### ISSUE TITLE
Inverso da função zzunescape

### ISSUE THREAD

**Issue by a2fmedeiros** [funcoeszz/funcoeszz#224]
Olá,
Antes de mais nada, parabéns pela iniciativa de criar esse grupo de funções.
Comecei a usá-las rcentemente e senti falta de substituir em um texto os caracteres acentuados pelos seus equivalentes em HTML, por exemplo trocar o cedilha por &ccedil;, ou seja, o inverso da função zzunescape.
Desculpe se já existe e eu não encontrei, é que são muitas funções.
Mais uma vez parabéns e obrigado.
[]s
Allan Medeiros

**Comment by itamarnet** [comment]
Caro Allan
Realmente não existe uma função inversa da ``` zzunescape ```, mas há duas que se aproximam disso, ou ao menos tem uma proposta nessa direção: ``` zzasci ``` e a ``` zzstr2hexa ```.
Elas podem fornecer uma maneira de obter esse resultado, ou poderia apenas inverter as sintaxes usadas na própria ``` zzunescape ```.
Há algumas pegadinhas se for usar essa última sugestão:
 - O uso do caractere ``` & ```
 - Qual código retornar: decimal, hexadecimal ou html

Obs.:
No seu texto quando diz ``` cedilha por ç ``` imagino que tenha dito  ``` cedilha por &ccedil; ```, ``` cedilha por &#0231; ``` ou    ``` cedilha por &#xE7; ```

**Comment by itamarnet** [comment]
Olá Alan
Olha algo interessante que pode oferecer o que você sugere sem muito trabalho
Vou pegar minha última frase do comentário anterior como exemplo:
```
echo "No seu texto quando diz cedilha por ç imagino que tenha dito cedilha por &ccedil;, cedilha por &#0231; ou cedilha por &#xE7;" |
$ZZWWWDUMP  -assume_charset=utf-8 -stdin |
zztrim
```
E então, isso serve?

Obs.: O uso de ``` -assume_charset=utf-8 ``` é para suprir alguns problemas de interpretação em algumas versões do ``` lynx ``` com caracteres especiais. O seu uso não influencia naqueles que não apresentam esse problema.

**Comment by a2fmedeiros** [comment]
Olá,
Eu me confundi na ultima frase o certo era trocar o cedilha (ç) pode
&ccedil; etc.
Agradeço pela ajuda, mas o resultado do que vc mandou foi  o seguinte:

allan@allan:~$ echo "No seu texto quando diz cedilha por ç imagino que
tenha dito cedilha por &ccedil;, cedilha por &#0231; ou cedilha por &#xE7;"
| $ZZWWWDUMP  -assume_charset=utf-8 -stdin | zztrim

No seu texto quando diz cedilha por ç imagino que tenha dito cedilha por ç,
cedilha por ç ou cedilha por ç




--
*Allan Medeiros*
Analista de Informática
__________________________________________
Companhia de Processamento de Dados da Paraíba
medeiros@codata.pb.gov.br





Em 5 de dezembro de 2015 11:27, itamarnet <notifications@github.com>
escreveu:

**Comment by itamarnet** [comment]
Cara você tem razão, e eu fui no embalo.
Se é pra ser o inverso da ``` zzunescape ```, não tem cabimento o que eu disse. A sugestão que eu dei, faz a mesma coisa. Foi mal :(

**Comment by a2fmedeiros** [comment]
;-))
Ei Aurélio, quando quiser conhecer a Paraíba está convidado!
Grande abraço.



--
*Allan Medeiros*
Analista de Informática
__________________________________________
Companhia de Processamento de Dados da Paraíba
medeiros@codata.pb.gov.br





Em 6 de dezembro de 2015 07:50, itamarnet <notifications@github.com>
escreveu:

**Comment by itamarnet** [comment]
Resolvi fazer uma função oposta a ``` zzunescape ```
Acho que atende a solicitação.
Veja no commit 7505d0052e0f0030b031019aa4083a786d2bea29
