### ISSUE TITLE
zzpiada: Não responde.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#226]
A função zzpiada não responde.
Aparentemente o domínio não existe mais ou está temporariamente inativo.
Caso não retorne em alguns dias, acredito que a melhor solução seja desativa-la de vez.

**Comment by itamarnet** [comment]
Site voltou a funcionar.
Nada a ser feito.

**Comment by itamarnet** [comment]
Site muito instável, talvez seja melhor desativá-la em definitivo :(

**Comment by aureliojargas** [comment]
Se tá dando trabalho, desativa mesmo!

**Comment by itamarnet** [comment]
Desativada em definitivo
Commit 69e9439b1c6d496ad2361096236b7d47bfa5fff7
