### ISSUE TITLE
zzoperadora não funciona?

### ISSUE THREAD

**Issue by aleprovencio** [funcoeszz/funcoeszz#227]
Estou testando com o próprio exemplo da documentação (zzoperadora 1934621026) e não recebo retorno algum.

**Comment by itamarnet** [comment]
Realmente não funciona mesmo.
Mudança do site, mas vou verificar qual a natureza exata e assim que possível corrigimos.
Valeu pelo aviso!

**Comment by itamarnet** [comment]
Reativada.
Vide commit: e6582845793a8fa22ad3020f1b6490a9a7657e79

**Comment by aleprovencio** [comment]
Muito obrigado!
