### ISSUE TITLE
zztimer e zzcrono(metro)

### ISSUE THREAD

**Issue by aleprovencio** [funcoeszz/funcoeszz#228]
O que acham de algo como `zztimer 1:30` ?

**Comment by itamarnet** [comment]
Qual seria a intenção?
O comando sleep não atenderia já apenas convertendo para sleep 90?
Ou é exibir uma contagem regressiva?

Apenas detalhe um pouco mais sobre o objetivo por favor.

**Comment by aleprovencio** [comment]
exatamente @itamarnet, o grande lance seria a exibição dos contadores atualizando

**Comment by itamarnet** [comment]
Fiz o commit de uma função que creio que atende o que pediu.
Dá uma conferida em 10c97e73fb48ed6867da530fbafe86448696ae35

**Comment by aleprovencio** [comment]
atende com perfeição! :D
A zztimer sem dúvidas é a mais legal mas a zzcrono você acha besteira?

**Comment by itamarnet** [comment]
Desculpe @aleprovencio acho que não entendi então.
Imaginei que havia digitado errado e que queria dizer algo como "zztimer ou zzcrono(metro)", que ao meu entender são coisas idênticas, mudando apenas o nome.

Seja mais detalhista e qual seria a diferença entre ambas? Sinceramente não imaginei duas opções, mas apenas alternativas de nome.

Obs.: E essa zztimer tem mais um efeito estético, não dá pra contar com uma precisão "suiça", pois a cada arquitetura o processamento pode ser muito lento, gastando mais tempo do que é exibido.

**Comment by aleprovencio** [comment]
Desculpe ser tão vago @itamarnet . A zzcrono seria basicamente uma zztimer simplificada, mas com contagem progressiva ao invés de regressiva e sem necessidade de argumento algum. Se quiser deixá-la ainda mais legal o pressionamento de alguma tecla poderia imprimir o tempo das voltas (laps).

**Comment by itamarnet** [comment]
Entendi @aleprovencio 
Isso é algo possível de ser feito, mas esbarra num problema.

Temos "Coding Style" e a idéia violaria um desses princípios, a saber: https://github.com/funcoeszz/funcoeszz/wiki/Coding-Style#interatividade-zero

Existem algumas funções antigas que não se enquadram nesse quesito também, mas são anteriores a essa diretriz, e serão modificadas. Todavia tentamos evitar criar algo que fuja dessa linha.

Mas vi que vc criou um fork do desse projeto, talvez possamos criar algo e que fique na sua versão apenas.

Além disso a ``` zztimer ``` precisa de alguns ajustes e testes adicionais, é apenas um commit inicial. E salvo raras exceções, normalmente sempre existem melhorias posteriores a cada nova função criada.

Vou deixar esse issue fechado, mas não quer dizer que o assunto esgotou, apenas acredito que, conforme expliquei, não se aplicaria aqui.

Tudo bem?

**Comment by aleprovencio** [comment]
Não havia me atentado à essas diretrizes. Está ótimo, obrigado novamente @itamarnet !
