### ISSUE TITLE
zztv: próximas atrações

### ISSUE THREAD

**Issue by aleprovencio** [funcoeszz/funcoeszz#229]
Seria muito útil se tivevesse um argumento para mostrar ao invés da programação que está no ar, a que vai entrar na sequência.
Ex: `zztv filmes prox` mostraria os próximos filmes que vão começar

**Comment by itamarnet** [comment]
@aleprovencio 
A idéia é boa, mas o site consultado não oferece essa possibilidade nas categorias, exceto por canal.

A consulta por canal mostra o que passa no momento e o resto da grade divulgada, e há a possibilidade de ver dias posteriores, mas apenas por canal..

Se houver algum outro site que possa ser consultado e que ofereça essa possibilidade, é algo a ser considerado.

Eu pessoalmente, aprecio a forma como o "http://meuguia.tv/" apresenta seu conteúdo, sua variedade e a estabilidade de seu layout, o que não ocorria em outros sites consultados a época de sua adoção.

No momento acho difícil ter essa opção implementada.

**Comment by aleprovencio** [comment]
Entendi @itamarnet, eu tb até tentei fazer umas gambiarras com xargs e grep mas no fim não gostei do resultado, pena mesmo.
Valeu
