### ISSUE TITLE
zztool: Incluir 'testa_octal' e 'testa_hexadecimal'.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#230]
Já existem as ferramentas ``` testa_binario ``` e ``` testa_numero ``` na ``` zztool ```, se for pertinente poderiam ser inclusas a ``` testa_octal ``` e ``` testa_hexadecimal ``` ( ou ``` teste_hexa ``` ).

Há uma amostra de como o código poderia ser feito na ``` zzconverte ``` no commit 70db70f5c7e5785d0703d10b7be10aa5c172418d.

**Comment by aureliojargas** [comment]
Acho massa! :+1:

**Comment by itamarnet** [comment]
Aqui também deixo a sugestão do @rafaelsilvag, que foi feita em https://github.com/funcoeszz/funcoeszz/pull/232, onde poderíamos ter também o ``` testa_mac ```.

Esperava que ele mesmo fizesse a sugestão em um novo issue, ou comentando aqui.

De toda forma a ideia parece interessante em um novo release.

**Comment by rafaelsilvag** [comment]
Se for pertinente, incluir a função testa_mac. O exemplo do código alterar, com sugestões do @itamarnet, estão no commit (https://github.com/rafaelsilvag/funcoeszz/commit/f1bb9f20073d17b8b89f1099dda8dc6e6a2e955b) feita em #232. Esta função, irá validar se o argumento possui um formato de mac válido.

**Comment by itamarnet** [comment]
Ao invés de criar novas ferramentas na ``` zztool ```, houve a criação de uma nova função: ``` zztestar ``` que cobre essa sugestão.
Ver commit 61ddff02b3dcbb94b87c4078d78baee68bca34a7
