### ISSUE TITLE
zznarrativa não mais responde.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#231]
Ao solicitar qualquer palavra ou frase ao ``` zznarrativa ``` não há nenhum retorno.

Acessando o google diretamente simulando a url montada pela zz, há a solicitação de confirmação com um formulário usando "captcha".

Alguém mais está com o mesmo problema?

Se confirmar essa situação, o caminho natural é achar outra fonte ou desativar essa função.

**Comment by itamarnet** [comment]
DESATIVADA: Limitações impostas pelo Google e sem uma opção viável para substituição.
Commit 5df6291e12a0e9eaec9d827d8d12aa7d244ffc47

**Comment by aureliojargas** [comment]
:+1:
