### ISSUE TITLE
Modificar "zztool num_linhas", e promover "iconv" a comando essencial.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#233]
Trocar a função ``` num_linhas ``` 
de: 
```
			zztool file_stdin "$@" |
				wc -l |
				tr -d ' \t'
```

para:
```
			zztool file_stdin "$@" |
				sed -n '$='
```

 - Faz mais sentido usar o ``` sed ```, que é um comando essencial ao core, do que o ``` wc ``` que sequer é listado com opcional.
 
- Promover o ``` iconv ``` como comando essencial, visto a sua utilidade dentro do core e demais funções.

**Comment by aureliojargas** [comment]
Eu acho que tinha alguma motivo de portabilidade pra ser assim. Algo como diferentes seds trazerem resultados em formatos diferentes.

Mas pode ser viagem minha, pois com o `wc` tem o mesmo problema...

**Comment by itamarnet** [comment]
Não desconfio qual fosse o motivo original, mas vi que havia o uso do ``` sed ``` nas funções e não o uso dessa ferramenta.

Todavia o que mais me chamou a atenção é o resultado dessa comparação que exemplifico:
```
$ printf 'linha1\nlinh2\nlinha3' | wc -l
2
```
```
$ printf 'linha1\nlinh2\nlinha3' | sed -n '$='
3
```
 Pelo retorno dos resultados, acho que é mais uma justificativa pela troca.

E só para não contrariar com o ``` awk ``` também teria um resultado mais adequado:
```
$ printf 'linha1\nlinh2\nlinha3' | awk 'END {print NR}'
3
```
É o caso de esperar um futuro release ou já aplicar essa mudança?

**Comment by itamarnet** [comment]
Sugestão parcialmente resolvida no commit 61ddff02b3dcbb94b87c4078d78baee68bca34a7 com a criação da ``` zztestar ```

**Comment by aureliojargas** [comment]
Olha só, não sabia que o wc ignorava a última linha sem `\n`, estranho...

Acho que é o caso de trocar e ver se quebra os testes.

**Comment by itamarnet** [comment]
Nem eu sabia até pouco tempo, mas pelo que eu pude entender o wc faz a contagem de linhas pela quantidade de ocorrências do ``` New Line (\n) ```.

Nos testes que fiz, assim como exemplifiquei, tanto o sed como o awk trazem um resultado mais adequado na contagem, ou usar a alternativa ```zzwc ```.

**Comment by itamarnet** [comment]
Solicitações resolvidas nos commits cf7b694878330bd257b9f10242c29a6608326933 e 7e29a5f599b1aa5721e8e66225e0016619893e50

**Comment by aureliojargas** [comment]
:+1:

**Comment by aureliojargas** [comment]
Achei o problema de usar sed: quando não tem linhas.

```
$ true | sed -n '$='
$ true | wc -l | tr -d ' \t'
0
$
```

**Comment by itamarnet** [comment]
Temos um problema duplo então:
 - Arquivo vazio
 - Ou não terminando em ``` \n ```

Tenho duas sugestões:
 - Direcionar para uma variável e se estiver vazia, assume-se 0
``` 
$ linhas=$(true | sed -n '$=')
$ echo ${linhas:-0}
0
```

 - Ou usar awk: ( Não recomendo )
```
$ true | awk 'END {print NR}'
0
```

**Comment by aureliojargas** [comment]
Boa ideia, usei a variável então :+1:
