### ISSUE TITLE
zztool: Incluir a 'num_caracteres' ou 'num_chars'

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#235]
Sugestão leva em conta alguns aspectos do comando ``` wc ```:
 - Nem todas as versões contam com a opção ``` -m ``` que conta caracteres, o que pode ser um problema de portabilidade.
 - Há um retorno diferente da quantidade de caracteres ou bytes quando se usa o ``` printf ``` ou ``` echo ```, pois o ``` wc ``` contabiliza o ``` new line ( \n ) ```.
 - O ``` wc ``` também contabiliza o ``` carriage return ( \r ) ``` de arquivos oriundos do Windows ou Mac.

 Poderia ser algo assim:
```
			zztool multi_stdin "$@" |
				sed 's/[[:cntrl:]]//g; s/././g' |
				tr -d '\r\n' | # aqui também poderia ser: awk '{printf $0}'
				wc -c
```

**Comment by aureliojargas** [comment]
Boa ideia. Talvez zzcount pra ficar mais genérico.

O awk dá pra trocar por `tr -d '\n'`.

**Comment by itamarnet** [comment]
A citação ao ``` awk ``` é uma opção apenas, que poderia ser alternativa ao trecho ``` tr -d '\r\n' ```, mas que não considerei por não ser um dos comandos essenciais.

A sugestão para constar no core é baseada na mesma lógica do ``` zztool num_linhas ```, mas se for para ser uma função externa talvez seja melhor usar ``` zzwc ```. Ai além dessa ideia exposta, também englobaria ``` zztool num_linhas ``` e uma emulação também do comando ``` wc ``` com as opções ``` -c ```, ``` -L ``` e ``` -w ```.

**Comment by itamarnet** [comment]
Criada a função ```zzwc ``` que atende essa demanda com a opção ``` zzwc -m ```.
Vide commit 9d0d24a6ba00a9abd52f16d0838372196d02e4f1
