### ISSUE TITLE
Criar "zztesta" em substituição a "zztool testa_*"

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#237]
Acredito que seria interessante a criação da uma nova função especialmente apenas para testes, que estivesse desvinculada do core.
Num primeiro momento substituiria as seguintes opções da ``` zztool ```:
```
testa_ano
testa_ano_bissexto
testa_numero
testa_numero_sinal
testa_numero_fracionario
testa_dinheiro
testa_binario
testa_ip
testa_data
testa_hora
```

E incluiria também essas duas que estão dentro da ``` zzmat ```:
```
testa_num
testa_num_exp
```

Além de atender mais rapidamente as seguintes sugestões ainda não implementadas:
```
testa_octal
testa_hexadecimal
testa_mac
```
Referência aos issues #230 e #233 .

**Comment by itamarnet** [comment]
Função criada com o nome ``` zztestar ``', mas ainda não substituindo as ``` zztool testa_* ``` usadas.
Ver commit 61ddff02b3dcbb94b87c4078d78baee68bca34a7

**Comment by aureliojargas** [comment]
@itamarnet as `testa_*` estão no core por serem essenciais para a maioria das funções. É garantido que estas ferramentas sempre vão existir. Se migrar pra uma função normal, não há mais essa garantia.

**Comment by itamarnet** [comment]
@aureliojargas Num primeiro momento considerei a possibilidade da troca, mas reconsiderei tanto que fechei o issue.
A ``` zztestar ``` age como uma intermediária até que modificações possam sem inclusas no core, ou como uma forma alternativa de teste, visto alguns testes tem comportamento apenas similar as ferramentas originais da ``` zztool ```.
Acredito que mante-la não fará mal, o que acha?

**Comment by aureliojargas** [comment]
Isso, deixa lá que ela complementa, ficou muito boa!

Pra evitar duplicação de código, alguns testes da `zztestar` podiam chamar a `zztool testa_*` equivalente.

Também agora dá pra repensar quais devem continuar no core e quais podem ficar só na zztestar, pois poucas funções usam ou não é de uso tão geral que mereça estar no core.

**Comment by itamarnet** [comment]
O ``` testa_numero ``` é um caso indiscutível que deve estar no core, ele é muito usado e uma alteração nele não acho que seja vantajosa em nenhum aspecto.

O ``` testa_ano ``` e ``` testa_data ``` são outros 2 caso que acredito que também devam permanecer no core, mas não é tão crítico e uma mudança é plausível, mas não recomendo.

Os demais acho que podemos considerar a mudança e deixar apenas no ``` zztestar ```.

Para deixar mais claro me baseie no resultado apontado pelo script que há na pasta info:
```
$ ./requisitos.sh tool
```

O que acha dessas sugestões?

**Comment by itamarnet** [comment]
Refiz o branch para esse issue, e adequei o que havia sido feito com a nova realidade.
Não quis aproveitar o branch anterior pois haveria muitos conflitos.
Mas pelo visto acabou sendo uma adaptação tranquila.

https://travis-ci.org/funcoeszz/funcoeszz/builds/127963640 

Aguardo seu OK para fazer ou não esse merge.

**Comment by itamarnet** [comment]
Feito!
Ver commits 27dfd5a8c437d717984ab9e833e0344a5990bc3a e 26e45586964c60c7a4faab4ade8842808c335bc6
