### ISSUE TITLE
Testadores: zzrastreamento, zzora, zzjuntalinhas e zzcapitalize.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#238]
``` zzrastreamento ``` - impossível testar sem um código válido.

``` zzora ``` - site inacessível. Problema temporário?

``` zzjuntalinhas ``` - Esse trecho dá erro com fim na primeira linha:
```
  $ zzjuntalinhas	-d	@	-f	1	_numeros.txt
```

``` zzcapitalize ``` - ``` XªX½ ```: por algum motivo o ``` ª ``` impede o ``` X ``` seguinte ficar em caixa alta resultando em ``` Xªx½ ```.

**Comment by aureliojargas** [comment]
Aqui no Mac a capitalize rodou normal:

```console
$ ./run zzcapitalize.sh 
..................
OK: 18 of 18 tests passed
$
```

**Comment by aureliojargas** [comment]
O mesmo pra `zzjuntalinhas`:

```console
$ ./run zzjuntalinhas.sh 
............................
OK: 28 of 28 tests passed
$
```

**Comment by aureliojargas** [comment]
Você rodou com o bash ou com o jeito antigo `/bin/sh`?

**Comment by itamarnet** [comment]
Pois é @aureliojargas eu tive esses problemas com o testador e o que tentei foi:
 - mudar a linha para ``` /bin/bash ``` no Shebang, 
 - mudar a variável ``` tester='bash clitest' ``` ,
 - invocar os comandos que deram erro fora do testador.

Em todas situações o erro permaneceu.
Usei um note com Linux Mint 17.3 e outro Desktop com o Manjaro e ambos atualizados.

Sinceramente não sei nem o que sugerir.

**Comment by itamarnet** [comment]
Então @aureliojargas, com relação a ``` zzjuntalinhas ``` o problema persiste.
O problema aparentemente está em ser o início e fim na mesma linha, por exemplo:
```
$ zzjuntalinhas -d _ -i 3 -f 3 _numeros.txt 
1
2
3
5
```
Como vc sabe não sou expert em ``` sed ```, mas numa tentativa de resolver fiz isso, apenas comentei as ações:
```
			# Exceção: Início e fim na mesma linha, mostra a linha e pronto
			$inicio {
				$fim {
					#p
					#d
				}
			}
```

E os resultados foram satisfatórios:
```
$ zzjuntalinhas -d _ -i 3 -f 3 _numeros.txt 
1
2
3
4
5
```
```
$ zzjuntalinhas -d @ -i 3 -f 3 _numeros.txt 
1
2
3
4
5
```

Não quis fazer commit dessa alteração, pois não sei se isso quebraria os testes do seu lado, e gostaria que avaliasse antes se a solução procede.

Será alguma limitação no ``` GNU sed ```? Tem alguma relação com as alterações recentes feitas no core ( Isso parece bem improvável ) ou em alguma outra função ( pouco provável também )?
 
Estranho que eu não lembro desse erro ocorrer até pouco tempo atrás.
No momento estou usando apenas 2 micros, um com Linux Mint 17.3 e outro com Manjaro.

O que acha?

**Comment by itamarnet** [comment]
O ``` zzcapitalize ``` pode desconsiderar, os testes estão "OK".

O problema realmente ocorria quando estava no jeito antigo ``` /bin/sh ```.

**Comment by aureliojargas** [comment]
Achei um código de teste pra `zzrastreamento` e atualizei o testador.

**Comment by aureliojargas** [comment]
@itamarnet você acertou! Removi aqui aquele trecho e a função continuou funcionando igual. Vai entender! :smile: 

Então todos os problemas dessa issue foram resolvidos, vou fechar.

Só peço que no futuro abra uma issue por função, para ficar mais fácil resolver/gerenciar os problemas individualmente, ok?
