### ISSUE TITLE
zzcut: problema no awk do BSD

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#244]
```
$ ./run zzcut.sh 
.................
----------------------------------------------------------------------------------------------------
[FAILED #17, line 85] zzcut	-v	-c	1~3	_tmp1
@@ -1,5 +1,3 @@
-♦u♦oe
-♦distw
-♦testhee
-♦qato♦ou
-♦cnc♦fve
+awk: illegal field $(), name "i"
+ input record number 1, file 
+ source line number 24
----------------------------------------------------------------------------------------------------
............

FAIL: 1 of 29 tests failed
```

**Comment by itamarnet** [comment]
@aureliojargas 
Na linha 166 da zzcut.sh troque:
``` split("", faixa); split($i, faixa, "~") ```

por:
``` split("", faixa); split($1, faixa, "~") ```

Acho que o erro é aqui, mas no awk que tenho ele contorna esse problema.

**Comment by itamarnet** [comment]
@aureliojargas
Veja se a solução do commit 75ce06bcd1ac00c68dc200009156bfc0486897d3 resolveu o problema.

**Comment by aureliojargas** [comment]
O erro do awk sumiu, mas a saída continua errada:

```
$ ./run zzcut.sh 
.................
----------------------------------------------------------------------------------------------------
[FAILED #17, line 85] zzcut	-v	-c	1~3	_tmp1
@@ -1,5 +0,0 @@
-♦u♦oe
-♦distw
-♦testhee
-♦qato♦ou
-♦cnc♦fve
----------------------------------------------------------------------------------------------------
............

FAIL: 1 of 29 tests failed
```

**Comment by itamarnet** [comment]
De novo não consegui reproduzir o erro comigo.

Assim que puder mude a linha 170 de:
``` printf "s/./" tsp "/" faixa[1] "; :a; s/\\(" tsp ".\\{" faixa[2]-1 "\\}\\)[^" tsp "]/\\1" tsp "/g; ta;" ```
para:
``` printf "s/./" tsp "/" faixa[1] "; :a; s/\\(" tsp ".\\{" faixa[2]-1 "\\}\\)[^" tsp "]/\\1" tsp "/; ta;" ```

Desconfio que esse 'g' adicional faça a diferença.

Fico no aguardo.

**Comment by aureliojargas** [comment]
Tirei o `g` e deu a mesma saída :/

**Comment by itamarnet** [comment]
@aureliojargas Esse é um caso que gostaria que verificasse.

Na ``` zzcut ```, que é uma função que apreciei muito em fazer, há uma mistura muito legal de recursos de ``` awk ``` e ``` sed ```.

No primeiro trecho da função o ``` awk ``` constroi o script a ser usado na segunda parte.

E na segunda parte que há a separação por campos ou caracteres.
E nesse ponto o ``` sed ``` cuida na separação por caracteres e o ``` awk ``` por campos. Nesse ponto, acho que uso o que cada ferramenta faz de melhor. Mesmo assim tanto o ``` sed ``` como o ``` awk ``` contam um com o outro para completar a tarefa que cada um faz.

O que ficou claro nesse problema, é que no BSD quando o ``` sed ``` faz uso de loop ou saltos, usando ``` b ``` ou ``` t ```, as instruções precisam estar em linhas individuais.
Essa construção ``` :volta; s/de/para/; t volta ``` falha, mas funciona dessa forma:
```
:volta
s/de/para
t volta
```

Essa é uma característica que não achei descrita em lugar nenhum, e olha que pesquisei muito e a descoberta foi apenas através de tentativa e erro.

Qualquer coisa confere em d931d3c52718ed9649e3ec2790d2eceb285a9d39

**Comment by aureliojargas** [comment]
É isso aí mesmo. A maneira mais portável é sempre um comando por linha. Eu prefiro assim também por ser mais legível.

No caso do `t` e `b`, da diferença em quais caracteres são considerados válidos como parte de label. Aí ele acaba considerando que o próximo comando ainda é o nome da label. Deixando um por linha, a ambiguidade some.

**Comment by itamarnet** [comment]
Humm!  Então é como os casos dos comandos ``` r arquivo ``` e ``` w arquivo ``` que citou na sua prévia de livro "Dominando o SED".
E por falar nisso ...

**Comment by aureliojargas** [comment]
Isso, mesmo caso do `r` e `w`.

Um por linha é mais legível, especialmente se tiver comentários explicando as partes mais intrincadas. Uma hora vou dar uma faxina de legibilidade nas funções, pra iniciantes poderem aprender com o código. As partes com sed (e agora awk hehe) são as mais alienígenas 😄

**Comment by itamarnet** [comment]
Revendo aqui alguns trechos, acho que dá um livro.
E ai, esse vc escreveria?

**Comment by aureliojargas** [comment]
**Se** eu conseguir terminar o que estou escrevendo agora, a ideia era voltar a pensar no de sed.

As ZZ têm material pra vários livros 😄  Pensa em escrever? Poderíamos fazer um livro em dupla também.
