### ISSUE TITLE
Portabilidade: sed deve fechar comando antes do }

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#245]
Várias funções estão quebradas no BSD porque o sed não fechou o último comando com ponto-e-vírgula, dentro dos blocos `{ … }`.

Vou arrumar.

**Comment by aureliojargas** [comment]
cc @itamarnet

**Comment by itamarnet** [comment]
@aureliojargas Desculpe isso me passou batido.

**Comment by aureliojargas** [comment]
Sem crise :)

A hora que o Travis estiver funcionando pra Linux e Mac esse tipo de erro vai aparecer na hora.
