### ISSUE TITLE
zzloteira: testes falhando no BSD: duplasena e federal

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#246]
```
$ ./run zzloteria.sh 
...
----------------------------------------------------------------------------------------------------
[FAILED #3, line 13] zzloteria duplasena | tr '[0-9]' 'N' | head -8
@@ -1,8 +1,8 @@
 duplasena:
 Concurso NNNN (NN/NN/NNNN)
-
-  Nº sorteio
+        Nº sorteio
    NN   NN   NN   NN   NN   NN
-
-  Nº sorteio
+        Nº sorteio
    NN   NN   NN   NN   NN   NN
+
+   Estimativa de prêmio do próximo concurso NN/NN/NNNN   R$ NNN.NNN,NN
----------------------------------------------------------------------------------------------------
...
----------------------------------------------------------------------------------------------------
[FAILED #6, line 40] zzloteria federal | tr '[0-9.]' 'N' | sed 's/ *$//;s/º  */º      /;s/  *R\$/   R$/;s/  *\([BV]\)/ \1/g'
@@ -2,9 +2,4 @@
 Concurso NNNNN (NN/NN/NNNN)
 
    Destino Bilhete Valor do Prêmio (R$)
-   Nº      NNNNN   R$ NNNNNNN,NN
-   Nº      NNNNN   R$ NNNNNN,NN
-   Nº      NNNNN   R$ NNNNNN,NN
-   Nº      NNNNN   R$ NNNNNN,NN
-   Nº      NNNNN   R$ NNNNNN,NN
 
----------------------------------------------------------------------------------------------------
..........

FAIL: 2 of 16 tests failed
```

**Comment by itamarnet** [comment]
@aureliojargas 
Esse é um item que está difícil de reproduzir, então te peço mais um favor.
Se possível me envie o resultado da saída desses comandos.
```
zztool dump links http://loterias.caixa.gov.br/wps/portal/loterias/landing/duplasena
zztool dump links http://loterias.caixa.gov.br/wps/portal/loterias/landing/federal
```
Nos ambientes onde ocorrem os testes não ocorrem essas falhas.
Ou vou ter que esperar até conseguir colocar um BSD funcionando em um VM, e minha perspectiva mais próxima é apenas no fim de semana, se não houver imprevistos.

**Comment by aureliojargas** [comment]
* [duplasena.txt](https://github.com/funcoeszz/funcoeszz/files/210383/duplasena.txt)
* [federal.txt](https://github.com/funcoeszz/funcoeszz/files/210382/federal.txt)

**Comment by itamarnet** [comment]
Obrigado @aureliojargas .

Mas acredite se quiser, não repetiu o erro.

Usei os arquivo que me mandou, repeti passo a passo o que a função faz e o que o testador faz e 
retorna o que está previsto no testador.

Obs.: Levei em consideração as "novidades descobertas" recentemente que davam erros ou divergências na saída.

Tem alguma sugestão ou teoria sobre o assunto? Confesso que ainda estou perdido.

**Comment by itamarnet** [comment]
Outra vez o uso do Travis facilitou a identificação do problema.
Mesmo caso do ``` zzmariadb ``` onde a ocorrência de "\|" não é portável.

Vide commit d1453731ac76b53d4854682b5f43c6436798062b

**Comment by aureliojargas** [comment]
Arrumou aqui também, show! 👍
