### ISSUE TITLE
zzbraille congela no Travis

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#248]
Aqui funciona normal, mas ao executar no Travis, a `zzbraille` congela no primeiro teste e não retorna mais.

Investigar melhor isso.

**Comment by itamarnet** [comment]
Nas linha 138 e 139 em ```zzbraille ```:
```
	local c='●'
	local v='○'
```

Tente substituir por:
```
	local c=$(echo "&bull;" | zzunescape --html)
	local v=$(echo "&deg;" | zzunescape --html)
```
Acho que são esses caracteres exóticos que estão travando.

**Comment by aureliojargas** [comment]
Sei lá qual que era o problema antes, agora funcionou sem precisar mexer nada na função. :smile:

**Comment by aureliojargas** [comment]
Migramos para o GitHub Actions, e o problema voltou :) 

Vide #760
