### ISSUE TITLE
zzwc: testes quebrados no BSD

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#249]
```
$ ./run zzwc.sh 
....
----------------------------------------------------------------------------------------------------
[FAILED #4, line 4] zzwc -w zzwc.in.txt	
@@ -1 +1 @@
-19
+      19
----------------------------------------------------------------------------------------------------
..
----------------------------------------------------------------------------------------------------
[FAILED #6, line 6] zzwc -L zzwc.in.txt	
@@ -1 +1 @@
-7
+8
----------------------------------------------------------------------------------------------------
.........
----------------------------------------------------------------------------------------------------
[FAILED #15, line 20] zzwc -L zzunescape.in.txt	
@@ -1 +1 @@
-28
+29
----------------------------------------------------------------------------------------------------
.

FAIL: 3 of 16 tests failed
```

**Comment by itamarnet** [comment]
Não consigo reproduzir esse erro, mas suponho que seja algo ligado ao Carriage Return '\r' ou New Line '\n'.
Lembro de ter lido algo a respeito dessas diferenças entre Linux, Windows e Mac's.
 - Linux '\n'
 - Mac '\r'
 - Windows '\r\n'

Não sei se isso é válido desde que os Macs adotaram o kernel baseado em BSD's, mas é nisso que me orientei.
Veja se soluciona para você.

Commit bf8d9c0d2a077057db2dbad9bb713c970a02ed9b

**Comment by aureliojargas** [comment]
Arrumado :

**Comment by aureliojargas** [comment]
Quanto à quebra de linha, isso de usar só `\r` era coisa do Mac clássico, antes de virar Unix. Hoje é `\n`, normal.

**Comment by aureliojargas** [comment]
Droga, eu conferi no Ubuntu (e lá funcionou), mas no BSD o problema continua.

Pelo menos resolveu um dos problemas, agora sobram dois:

```
$ ./run zzwc.sh 
......
----------------------------------------------------------------------------------------------------
[FAILED #6, line 6] zzwc -L zzwc.in.txt	
@@ -1 +1 @@
-7
+8
----------------------------------------------------------------------------------------------------
.........
----------------------------------------------------------------------------------------------------
[FAILED #15, line 20] zzwc -L zzunescape.in.txt	
@@ -1 +1 @@
-28
+29
----------------------------------------------------------------------------------------------------
.

FAIL: 2 of 16 tests failed

```

**Comment by itamarnet** [comment]
Estou sem muitas idéias sobre esse detalhe em especial e acho que vou ter que instalar um BSD numa VM para testar isso.

Antes desse recurso pode tentar mais uma opção?

Na linha 111 do ``` zzwc ``` trocar:
``` sed 's/[^[:cntrl:]]/./g' | wc -c ```

por:
``` sed 's/[^[:cntrl:]]/./g' | awk 'BEGIN {FS=""} { print NF }' ```

Não é ``` POSIX ```, mas aqui funcionou com ``` awk ```, ``` mawk ``` e ``` busybox ```.

**Comment by aureliojargas** [comment]
Bingo! Com esta alteração resolveu. :+1:

**Comment by itamarnet** [comment]
Feito!
Commit 3d7cdeb1f3d3cfe908c44e1c549589617b711378
