### ISSUE TITLE
zzlibertadores: teste falhando no BSD

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#252]
```
$ ./run zzlibertadores.sh 
..
----------------------------------------------------------------------------------------------------
[FAILED #2, line 2] zzlibertadores 3                      
Expected 16 lines, got 0.
----------------------------------------------------------------------------------------------------
...

FAIL: 1 of 5 tests failed
```

**Comment by itamarnet** [comment]
Esse é um caso que não fiz o commit, pois a mudança no site não reserva mais o espaço com as futuras vagas.
Estava tratando a parte e deixei do enviar essa alteração para não criar mais um problema.
Vou rever o que fiz, e ver se ainda é aplicável.

**Comment by itamarnet** [comment]
Solucionado em 6cf13c81ce800c63a5d39eb84b299571170821eb

A exibição de resultado é temporal, podendo ter ou não uma resposta.

**Comment by aureliojargas** [comment]
👍
