### ISSUE TITLE
zzramones: teste falhando no Ubuntu

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#258]
```
$ ./run zzramones.sh 
..
--------------------------------------------------------------------------------
[FAILED #2, line 3] zzramones UFO
@@ -1 +1 @@
-Zero Zero UFO
+   knees would bend and your hair will curl Your little girlfriend Your low cut slacks and your long black hair Your marshall law Your slacks are low and your hips are showin Youre Gonna Kill That Girl Zero Zero UFO
--------------------------------------------------------------------------------

FAIL: 1 of 2 tests failed

$ l /usr/bin/awk
lrwxrwxrwx 1 root root 21 Nov  9 13:10 /usr/bin/awk -> /etc/alternatives/awk
$ l /etc/alternatives/awk
lrwxrwxrwx 1 root root 13 Nov  9 13:10 /etc/alternatives/awk -> /usr/bin/mawk
$ l /usr/bin/mawk 
-rwxr-xr-x 1 root root 117768 Mar 24  2014 /usr/bin/mawk
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
$
```

**Comment by itamarnet** [comment]
Esse não parece ser um caso de ``` awk ```, mas alterei a ``` zztool dump ``` para ``` zztool download ```, e ao menos no Travis funcionou.

Vide commit fd4684ca57474c56e5b5f1ac9088954e5d579366

**Comment by aureliojargas** [comment]
Aqui no Ubuntu o erro continua :(

**Comment by itamarnet** [comment]
Não sei como funciona exatamente em cada distro com relação ao diretório ``` /tmp ```:
- em alguns casos os arquivos lá são apagados a cada reinicialização
- em outros há um período pré definido no ``` cron ```
- e em outros, são mantidos indefinidamente, como é o caso do slack.
Antes que eu tente algo mais para ``` zzramones ``` e ``` zzlocale ``` pode verificar se o cache foi atualizado?

**Comment by aureliojargas** [comment]
Apagando o cache da função na mão, o teste foi.

De repente era uma boa apagar todos os caches antes de rodar a test suite.
