### ISSUE TITLE
Rodar Funções ZZ via Docker

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#264]
- [x] Escolher uma imagem base (busybox, alpine, Debian, Ubuntu)
- [x] Criar o Dockerfile 
- [ ] Testes rodando 100% nesta imagem
- [ ] :tada:

**Comment by itamarnet** [comment]
Se for para escolher uma opção o alpine parece o mais promissor como imagem base.

**Comment by aureliojargas** [comment]
Concordo!

**Comment by kl0nez** [comment]
Estou fazendo, mas o alpine tem um bucado de pacote "extra" que precisa instalar, por hora estou fazendo com o ubuntu14.04 e depois adaptamos o Dockerfile pro alpine.

Se quiserem, os primeiros testes com alpine, o funcoeszz deu um erro que eu não soube resovler:

# ./funcoeszz zzzz --bashrc
sed: no address after comma
sed: no address after comma
(script) /root/funcoeszz/funcoeszz
( pasta) /root/zz
(versão) dev (UTF-8)
( cores) sim
(   tmp) /tmp/zz
(bashrc) não instalado
( zshrc) não instalado
(  base) zzajuda, zztool, zzzz
(  site) http://funcoeszz.net

(( 0 funções disponíveis ))

**Comment by kl0nez** [comment]
$ mkdir funcoeszz
$ cd funcoeszz
~/funcoeszz& echo 'FROM ubuntu:14.04

# Definindo variáveis de ambiente

ENV ZZDIR="/root/funcoeszz/zz"
ENV ZZOFF=""
ENV ZZPATH="/root/funcoeszz/funcoeszz"


# Caso utilize proxy, descomente a linha abaixo
#ENV http_proxy="http://127.0.0.1:3128"



# Instalando o git e bc

RUN apt-get update
RUN apt-get install -y git bc

# Instalando funcoeszz

# Caso utilize proxy, descomente a linha abaixo
#RUN git config --global http.proxy $http_proxy

RUN git clone http://github.com/funcoeszz/funcoeszz.git ~/funcoeszz
RUN cd /root/funcoeszz/ && ./funcoeszz zzzz --bashrc
RUN $ZZPATH 
CMD /bin/bash ' > Dockerfile
~/funcoeszz$ sudo docker build -t fzz . && sudo docker run --name fzz -itd fzz
~/funcoeszz$ sudo docker exec -it fzz /bin/bash
root@dbc81109beaf:/# zzcalcula 10+5
15
root@dbc81109beaf:/# exit
~/funcoeszz$ sudo docker stop fzz && sudo docker rm fzz && sudo docker rmi fzz

**Comment by kl0nez** [comment]
`$ mkdir funcoeszz
$ cd funcoeszz
~/funcoeszz& echo 'FROM ubuntu:14.04

# Definindo variáveis de ambiente

ENV ZZDIR="/root/funcoeszz/zz"
ENV ZZOFF=""
ENV ZZPATH="/root/funcoeszz/funcoeszz"


# Caso utilize proxy, descomente a linha abaixo
#ENV http_proxy="http://127.0.0.1:3128"



# Instalando o git e bc

RUN apt-get update
RUN apt-get install -y git bc

# Instalando funcoeszz

# Caso utilize proxy, descomente a linha abaixo
#RUN git config --global http.proxy $http_proxy

RUN git clone http://github.com/funcoeszz/funcoeszz.git ~/funcoeszz
RUN cd /root/funcoeszz/ && ./funcoeszz zzzz --bashrc
RUN $ZZPATH 
CMD /bin/bash ' > Dockerfile
~/funcoeszz$ sudo docker build -t fzz . && sudo docker run --name fzz -itd fzz
~/funcoeszz$ sudo docker exec -it fzz /bin/bash
root@dbc81109beaf:/# zzcalcula 10+5
15
root@dbc81109beaf:/# exit
~/funcoeszz$ sudo docker stop fzz && sudo docker rm fzz && sudo docker rmi fzz`

**Comment by aureliojargas** [comment]
@kl0nez Dá uma olhada aqui https://github.com/funcoeszz/funcoeszz/issues/290 que tem o Dockerfile pra Debian, que é mais "diet" do que o Ubuntu.
