### ISSUE TITLE
Limpar cache antes de rodar a test suite

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#265]
Às vezes algum teste falha por causa de uma versão antiga (e problemática) do resultado da filtragem ainda estar lá presente na pasta `tmp` do usuário, como cache.

Apagar o cache resolve o problema (vide #255 e #258).

Pra evitar isso, o bom era mesmo que o `testador/run` já apagasse todos os caches antes de rodar os testes.

**Comment by itamarnet** [comment]
Existe a chamada na ``` zztool cache rm '*' ``` no core que pode ser invocada para limpar tudo.
Ou ``` zztool cache rm funcaozz ``` para uma limpeza específica.

**Comment by aureliojargas** [comment]
Feito!
