### ISSUE TITLE
Minimizar diferenças entre navegadores e suas versões.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#270]
Nas Funções ZZ há possibilidade de uso, quando disponível no SO, de 3 navegadores por enquanto:
 - lynx ( padrão )
 - links ( necessário em algumas funções e no uso do Travis )
 - w3m ( mais recente, mais limitado, mas promissor )

Todavia a forma como exibem as páginas (dump) tem diferenças sensíveis entre eles, e até em diferentes versões do mesmo navegador, por exemplo:
 - Interpretação de títulos: ``` <h1> ``` até ``` <h6> ```
 - Representação de linhas ``` <hr> ```
 - Exibição ou não das opções da tag ``` <select> ```

Essas questões influem diretamente no layout de exibição de resultados, e na filtragem de conteúdo.

O desafio é uniformizar ou minimizar essas diferenças.
No core já há uma forma de detectar e realizar chamadas ao 'BROWSER' padrão.
Talvez seja necessário a criação de uma sub-rotina que faça a interpretação das páginas (dump) de uma maneira mais uniforme.

Aparentemente o código fonte (source) não apresenta grandes problemas ainda.

**Comment by aureliojargas** [comment]
Para ajudar a minimizar este problema, podemos fazer uma revisão se todas as funções que hoje usam o `dump` realmente precisam dele, se de repente não poderia usar o `download` em seu lugar.

Seria bom que o uso do `dump` fosse uma exceção, quando não há outra maneira de fazer a mesma coisa, pois com esta realidade de múltiplos browsers vai ficar muito trabalhoso contornar estas diferenças e manter isso atualizado.

Temos que levar em conta que somos apenas dois, com contribuições esporádicas, e aumentar consideravelmente a carga de trabalho por causa destas incompatibilidades não é um cenário sustentável :/

**Comment by itamarnet** [comment]
Não fiz um levantamento completo, mas numa visão geral, o uso de ``` download ``` não parece trazer uma solução definitiva também, visto que baixamos uma página que eventualmente seria analisada com recurso do ``` dump ``` ou o código fonte puro com ajuda do ``` zzunescape ```, ``` zzjuntalinhas ```, ``` zztrim ```, ``` zzutf8 ``` ou ``` zzxml ``` ( ou até mais ).

O ideal mesmo seria existir uma ``` api ``` nos sites, como é o caso da ``` zzcoin ``` onde o máximo que foi necessário foi ajustar a ``` url ```, mas como isso não parece ser um opção acredito que infelizmente essa é uma árdua tarefa que deverá será feita.

Mas acho que alguns casos o ``` dump ``` possa ser substituído mesmo com ganhos por outro recurso, mas creio que na grande maioria deva permanecer como está.

Outra possibilidade é de novo focar em apenas um ``` browser ``` o que diminuiria consideravelmente o trabalho.
Todavia há esses cenários a considerar:
 - Voltar ao ``` lynx ``` e não considerar as funções que o usam no Travis.
 - Adotar apenas o ``` links ``` e retrabalhar todas que usam preferencialmente o ``` lynx ```.
 - Construir um ``` wrapper ``` básico que trate dessas diferenças, uma ``` zzbrowser ``` talvez.
 - Repensar na gama de funções, desativando aquelas que julgarmos desnecessárias ( não aprecio essa idéia ).
 - Abandonar a proposta do uso do Travis ( o que eu particularmente também não acho boa idéia ).

Em todas as opções é um trabalho considerável, mas que podemos fazer com calma.
Até acho que ao finalizar isso, podemos considerar um novo release, afinal já foram muitas mudanças, e talvez ainda venham muito mais.

**Comment by itamarnet** [comment]
No momento o problema mais gritante entre navegadores é com o ``` links ```:
 - na forma como interpreta a tag ``` <hr /> ``` na versão 2.6 que é a usada pelo Travis (na versão 2.8 o problema está resolvido)
 - e o limite máximo da largura na opção``` -width ```, que aceita até 512.

No primeiro caso o ``` links ``` (2.6) coloca 3 linhas consecutivas em branco para representar a tag ``` <hr /> ``` e para isso inclui esse código para tratar do assunto:
```
awk '
	$0  ~ /^$/  { branco++; if (branco == 3) { print "----------"; branco = 0 } }
	$0 !~ /^$/  { for (i=1;i<=branco;i++) { print "" }; print ; branco = 0 }
'
```
Onde a cada 3 linhas consecutivas em branco, substitui por um linha com '10 traços', simulando um ``` <hr /> ``` formatado pelo 'dump'.


No segundo caso, além do limite citado, o ``` links ``` quebra a linha de forma diferente do ``` lynx ``` e ``` w3m ``` mesmo em limites menores que 512. Usar o comando ``` fmt -s ``` para substituir também não funciona, pois a cada SO ou distro há um comportamento diferente, fazendo a quebra de forma distinta.
Para minimizar o problema criei a função ``` zzdividirtexto ``` para dividir as linhas pela quantidade de palavras e não por colunas, que podem ser influenciados pelos caracteres multi-bytes.
Vide commit 8cdd6ae548465ba3ddadd6db5930b792d22831c9

**Comment by itamarnet** [comment]
Outro fato constatado é a questão de tags mal formatadas, seja a tag em si ou seus atributos.

Na adaptação da ``` zzrastreamento ``` foi necessário apelar para o uso do código fonte da página ( ``` zztool source ``` ), visto que usar o ``` dump ``` há um comportamento totalmente diferente entre os navegadores ``` lynx ```, ``` links ``` e ``` w3m ```.
O motivo é essa construção: ``` <table  border cellpadding=1 hspace=10> ```, onde o atributo ``` border ``` não apresenta valor, o que faz com que o ``` links ``` e ``` w3m ``` desenhem bordas ao redor das células cada um a sua maneira, mas o ``` lynx ``` ignora e nada faz.

**Comment by itamarnet** [comment]
Seria muito estranho ao invés do ``` google.com ``` usar o ``` duckduckgo.com ``` no ``` zzgoogle ```?

Por incrível que pareça, tratar o google pelo ``` links ``` está sendo um tormento. :(

**Comment by aureliojargas** [comment]
Quanto ao bug do links 2.6 que foi resolvido na 2.8, acho melhor então não fazer nada e simplesmente esperar um tempo até que a versão nova seja a default. Que fique quebrado durante este tempo. Senão vamos tornar nosso software mais complexo por causa de bugs alheios.

Juntando isso com o problema do `-width` que você citou, mais as bordas das tabelas, mais... Isso não vai ter fim nunca. Será um pesadelo alinhar todas estas diferenças e vai tornar o nosso código desnecessariamente complexo.

Parsear o HTML também tem suas dificuldades, mas pelo menos tem a vantagem que o texto de entrada (o HTML) será sempre o mesmo independente do método de download que o usuário tenha disponível. Outra vantagem seria eliminar a dependência de browsers modo texto, pois tudo o que seria necessário é um wget/curl da vida pra baixar coisas e fazer uns POST de vez em quando.

Ou esquecer essa história de multibrowser e voltar a suportar somente um.

Sei lá, não estou curtindo a complexidade que isso tudo está gerando. Vai ficando cada vez mais difícil dar manutenção e deixar tudo funcionando. 

Idealmente, o código das funções deve ser simples, legível e bem comentado, para que seja fácil entender e ao mesmo tempo didático pra quem está aprendendo shell. Não estamos tão perto disso, mas é onde eu gostaria de chegar.

Enfim, no momento não tenho respostas :)

**Comment by itamarnet** [comment]
É uma condição complicada mesmo camarada!

A opção de download apesar de trabalhosa é viável, mas podemos nos deparar com a questão de sites feitos com IDE's que poluem o código, tratamento de tags mal formatadas, scripts embutidos e outras possibilidades inesperadas, coisas que esses navegadores tratariam de forma melhor. ( a ``` zzrastreamento ``` mostrou! )

Optar por apenas um navegador é uma das possibilidades, mas voltaríamos as questões que citei acima.

Criar um novo branch e testar as substituições do ``` dump ``` por ``` download ``` é algo que posso fazer em paralelo, e penso também em testar o uso do ``` zztestar ``` em um branch a parte também.

De toda forma hoje os testes do Linux no Travis estão passando ( https://travis-ci.org/funcoeszz/funcoeszz/builds/123492048 ), e podemos nos concentrar em ajustar os problemas que ocorrem no Ubuntu e na sequência partir para o OSX.

Let's go ahead!

**Comment by itamarnet** [comment]
Com a inclusão do ``` elinks ``` na dança e sua solução conseguimos sanar as diferenças.
Partir para o uso do ``` curl ``` é outra empreitada a ser vista na sequência.

Commit: 80137f51786c9f00e24c7115fa869b32acd0176f
