### ISSUE TITLE
Criar releases na interface do github

### ISSUE THREAD

**Issue by codexico** [funcoeszz/funcoeszz#283]
Estou escrevendo um script para baixar a última versão das funcoeszz, mas atualmente as funcoeszz tem somente tags, o que aumenta os passos e a complexidade do script.

Com releases facilitaria muito para conseguir um link para a última versão das funcoeszz, seria somente:

curl -s https://api.github.com/repos/funcoeszz/funcoeszz/releases/latest | grep tarball_url | head -n 1 | cut -d '"' -f 4
"_ficaria melhor com a zzjson #164 ;-)_"

Exemplo:
curl -s https://api.github.com/repos/codexico/dotfiles/releases/latest | grep tarball_url | head -n 1 | cut -d '"' -f 4

Para criar as releases basta ser um administrador, acessar https://github.com/funcoeszz/funcoeszz/releases e clicar em "Draf a new release".

Refs:
https://help.github.com/articles/creating-releases/
https://help.github.com/articles/about-releases/
https://developer.github.com/v3/repos/releases/#get-the-latest-release
http://stackoverflow.com/a/26738019/803864

**Comment by itamarnet** [comment]
Puxa que legal, @codexico !
Essa eu não conhecia, mas curti a ideia. É bem prático e direto.

Lembrou bem, a proposta da ``` zzjson ``` ficou esquecida por um tempo, mas sempre há oportunidades para retomadas :+1: 

Vamos aguardar e ver o que o @aureliojargas pensa a respeito.
 De minha parte a sugestão é muito bem vinda.

**Comment by aureliojargas** [comment]
Fala @codexico! 

Eu acho legal o esquema de releases do GitHub. Mas como as Funções ZZ são mais velhas que o GitHub (e que o git!), já criamos nosso próprio esquema anos atrás.

```
$ curl http://funcoeszz.net/v
15.5
```

E é isso 😄 

A URL de download é `http://funcoeszz.net/download/funcoeszz-15.5.sh`, sempre com a versão reportada pelo `/v`.

É assim que funciona o [zzzz --atualiza](https://github.com/funcoeszz/funcoeszz/blob/master/funcoeszz#L793), consultando o `/v` e baixando a versão nova do site.

**Comment by codexico** [comment]
Puxa, bem melhor com esse esquema!

O scriptzinho ficou assim: https://github.com/codexico/dotfiles/blob/master/install_funcoeszz.sh

``` shell
#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# Baixa e instala a última versão das funcoeszz
#
# Uso: ./install_funcoeszz.sh
#
# Autor: @codexico
# Desde: 2016-05-11
# Versão: 0.1.1
#
# TODO:
#     - perguntar ao user em que diretório deseja deixar o arquivo
#     - verificar se já está instalada chamar o zzzz --atualiza
# ----------------------------------------------------------------------------

echo "instalando as funcoeszz";

LAST_ZZ_VERSION=$(curl http://funcoeszz.net/v);
LAST_ZZ_URL="http://funcoeszz.net/download/funcoeszz-$LAST_ZZ_VERSION.sh";
curl -L -o funcoeszz $LAST_ZZ_URL

# seria melhor testar a existência dos arquivos ~/.bashrc e ~/.zshrc?
if [ "$SHELL" == "/bin/bash" ]; then
    echo "instalando no bash";
    chmod +x funcoeszz
    mv funcoeszz ~/bin/funcoeszz
    cd ~/bin
    ./funcoeszz zzzz --bashrc
    echo "execute 'source ~/.bashrc' ou abra outro terminal";
elif [ "$SHELL" == "/usr/bin/zsh" ]; then
    echo "instalando no zsh";
    chmod +x funcoeszz
    mv funcoeszz ~/bin/funcoeszz
    cd ~/bin
    ./funcoeszz zzzz --zshrc
    echo "execute 'source ~/.zshrc' ou abra outro terminal";
else
    echo "Não sei qual o seu shell!";
    echo "Por favor acesse o FAQ: http://funcoeszz.net/faq.html";
fi
```

Valeu @itamarnet e @aureliojargas !
