### ISSUE TITLE
Core: zztool grep_var é portável?

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#286]
A forma como a ferramenta ``` grep_var ``` verifica a presença de uma string embutida em outra é portável?
No link http://mywiki.wooledge.org/Bashism há um trecho que coloca dúvidas sobre o assunto: 
```
The behavior of the #, ##, %, and %% operators are unspecified by POSIX and the ksh88 manual when used together with the @ or * parameters. Dash applies the trimming to the flattened result. mksh/pdksh treats it as a bad expansion
```
E o trecho da ``` grep_var ```:
```
grep_var)
	# $1 está presente em $2?
	test "${2#*$1}" != "$2"
```

O que fazer? Isso interfere em algo? Ou não é necessário fazer nada, visto que não foi reportado nenhum bug sobre esse ponto?

Pessoalmente gosto da construção como está, mas isso pode ser um problema de portabilidade.

**Comment by aureliojargas** [comment]
@itamarnet a frase original está confusa, mas pelo que entendi, o artigo se refere a usar estas expansões nas variáveis especiais `$@` e `$*`, como em `${*#foo}`. Aí concordo, é realmente estranho e eu não usaria.

Mas a forma como usamos, até onde sei é portável.

**Comment by itamarnet** [comment]
@aureliojargas então esqueçamos esse assunto e deixemos como está.

Como vc bem frisou a frase está confusa, e eu interpretei errado.

Esse issue não justifica mais.

**Comment by aureliojargas** [comment]
👍
