### ISSUE TITLE
zzquebramd5 parou de funcionar?

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#29]
```
prompt$ printf 1234 | zzmd5
81dc9bdb52d04dc20036dbd8313ed055

prompt$ zzquebramd5 81dc9bdb52d04dc20036dbd8313ed055
Não foi possível descobrir a string que originou este hash.
```

Se não quebra o 1234, tem algo errado :)

**Comment by merces** [comment]
O site que era utilizado nela saiu do ar. Achei este outro, que não tem CAPTCHA e aceita GET:

```
$ wget -qO - 'http://hashtoolkit.com/reverse-hash/?hash=81dc9bdb52d04dc20036dbd8313ed055' \
> | grep -F 'span title="decrypted md5 hash"' \
> | sed 's/.*>\(.*\)<\/span>.*/\1/'
1234
```

Qual a melhor maneira de fazer um HTTP GET neste código? Posso usar o wget mesmo?

Abraço.

**Comment by marcelma** [comment]
Olá merces, 

Não sei se ainda é utlizado, mas existe a ZZWWWPOST para realizar HTTP POST, acredito que podemos criar a ZZWWWGET sendo:

ZZWWWGET="lynx -get-data -nolist -width=300 -accept_all_cookies -display_charset=UTF-8"

O que vocês acham?

**Comment by itamarnet** [comment]
Olá @merces e @marcelma ,

As variáveis ZZWWW* não são mais usadas, exceto a ``` ZZBROWSER ```, que identifica qual o navegador textual presente.

Tentando ser portável e manter uma compatibilidade, essas variáveis foram substituídas por funções na ferramenta ``` zztool ```, assim pode adaptar-se aos navegadores ``` lynx ```, ``` links ```, ``` links2 ```, ``` elinks ``` ou ``` w3m ```, que tem características comuns e outras diferentes para seus usos, o que possibilita usar o que estiver disponível para uso conforme a distro ou S.O.

Hoje há a ``` zztool post ```, ``` zztool dump ```, ``` zztool source ```, ``` zztool  list ```, ``` zztool  download ``` em substituição. 

No caso para usar ``` GET ``` é possível usar ``` zztool dump ```, ``` zztool source ``` ou ``` zztool  list ``` e fornecer a url conforme o exemplo acima:
``` http://hashtoolkit.com/reverse-hash/?hash=81dc9bdb52d04dc20036dbd8313ed055 ```.

Isso pode ser analisado em:
https://github.com/funcoeszz/funcoeszz/blob/master/funcoeszz#L344

E virtude disso a sugestão da criação da ``` ZZWWWGET ``` não se aplica, mas obrigado pela sugestão @marcelma 

@merces Estou um tanto enrolado com outros afazeres, mas vou tentar testar o mais breve possível a sugestão de site que enviou.
