### ISSUE TITLE
Travis dando timeout na zzmacvendor

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#297]
Vide https://travis-ci.org/funcoeszz/funcoeszz/jobs/130475601

Deu tanto timeout ao executar os testes, que estourou o timeout global do Travis:

```
The job exceeded the maxmimum time limit for jobs, and has been terminated.
```

Não sei se foi algo temporário, mas é bom ficarmos de olho.

**Comment by itamarnet** [comment]
Esta dando esse problema desde 15/05/2016.
Imaginei que fosse uma instabilidade momentânea no fim de semana.

**Comment by aureliojargas** [comment]
Rodando localmente os testes ela dá umas travadas também. Pode ser o site remoto que não está gostando de muitos acessos consecutivos.

De repente diminuir o número de testes. Conseguimos testar as mesmas funcionalidades com menos testes?

**Comment by itamarnet** [comment]
Boa ideia.
Vou testar com uma quantidade mais limitada de itens.

**Comment by itamarnet** [comment]
Problema solucionado com troca de site e limitando quantidade de testes
Commit caecc2ca744430aa214835e4e13ab0a1a118cd7e
