### ISSUE TITLE
Função 'zztool arquivo_existe' existe?

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#298]
Na ``` zzenviaemail ``` há esse trecho:
```
zztool arquivo_existe "${mensagem}"
```
Há ou houve essa ferramenta na ``` zztool ```.
Eu não achei!

**Comment by aureliojargas** [comment]
Verdade, só tem `arquivo_vago` e `arquivo_legivel`. Talvez usar `arquivo_legivel` nesse caso.

De qualquer forma, será que alguém usa essa função? Ela é bem antiga, precisa de um comando específico `ssmtp` e eu pelo menos, nunca a testei, não faço ideia se funciona. Vale a pena mantê-la?

**Comment by itamarnet** [comment]
Também nunca testei ou usei, apenas percebi isso ao reavaliar o uso da opção ``` -- ``` nas funções, incluindo a ``` zzenviaemail ```.
A noite testo em algumas máquinas para ver se ainda funciona. Se funcionar fica a questão em aberto para discutir, mas se não funcionar desativamos. O que acha?

**Comment by aureliojargas** [comment]
Por mim pode 🔥 
😄

**Comment by itamarnet** [comment]
@aureliojargas Eu não consegui fazer um teste satisfatório porque aparentemente há um problema com o uso da porta 25 (padrão) que o ``` ssmtp ``` usa.

Aparentemente é uma porta já muito utilizada por spammers a anos, e aparentemente em todos os micros a porta é desabilitada por padrão e pelo que parece os firewalls de modens e rotedores também não o liberam por padrão.

Até consegui liberar a porta num dos micros, mas o modem que tenho não tenho acesso a cofiguração.

Por algumas dicas que achei pela net, tentei usar a porta 465, mas aparentemente o ``` ssmtp ``` em algum ponto volta a usar a porta 25.

Efetivamente não consegui testar a ``` zzenviaemail ```, mas pelo trabalho que tive até agora e sem sucesso acho que não vale o esforço em mantê-la.

Quer providenciar o fechamento imediato ou deixamos em aberto por um tempo até que alguém vendo esse issue teste e talvez consiga faze-la funcionar? Eu pessoalmente já providenciaria o fechamento.

**Comment by aureliojargas** [comment]
Fecha, nem perca mais tempo com isso.

**Comment by itamarnet** [comment]
Função zzenviaemail desativada e ignorando zztool inexistente
