### ISSUE TITLE
Lynx ignora meu proxy CNTLM

### ISSUE THREAD

**Issue by MaikoID** [funcoeszz/funcoeszz#311]
Olá, estou com problemas de usar o funcoeszz em qualquer função que utilze a internet porque o lynx não reconhece meu ambiente:

**ENV**
```
$ env | grep proxy 
ftp_proxy=ftp://localhost:3128/
no_proxy=localhost,127.0.0.0/8,*.datacom,*.datacom.net,*.datacom.ind.br
https_proxy=https://localhost:3128/
socks_proxy=socks://localhost:3128/
all_proxy=socks://localhost:3128/
http_proxy=http://localhost:3128/
```

**wget**
```
$ wget http://www.google.com
--2016-06-07 13:24:25--  http://www.google.com/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:3128... connected.
Proxy request sent, awaiting response... 302 Moved Temporarily
Location: http://www.google.com.br/?gfe_rd=cr&ei=yPRWV_SnCOiU8QfCu6TIAQ [following]
--2016-06-07 13:24:25--  http://www.google.com.br/?gfe_rd=cr&ei=yPRWV_SnCOiU8QfCu6TIAQ
Connecting to localhost (localhost)|127.0.0.1|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.1’

    [ <=>                                                                      ] 10.989      --.-K/s   in 0,006s  

2016-06-07 13:24:25 (1,72 MB/s) - ‘index.html.1’ saved [10989]
```

**lynx**
```
lynx http://www.google.com
Alert!: Unexpected network read error; connection aborted.
```

**funcoezz**
```
maiko.costa at PEDCWB315 in ~ 
$ zzbrasileirao a
Série A

Looking up localhost:3128
Making HTTP connection to localhost:3128
Sending HTTP request.
HTTP request sent; waiting for response.
Alert!: Unexpected network read error; connection aborted.
Can't Access `http://esporte.uol.com.br/futebol/campeonatos/brasileirao/jogos'
Alert!: Unable to access document.

lynx: Can't access startfile 

 Libertadores  
 Sul-Americana 
 Rebaixamento  

```
Alguém conseguiria me responder porque o lynx está ignorando meu env ?

**Comment by itamarnet** [comment]
Caro @MaikoID não sei dizer o porque, pois há fatores como SO ou versão do ``` lynx ``` que podem influenciar. E portabilidade costuma esbarrar em questões do gênero.
Algo que suspeito apenas é o redirecionamento do ``` lynx ```, então poderia testar e mudar a variável para: ``` http_proxy=http://127.0.0.1:3128/ ```.
É um chute apenas.

**Comment by MaikoID** [comment]
Oi @itamarnet , fiz a alteração http_proxy mas não adiantou.

 O uso do cntlm é meio estranho mesmo, antes eu precisava configurar essas variáveis o conf do wget pra funcionar, depois não foi mais necessário, por acaso sabe de um arquivo similar para o lynx? Ou é possível fazer o funcoeszz usar o wget ao invés do lynx?

**Comment by itamarnet** [comment]
Temia que não funcionasse mesmo @MaikoID 

Não cheguei a ter contato com o cntlm, então não posso ajudar muito nesse caso.
O ``` lynx ``` tem um arquivo para variáveis ``` lynx.cfg ```, que na maioria da vezes está no diretório ``` /etc ``` ou na numa pasta do configuração por usuário, por exemplo ``` .config ```, e lá é possível reconfigurar essas variáveis.

Quanto a substituição do ``` lynx ```, ``` links ```, ``` elinks ``` e ``` w3m ``` é algo em curso e consideramos usar o ``` curl ```, pois tivemos problemas nas várias formas de renderização de inúmeros sites. É algo sendo tratato no issue #275

**Comment by MaikoID** [comment]
tambem não deu certo colocar no /etc/lynx-cur/lynx.cfg : 
http_proxy:http://localhost:3128/
https_proxy:https://localhost:3128/
ftp_proxy:ftp://localhost:3128/
#gopher_proxy:http://some.server.dom:port/
#news_proxy:http://some.server.dom:port/
#newspost_proxy:http://some.server.dom:port/
#newsreply_proxy:http://some.server.dom:port/
#snews_proxy:http://some.server.dom:port/
#snewspost_proxy:http://some.server.dom:port/
#snewsreply_proxy:http://some.server.dom:port/
#nntp_proxy:http://some.server.dom:port/
#wais_proxy:http://some.server.dom:port/
#finger_proxy:http://some.server.dom:port/
#cso_proxy:http://some.server.dom:port/
#no_proxy:host.domain.dom

.h2 NO_PROXY
# The no_proxy variable can be a comma-separated list of strings defining
# no-proxy zones in the DNS domain name space.  If a tail substring of the
# domain-path for a host matches one of these strings, transactions with that
# node will not be proxied.
.ex
#no_proxy:domain.path1,path2
no_proxy:localhost,127.0.0.0/8,*.datacom,*.datacom.net,*.datacom.ind.br

diaxo viu =|

**Comment by itamarnet** [comment]
Caramba hein! Esse problema está complicado

Mais três sugestões:
 - Verificou se existe na home ou na pasta ``` .config ``` ( dentro da home também) o arquivo ``` .lynxrc ``` ou ``` lynx.cfg ```. Se existir as configurações na pasta do usuário, elas são preferencias em relação ao geral que fica no ``` /etc ```.
 - Tenta usar o endereço ``` 127.0.0.1 ``` no lugar de ``` localhost ``` também nesses arquivos de configuração.
 - Teste excluir o asteriscos na configuração de no_proxy, como ``` .datacom ```.

E se ainda não der certo, tem instalado algum outro browser textual? E se tiver, o proxy funciona?
Tem o ``` curl ``` instalado? Se tiver experimenta isso e verifica se funciona contigo:
```
curl -s "http://esporte.uol.com.br/futebol/campeonatos/brasileirao/jogos/" | lynx -dump -stdin -nolist
```

**Comment by MaikoID** [comment]
opa, nem me fale =/
resultados sugestões:
- NOK
- NOK
- NOK
```
aiko.costa at PEDCWB315 in ~ 
$ curl -s "http://esporte.uol.com.br/futebol/campeonatos/brasileirao/jogos/" | lynx -dump -stdin -nolist | head

     * UOL - O melhor conteúdo
     * Assine 0800 703 3000
     * SAC

     * Bate-papo
     * E-mail
     * BOL
     * Notícias
     * Esporte
```
o curl também ta funcionando mas nada de lynx.

**Comment by itamarnet** [comment]
Caro camarada, eu lamento mas não tenho mais o que sugerir a vc.
``` wget ``` e ``` curl ``` funcionam sem problemas.
Nesse último comando com o ``` curl ``` vemos que o ``` lynx ``` funciona para renderizar e o problema está em algo liga ao proxy.
Os aquivos de configuração e variáveis de ambiente estão OK.

O caso é tão específico que sinceramente não sei o que pode ser feito para resolver o problema do ``` lynx ``` pra você.

Mas como havia dito antes, estamos trabalhando para mitigar os problemas de compatibilidade de browsers textuais, com o uso do ``` curl ```, e esse seu caso é um situação que pode se beneficiar dessa mudança.

Vale como mais uma motivação para acelerarmos o processo iniciado no issue #275

**Comment by kl0nez** [comment]
Hi galera,

como estamos testando possibilidades, por favor... faça o seguinte teste:

export http_proxy="http://127.0.0.1:3128" && lynx -reload -dump -nolist  "http://esporte.uol.com.br/futebol/campeonatos/brasileirao/jogos/" | head 

além disso, dê uma olhada nos logs do seu cntlm (como você não especificou a plataforma onde está rodando, vou usar por analogia do meu Debian, os logs ficam em /var/log/syslog) e verifique se a sua requisição ao proxy está chegando ao cntlm.

$ dpkg-query -l cntlm
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Nome                                          Versão                      Arquitectura                Descrição
+++-=============================================-===========================-===========================-===============================================================================================
ii  cntlm                                         0.92.3-1                    amd64                       Fast NTLM authentication proxy with tunneling

$ dpkg-query -l lynx
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Nome                                          Versão                      Arquitectura                Descrição
+++-=============================================-===========================-===========================-===============================================================================================
ii  lynx                                          2.8.9dev1-2+deb8u1          all                         Text-mode WWW Browser (transitional package)

**Comment by MaikoID** [comment]
@itamarnet é bem específico mesmo, agradeço a ajuda. Acho que nem se seria uma boa colocar lá essa issue com motivação, bom pelo menos seria um usuário a mais haha.

@kl0nez opa, segue:
```
maiko.costa at PEDCWB315 in ~ 
$ export http_proxy="http://127.0.0.1:3128" && lynx -reload -dump -nolist "http://esporte.uol.com.br/futebol/campeonatos/brasileirao/jogos/" | head

Looking up 127.0.0.1:3128
Making HTTP connection to 127.0.0.1:3128
Sending HTTP request.
HTTP request sent; waiting for response.
Alert!: Unexpected network read error; connection aborted.
Can't Access `http://esporte.uol.com.br/futebol/campeonatos/brasileirao/jogos/'
Alert!: Unable to access document.

lynx: Can't access startfile 
```

Minha distro é o Ubuntu 14.04
maiko.costa at PEDCWB315 in ~ 
```
$ tail /var/log/syslog
Jun  8 11:29:46 PEDCWB315 cntlm[1247]: 127.0.0.1 GET http://esporte.uol.com.br/futebol/campeonatos/brasileirao/jogos/
Jun  8 11:29:46 PEDCWB315 cntlm[1247]: Proxy returning invalid challenge!
```

dei uma googlada neste erro mas nenhuma pareceu ser meu ambiente acho que vou disparar o wireshark aqui e verificar melhor o que diabo ta acontecendo.

**Comment by kl0nez** [comment]
@MaikoID opa...

Então, o problema *parece* não estar no lynx ao acessar o seu proxy, mas sim no seu proxy ao atender a requisição feita pelo lynx. Creio que esteja falhando o processo de autenticação NTLM que você está usando no seu cntlm, ou o cntlm está recebendo um deny ao acessar este conteúdo.

A partir destas hipóteses, vamos tentar 2 testes.

1 - Mudar o conteúdo que está sendo requisitado pelo lynx, por exemplo:

$ export http_proxy="http://127.0.0.1:3128" && lynx -reload -dump -nolist "http://www.google.com" | head


2 - Testar o acesso ao proxy com outro cliente:

$ curl --proxy http://127.0.0.1:3128 http://www.google.com

Vamos ver onde chegaremos.. :)

Um outro teste é validar se o seu cntlm está conseguindo autenticar corretamente...

$ cntlm -u usuario@dominio.com -H -I -v

E verificar se consegue se autenticar

$ cntlm -u usuario@dominio.com -H -I -v -M http://www.google.com

Para validar se o seu cntlm consegue atender a solicitação.

por enquanto... vamo que vamo.. :)

**Comment by MaikoID** [comment]
@kl0nez 
1: OK na primeira vez =|
```
maiko.costa at PEDCWB315 in ~ 
$ export http_proxy="http://127.0.0.1:3128" && lynx -reload -dump -nolist "http://www.google.com" | head

   Pesquisa Imagens Maps Play YouTube Notícias Gmail Drive Mais »
   Histórico da Web | Configurações | Fazer login

   Google

     _______________________________________________________
   Pesquisa Google  Estou com sorte    Pesquisa avançada
      Ferramentas de idioma

```
```
maiko.costa at PEDCWB315 in ~ 
$ export http_proxy="http://127.0.0.1:3128" && lynx -reload -dump -nolist "http://www.google.com" | head

Looking up 127.0.0.1:3128
Making HTTP connection to 127.0.0.1:3128
Sending HTTP request.
HTTP request sent; waiting for response.
Alert!: Unexpected network read error; connection aborted.
Can't Access `http://www.google.com/'
Alert!: Unable to access document.

lynx: Can't access startfile 
```

2: OK
```
maiko.costa at PEDCWB315 in ~ 
$ curl --proxy http://127.0.0.1:3128 http://www.google.com   
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com.br/?gfe_rd=cr&amp;ei=nkVYV_iFAaLL8gejg6moCQ">here</A>.
</BODY></HTML>

maiko.costa at PEDCWB315 in ~ 
$ cntlm -u maiko.costa@datacom -H -I -v                            
section: global, Username = 'maiko.costa'
section: global, Domain = 'datacom'
section: global, Auth = 'NTLMv2'
section: global, PassNTLMv2 = 'ED99CD4D6750B69C62A4459F3B85C743'
section: global, Proxy = 'proxy-cwb.datacom.net:3128'
section: global, NoProxy = 'localhost, 127.0.0.*, 10.*, 192.168.*, *.datacom, *.datacom.net, *.datacom.ind.br, metroautomatedtests.*'
section: global, Listen = '3128'
section: global, Gateway = 'yes'
Default config file opened successfully
cntlm: Cannot bind port 3128: Address already in use!
Adding no-proxy for: 'localhost'
Adding no-proxy for: '127.0.0.*'
Adding no-proxy for: '10.*'
Adding no-proxy for: '192.168.*'
Adding no-proxy for: '*.datacom'
Adding no-proxy for: '*.datacom.net'
Adding no-proxy for: '*.datacom.ind.br'
Adding no-proxy for: 'metroautomatedtests.*'
cntlm: Workstation name used: PEDCWB315
cntlm: Using following NTLM hashes: NTLMv2(1) NT(0) LM(0)
Password: 
PassLM          2EB2C8B1BB0C994855487C53D18E69CA
PassNT          BC2FC1BC9F71FA10A8E8A60D158E0AFA
PassNTLMv2      ED99CD4D6750B69C62A4459F3B85C743    # Only for user 'maiko.costa', domain 'datacom'
cntlm: Terminating with 0 active threads
```
```
maiko.costa at PEDCWB315 in ~ 
$ cntlm -u maiko.costa@datacom -H  -v -M http://www.google.com   
section: global, Username = 'maiko.costa'
section: global, Domain = 'datacom'
section: global, Auth = 'NTLMv2'
section: global, PassNTLMv2 = 'ED99CD4D6750B69C62A4459F3B85C743'
section: global, Proxy = 'proxy-cwb.datacom.net:3128'
section: global, NoProxy = 'localhost, 127.0.0.*, 10.*, 192.168.*, *.datacom, *.datacom.net, *.datacom.ind.br, metroautomatedtests.*'
section: global, Listen = '3128'
section: global, Gateway = 'yes'
Default config file opened successfully
cntlm: Cannot bind port 3128: Address already in use!
Adding no-proxy for: 'localhost'
Adding no-proxy for: '127.0.0.*'
Adding no-proxy for: '10.*'
Adding no-proxy for: '192.168.*'
Adding no-proxy for: '*.datacom'
Adding no-proxy for: '*.datacom.net'
Adding no-proxy for: '*.datacom.ind.br'
Adding no-proxy for: 'metroautomatedtests.*'
cntlm: Workstation name used: PEDCWB315
Password: 
cntlm: Using proxy proxy-cwb.datacom.net:3128
cntlm: Resolving proxy proxy-cwb.datacom.net...
Config profile  1/4... Resolve proxy-cwb.datacom.net:
  -> 10.1.1.100
NTLM Request:
	   Domain: datacom
	 Hostname: PEDCWB315
	    Flags: 0xA208B205

Sending PROXY auth request...
Proxy-Connection               => keep-alive
Host                           => www.google.com
Proxy-Authorization            => NTLM TlRMTVNTUAABAAAABbIIogcABwApAAAACQAJACAAAABQRURDV0IzMTVEQVRBQ09N
Content-Length                 => 0

Reading PROXY auth response...
HEAD: HTTP/1.0 407 Proxy Authentication Required
Server                         => squid
Date                           => Wed, 08 Jun 2016 16:30:21 GMT
Content-Type                   => text/html
Content-Length                 => 1298
Expires                        => Wed, 08 Jun 2016 16:30:21 GMT
X-Squid-Error                  => ERR_CACHE_ACCESS_DENIED 0
Proxy-Authenticate             => NTLM TlRMTVNTUAACAAAADgAOADgAAAAFgomiDIt8llXwlIUAAAAAAAAAAHQAdABGAAAABgEAAAAAAA9EAEEAVABBAEMATwBNAAIADgBEAEEAVABBAEMATwBNAAEAEgBQAFIATwBYAFkALQBDAFcAQgAEABYAZABhAHQAYQBjAG8AbQAuAG4AZQB0AAMAKgBwAHIAbwB4AHkALQBjAHcAYgAuAGQAYQB0AGEAYwBvAG0ALgBuAGUAdAAAAAAA
X-Cache                        => MISS from proxy-cwb.datacom.net
X-Cache-Lookup                 => NONE from proxy-cwb.datacom.net:3128
Via                            => 1.0 proxy-cwb.datacom.net:3128 (squid)
Proxy-Connection               => keep-alive
Discarding 1298 bytes.
NTLM Challenge:
	Challenge: 0C8B7C9655F09485 (len: 186)
	    Flags: 0xA2898205
	NT domain: DATACOM
	   Server: PROXY-CWB
	   Domain: datacom.net
	     FQDN: proxy-cwb.datacom.net
	    TBofs: 70
	    TBlen: 116
	    ttype: 0
NTLMv2:
	    Nonce: C6237B3267458B6B
	Timestamp: 131098771220000000
NTLM Response:
	 Hostname: 'PEDCWB315'
	   Domain: 'datacom'
	 Username: 'maiko.costa'
	 Response: '911BA19D2B5B5E61AE05548FE7796B46010100000000000000ED0E49A3C1D101C6237B3267458B6B0000000002000E00440041005400410043004F004D0001001200500052004F00580059002D0043005700420004001600640061007400610063006F006D002E006E006500740003002A00700072006F00780079002D006300770062002E00640061007400610063006F006D002E006E00650074000000000000000000' (164)
	 Response: 'B362599381077DAE46FCF254D3EAF33EC6237B3267458B6B' (24)
HEAD: HTTP/1.0 302 Moved Temporarily
OK (HTTP code: 302)
----------------------------[ Profile  0 ]------
Auth            NTLMv2
PassNTLMv2      ED99CD4D6750B69C62A4459F3B85C743
------------------------------------------------
cntlm: Terminating with 0 active threads
```

é realmente meu cntlm ta muito bixado, parece que só funciona com que pega do /etc/cntlm.conf

**Comment by kl0nez** [comment]
@MaikoID opa...

Realmente, tem algo muito estranho entre a relação do cntlm e o seu proxy.

Pelo que eu pude perceber o seu proxy é um squid, ele só oferece o método de autenticação por NTLM ?

Outra coisa de extrema importância, vocẽ divulgou o hash da sua senha NTLM, o que implica que a sua senha foi comprometida, sugiro que substitua o mais rápido possível, e se estiver utilizando esta senha em algum outro lugar, altere lá também.

Sobre os seus testes, o mais estranho que o seu proxy atendeu a primeira requisição, mas a segunda não. Se tiver acesso, tente verificar nos logs do squid, o que está acontecendo para falharem algumas requisições.

Enfim, acho que pelo menos identificamos o ponto que está falhando. Eu apontaria o dedo para o "proxy-cwb.datacom.net:3128 (squid)" esse aí é quem deve receber as atenções.

**Comment by itamarnet** [comment]
Pelos relatos anteriores não é algo a ser feito nas FuncoesZZ, então fecho esse issue.
