### ISSUE TITLE
cpf e cnpj sem formatação

### ISSUE THREAD

**Issue by alternatribe** [funcoeszz/funcoeszz#324]
sugestão de alteração para opção que gera cpf/cnpj sem formatação

**Comment by itamarnet** [comment]
@alternatribe 
Tanto a zzcpf como a zzcnpj fornecem um número aleatório se forem invocados sem argumento.

Ao se fornecer um número ou ele é formatado apenas ou conferido seus dígitos verificadores, e retornam a mensagem que é "válido" ou "inválido".

Para sua sugestão poderia usar o comando assim:
``` zzcpf | tr -d '.-' ``` ou ``` zzcnpj | tr -d '/.-' ```

Acha realmente que precisa de uma opção para emitir um exemplo sem formatação?

**Comment by aureliojargas** [comment]
Já tem a opção `-f` pra formatar (inserir a pontuação). De repente faz sentido adicionar a opção pra fazer o contrário também. 

Só não sei qual seria uma letra boa pra essa opção. Talvez `-F` pra ter o sentido de inversão.

**Comment by robertopc** [comment]
Vim abrir uma issue pra sugerir o mesmo.
Por mais que seja simples a solução, seria interessante ter nativo.

**Comment by itamarnet** [comment]
@alternatribe @alexandre-mbm @robertopc vou aguardar a conclusão da PR #430 até o final dessa semana, senão darei continuidade.
Agregando a isso além da opção ``` -f ``` que já existe, adotar a opção ``` -F ``` para o uso sugerido nesse issue, a opção ``` -e ``` da PR citada e agrego a opção ``` -q ``` que não retornaria mensagem nenhuma, apenas deixando que se fizesse análise do código de retorno.

**Comment by itamarnet** [comment]
Opções ``` -F ``` e ``` -q ``` inclusas conforme descrito nos comentários anteriores.
