### ISSUE TITLE
zztempo não responde.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#333]
O site consultado pela ``` zztempo ``` não responde mais, mostrando no título "Service Removed" e em seu corpo "This Service is no longer available".

Caso não seja restabelecido o serviço ou se obtenha uma alternativa a função tende a ser desativada.

Como uma alternativa provisória recomendo o comando
```
 $ curl wttr.in

 $ curl wttr.in/:help    # Para ajuda
 $ curl wttr.in/jundiai  # Exemplo para cidade de Jundiaí
```

**Comment by itamarnet** [comment]
Função desativada, ver PR #334

**Comment by martinbra** [comment]
Haveria algum problemas se fizessemos zztempo apenas um alias do "curl wttr.in"? 
Exemplo: "zztempo cwb" chamaria "curl wttr.in/cwb".

**Comment by itamarnet** [comment]
@martinbra Não vejo mal nenhum em tentar fazer algo nesse sentido.
Gostaria de tentar elaborar?
Seria uma contribuição muito bem vinda.
