### ISSUE TITLE
zzbrasileirao

### ISSUE THREAD

**Issue by perlporter** [funcoeszz/funcoeszz#341]
uname -sv
Darwin Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64

zzbrasileirao a
Série A
sed: 1: "/^ *Classificacao *PG/, ...": extra characters at the end of p command

**Comment by itamarnet** [comment]
Wendell

Estou supondo que o seu sistema é ou um Mac ou FreeBSD, mas emulando aqui esses sistemas tudo funcionou ainda, e por isso não consegui reproduzir o erro que apontou.

Na linha 118 do arquivo zzbrasileirao.sh está assim: 
```
sed -n "/^ *Classificação *PG/,/20°/{ s/^/_/; s/°/./; p; }" |
```
Mude para:
```
sed -n "/^ *Classificação *PG/,/20°/{
    s/^/_/
    s/°/./
    p
}" |
```

Desconfio que a construção ``` in-line ``` do comando não seja suportada na sua versão do sed. Se for isso, há muita coisa a mudar não só na ``` zzbrasileirao ```, mas em várias outras funções.

Agradeço se puder fazer esse teste e nos dar esse feedback.

**Comment by perlporter** [comment]
Oba, obrigado pela rápida resposta...

Estou usando o macOS Sierra, e com a alteração que você sugeriu, funcionou perfeitamente ;)

Retirado do man:
HISTORY
     A sed command, written by L. E. McMahon, appeared in Version 7 AT&T UNIX.

AUTHORS
     Diomidis D. Spinellis <dds@FreeBSD.org>

**Comment by itamarnet** [comment]
Eu que agradeço pelo feedback.

Mas estava torcendo para que não funcionasse, pois isso mostra haver mais uma gama de situações a prever no quesito compatibilidade.
Provavelmente haverá outros erros do mesmo gênero na própria função ``` zzbrasileirao ``` como em outras funções.
Não sei se chegou a ver, mas no Wiki temos uma página que trata de questões de portabilidade, onde tentamos deixar o mais amplo possível a aceitação e funcionalidade das Funçoes ZZ, a saber:
https://github.com/funcoeszz/funcoeszz/wiki/Portabilidade

**Comment by perlporter** [comment]
Itamar, pode fechar os dois issues... Acertei o locale aqui e tudo se resolveu :-)

Que bom ...

**Comment by itamarnet** [comment]
Maravilha Wendell

Apenas vou fazer alguns testes adicionais, o que você reportou e a boa lembrança do locale feita pelo @aureliojargas deu uma nova ótica ao assunto.
Basicamente testamos UTF-8 e ISO-8859-1 que engloba quase que a totalidade das opções, mas podemos ter problemas em situações não previstas como foi esse caso.

Obrigado pelo retorno.

**Comment by aureliojargas** [comment]
Quanto ao sed, nesse caso específico, não era pra ter diferença entre ser inline ou multiline.

O problema é quando o inline esquece do ponto-e-vírgula antes da `}`, o que não era o caso aqui. 

Talvez a mudança para multiline coincidiu com a mudança do locale (ou testou no Terminal, que estava com o locale certo), e daí por isso pareceu que foi a mudança no sed que resolveu?
