### ISSUE TITLE
zzcoin

### ISSUE THREAD

**Issue by perlporter** [funcoeszz/funcoeszz#342]
OS: macOS sierra

Mais uma "incompatibilidade" encontrada:
sed: 2: "
                y/àáâãäåèéê ...": transform strings are not the same length

**Comment by itamarnet** [comment]
Caro Wendell

O erro que aponta na verdade está na função ``` zzsemacento ```, que é um das funções listadas como requisito da ``` zzcoin ```.

O que me preocupa no momento é que esse erro apontado agora, assim como na ``` zzbrasileirao ```, sejam novas situações devido ao seu SO, que se não me engano é a versão mais recente do Mac e que foi lançada a poucos dias.

O @aureliojargas, que é autor das FunçoesZZ, também usa Mac mas acredito que não seja ainda essa versão, ou ao menos não a tenha atualizado até o último uso que tenha feito das funções.

Nesse cenário parece que algo que funcionava, deixou de funcionar no Mac devido a essa atualização.

Ainda não fiz qualquer alteração na ``` zzbrasileirao ```, pois aquele comportamento apontava a mudanças bem maiores que não se limitavam só a aquela função em si.

E esse novo erro é mais inesperado ainda, visto que é, ou deveria ser, uma troca simples.

Poderia fazer outros 2 testes, visto que esse erro eu também não consegui reproduzir?
 1 - Testar esse comando:
```
 echo 'àáâãäåèéêëìíîïòóôõöùúûü' | sed 'y/àáâãäåèéêëìíîïòóôõöùúûü/aaaaaaeeeeiiiiooooouuuu/'
```

2 - Testar esse outro comando:
```
 zzsemacento 'àáâãäåèéêëìíîïòóôõöùúûü
```

**Comment by perlporter** [comment]
Segue teste solicitado..

 
echo 'àáâãäåèéêëìíîïòóôõöùúûü' | sed 'y/àáâãäåèéêëìíîïòóôõöùúûü/aaaaaaeeeeiiiiooooouuuu/'
sed: 1: "y/àáâãäåèéêë...": transform strings are not the same length
 zzsemacento 'àáâãäåèéêëìíîïòóôõöùúûü'
sed: 2: "
                y/àáâãäåèéê ...": transform strings are not the same length

**Comment by aureliojargas** [comment]
Ainda não atualizei pro Sierra, não tenho como testar. Isso tem a ver com o locale e codificação dos caracteres. @perlporter tua máquina tá configurada pra português?

Eu costumava ver esse tipo de erro no `tr` do Mac, mas o `sed` era imune. Só o que falta é isso ter mudado : disappointed:

**Comment by perlporter** [comment]
Ola Aurelio,  tudo bem ?

Olhando aqui na minha máquina, fiz um teste interessante:

Utilizo o iTerm2 e nele o zzcoin apresentou este problema relatado acima. Ao testar no Terminal do sistema, rodou sem problema.

Mais informações (locale):

Terminal
LANG=
LC_COLLATE="C"
**LC_CTYPE="UTF-8"**
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

iTerm2
LANG=
LC_COLLATE="C"
**LC_CTYPE="C"**
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

Fiz a configuração e acertou tudo :-)

Valeu ;-)
