### ISSUE TITLE
zzlinux não passa nos testes do Travis no linux.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#355]
Esse problema está acontecendo apenas no desenrolar dos testes dentro do ambiente do Travis no Linux, que é Ubuntu 12.04 LTS.
Testes feitos em Ubuntu, Slack, Manjaro, Debian, Open Suse atualizados em máquinas reais ou virtualizadas não apresentam a falha relatada.
Aparentemente o problema parece estar relacionado com a troca do certificado usado pelo site kernel.org, que agora usa o oferecido pela mesma empresa que oferece hospedagem: gandi.net
Não vejo como solucionar o problema por se tratar de algo ligado a infra tanto do site consultado, quanto o ambiente usado no Travis para linux.
Já foi tentado o uso do wget, lynx, links, elinks além do curl que a função já usa, mas não há um retorno de informação.
Esse issue é mais informativo, e para aguardar uma possível atualização da versão linux usado no Travis, ou a troca da autoridade certificadora usada pelo kernel.org.

**Comment by aureliojargas** [comment]
Mmmm, que chato. Aí acho que era bom desativar estes testes pro ora lá no Travis, pra que ele possa passar 100%. (fiz no #356)

É que se acostumar com ele quebrado, aí perde o sentido de usar.

**Comment by itamarnet** [comment]
Por tocar nesse assunto existe um outro ponto que me preocupa no Travis e não sei se vc tem acompanhado ou visto isso nessas últimas semanas.

Mas inúmeras vezes tem ocorrido problemas nos testes com OS X, onde invariavelmente o sistema parece ficar saturado. Normalmente quando ultrapassa 110 jobs, há perda de perfomance ou simplesmente não inicia, encerrando o teste por timeout.

Se consultar em https://www.traviscistatus.com/ vai ver um histórico constante de indisponibilidade para OS X.

Nos últimos PR que fiz, precisei esperar o sistema restabelecer para restartar os jobs ou builds e ver se os testes passaram na alteração solicitada.

Acho a ferramenta fantástica para debugar e validar as alterações, mas essa situação me preocupa.

**Comment by aureliojargas** [comment]
De repente desativar os testes no OS X e deixar só no Linux. Se no futuro o Travis voltar a ficar bom no OS X, reativamos.

**Comment by itamarnet** [comment]
Eu sinceramente lamentaria muito que essa decisão fosse tomada, mas nos 20 dias que antecedem essa postagem foram 18 ocorrências, e a grande maioria com uma duração considerável.

Talvez seja bom considerar isso também em outros projetos que também usam CI, vi recentemente também precisou desabilitar testes do OS X no clitest.

**Comment by aureliojargas** [comment]
Não é uma decisão permanente, podemos desligar agora e tentar ligar de novo daqui algumas semanas.

**Comment by itamarnet** [comment]
Desligar os testes no OS X no momento acho inevitável mesmo, mas temo pelo histórico recente do Travis que essa instabilidade seja permanent. Aparentemente a estrutura que tem para esse SO deve ter limites, sejam os motivos de fundo técnicos ou burocráticos... :(

**Comment by aureliojargas** [comment]
OK, podemos fechar essa issue agora
