### ISSUE TITLE
Resolver o impasse das funções zz*2

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#36]
prompt$ ls zz*2.sh
zzdicportugues2.sh zzloteria2.sh

Avaliar o que fazer com estas versões alternativas. Torná-las oficiais, fazer um merge de algumas partes ou descartar de vez.

**Comment by aureliojargas** [comment]
@itamarnet na zzdicportugues2 está faltando testes com verbos e as sub-opções de conjugação, você pode colocá-los? Quando o testador dela estiver completo e passando 100% aqui e aí, podemos tornar esta a função oficial.

**Comment by itamarnet** [comment]
Putz, tem razão!
Me foquei tanto no problema das palavras com acento que a zzdicportugues não cobria que nem pensei nisso.
Pode deixar, vou ampliar a gama de teste.

**Comment by itamarnet** [comment]
Novos testes cobrindo definição e conjugação verbal.
commit 8b17db2733d66e7c16f78ce38cfe0913fec6caa7

**Comment by aureliojargas** [comment]
OK! zzdicportugues2 virou a oficial nos seguintes commits: 2bf6dd728f1a78a02299f224ee8bf764d0b71a35 e 6a59f0a1a78e7bc361c9a6d89c32163bd93cf882.

Parabéns pelo trabalho @itamarnet!

**Comment by aureliojargas** [comment]
Sobre `zzloteria` e `zzloteria2`, ainda temos problemas em ambas. Há mais detalhes no issue #159.

**Comment by aureliojargas** [comment]
Parabéns mais uma vez pelo seu excelente trabalho @itamarnet, a sua `zzloteria` agora é a oficial. :tada: 

Agora, 2 anos depois, podemos finalmente fechar esse issue :)

**Comment by itamarnet** [comment]
Meu não meu amigo, nosso trabalho!
Demorou mas chegou...
Retroceder Nunca, Render-se Jamais :+1:

**Comment by aureliojargas** [comment]
:facepunch:
