### ISSUE TITLE
zztimer: --teste ser a saída padrão

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#361]
Muito legal essa `zztimer`! Testei todas as opções aqui e fiquei impressionado, mandou muito bem @itamarnet! :clap::clap::clap:

O único ajuste que eu faria, era a saída padrão (quando nenhuma opção for usada) ser a saída que atualmente está na opção `--teste`: um número por linha, sem `tput`.

```console
$ zztimer 5
00:00:05
00:00:04
00:00:03
00:00:02
00:00:01
00:00:00
$
```

Isso se encaixa melhor na filosofia das ZZ, de digitar um comando e ter o resultado no STDOUT (sem firula 😄 ). Eu me incomodo com comandos que bagunçam meu terminal.

Além disso, limpar todo o terminal e aparecer o número sozinho, pequeno, lá no topo, pra mim é menos legível do que a saída da `--teste`.

@itamarnet o que você acha?

**Comment by aureliojargas** [comment]
Pensando mais um pouco, ao usar o formato grande (`-n`) ele podia vir sempre centralizado, já que vai limpar a tela toda, melhor que fique no meio. Podia eliminar a opção `--centro` e tornar ela padrão.

**Comment by itamarnet** [comment]
Essa foi outra possibilidade que não havia imaginado, eu apenas adicionei a opção ``` --teste ``` para viabilizar um testador, por isso o nome.
O formato grande confesso que foi uma frescura minha, coisa de quem depende de óculos e precisar ver os números de longe da tela. Mas eu curti a sugestão, vou experimentar :+1:

**Comment by itamarnet** [comment]
Sugestões atendidas na PR #416
