### ISSUE TITLE
zzrandbackground é muito específica (não portável)

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#363]
Só funciona no Gnome, no Linux. Não tem utilidade no Unix modo texto, Mac, Cygwin, Windows 10...

Citando nosso [guia de portabilidade](https://github.com/funcoeszz/funcoeszz/wiki/Portabilidade):

> Evite ao máximo usar comandos específicos de um sistema operacional. Lembre-se que as funções rodam em Linux, Unix, Mac e até no Windows (via Cygwin).

Voto por aposentar esta função.

**Comment by itamarnet** [comment]
Tem razão, apoio a decisão.
