### ISSUE TITLE
Funções não atendem sinal de interrupção (Ctrl-C) no Docker

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#374]
As funções ``` zziostat ``` e ``` zzss ``` não respondem ao comando de interrupção, e ficam rodando indefinidamente travando o terminal.

A única forma de parar as funções foi usando o comando ``` kill ``` do docker.

Na função ``` zziostat ``` a inclusão de um parâmetro para quantidade de estatísticas pode resolver, que poderia ter um valor padrão por exemplo de 10 medições, e podendo ser alterado com uma opção ``` -n ```.
Já na função ``` zzss ``` não vislumbro uma solução.

Obs.: A função ``` zziostat ``` para funcionar foi necessário a inclusão do pacote ``` sysstat ``` no Dockerfile para instalação.

**Comment by aureliojargas** [comment]
Creio que esse comportamento não seja específico destas funções, mas do Docker em si:

```console
$ docker run --rm funcoeszz/zz timer --teste 10
awk: line 6: syntax error at or near *
00:00:10
^C00:00:09
00:00:08
^C00:00:07
^C00:00:06
^C00:00:05
^C^C^C00:00:04
^C^C^C^C00:00:03
^C^C^C^C^C^C^C00:00:02
^C^C00:00:01
00:00:00
$
```

**Comment by itamarnet** [comment]
Não lembro de ter lido nada a respeito no Docker na qual possa habilitar o uso de sinais de interrupção.
Ao menos no material que li, mas confesso que não vi toda a documentação como se deve, apenas o básico do funcionamento e do Dockerfile. Nem sobre o Compose li nada mais a fundo :(

Alguma idéia sobre como solucionar?

**Comment by aureliojargas** [comment]
Eu acho que pode ter a ver com o problema descrito aqui: https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html

**Comment by itamarnet** [comment]
Sim esse é o problema, e pelo visto oferece a solução também.
É só incluir a instalação do pacote ``` dumb-init ``` dentro do arquivo Dockerfile e problema resolvido!

**Comment by aureliojargas** [comment]
Massa, funciona mesmo:

```console
$ docker run --rm funcoeszz timer --teste 20
awk: line 6: syntax error at or near *
00:00:20
00:00:19
^C$
```

Por enquanto vou deixar de lado essa alteração até que o testador rode 100% no contêiner. Só pra garantir que possíveis bugs que apareçam não são relacionados ao uso deste componente.
