### ISSUE TITLE
Docker: zztimer com erro no awk

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#387]
```console
$ docker run --rm funcoeszz/zz timer --teste 3
awk: line 6: syntax error at or near *
00:00:03
00:00:02
00:00:01
00:00:00
$
```

A linha que ele não gostou tem um operador `**` que parece ser incompatível com essa versão do awk. 

```diff
-                       print (hora*(60**2)) + (min*60) + seg
+                       print (hora*(60*2)) + (min*60) + seg
```

Troquei pra um `*` só e aparentemente funcionou.

O `**` era typo ou é realmente necessário?

**Comment by itamarnet** [comment]
Realmente é necessário, mas o ``` mawk ``` ( o dash do awk ) não suporta a sintaxe ``` ** ``` para indicar potência, mas sim ``` ^ ```.
Todavia não precisa dessa conta, pode-se colocar o valor resultante direto: ``` 3600 ```.
Vou fazer essa troca.

**Comment by aureliojargas** [comment]
Realmente, tinha o `60*60` também. Você escolheu a maneira mais luxuosa, que só os awk ricos possuem :smile:

**Comment by aureliojargas** [comment]
Confirmo que resolveu 🎉 

```
$ docker run --rm -v $PWD:/app/ funcoeszz timer --teste 3
00:00:03
00:00:02
00:00:01
00:00:00
$
```
