### ISSUE TITLE
export ZZBROWSER não é respeitado

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#389]
Isso não deveria funcionar?

```console
$ ZZBROWSER=links ./funcoeszz zzzz | grep browser
(browser) lynx
$ export ZZBROWSER=links; ./funcoeszz zzzz | grep browser
(browser) lynx
$
```

**Comment by itamarnet** [comment]
Dentro do core há essa linhas:
```
ZZBROWSER_ALL='lynx links links2 elinks w3m'  # Todos os navegadores possíveis
```
```
# Descobre qual o navegador em modo texto está disponível no sistema
for ZZBROWSER in $ZZBROWSER_ALL
do
	type "$ZZBROWSER" >/dev/null 2>&1 && break
done
export ZZBROWSER
```

Dessa forma respeita a sequência de browser listada, adotando a primeira válida dentro da variável ``` ZZBROWSER_ALL ```

É uma consequência/percursora da criação da ``` zztool post | dump | list | source ```

**Comment by aureliojargas** [comment]
Mas além desse comportamento atual, não deveríamos honrar esse caso onde o usuário já escolheu seu browser? Com as outras variáveis de ambiente das ZZ funciona assim, se já tiver setado ele não mexe.

**Comment by itamarnet** [comment]
Tem total razão nisso e esse foi um lapso que passou desapercebido até agora.
O que eu sugiro é fazer essa troca no primeiro trecho citado acima:
```
ZZBROWSER_ALL="${ZZBROWSER:-lynx links links2 elinks w3}"
```

**Comment by aureliojargas** [comment]
Acabei fazendo de outro jeito, pra eliminar a necessidade da `$ZZBROWSER_ALL`
