### ISSUE TITLE
zzhora: -r com resultado negativo, está 1 dia atrasado

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#39]
```
$ zzhora -r 12:00 - 13:00
23:00 (hoje)

$ zzhora -r 12:00 - 37:00
23:00 (ontem)
```

Deveria ser **ontem** e **anteontem**, respectivamente.

**Comment by itamarnet** [comment]
O conceito anterior estabelecia a nomenclatura relativa baseada no dias.
O ajuste feito na exibição, considera a participação dos valores das horas ou minutos adicionais no resultados negativos.
E para manter coerência o uso da referência relativa (-r) com apenas um argumento usa como base para cálculo 00:00h do dia corrente, tanto para valores positivos como negativos.
Assim as alterações feitas também atingem o testador, trocando a antiga abordagem.
Vide no commit 473efe2082c7ed3825de3bcbe80e0d5c0e85c6cd

**Comment by aureliojargas** [comment]
Olhando o commit com as alterações, vejo que somente uma linha do testador foi alterada (fora a que foi descomentada). Pelo teu comentário aqui, achei que mais testes do `-r` seriam afetados. É isso mesmo ou está faltando mais testes para demonstrar o que você explicou?

**Comment by itamarnet** [comment]
Não acho que esteja faltando testes, os que você havia providenciado já cobre todas as possibilidades ao meu ver.

E a alteração feita é apenas para o caso apontado mesmo.

Como comentei é apenas conceitual, no que se refere ao horário base usado na referência para cálculo.
