### ISSUE TITLE
zzgoogle: acesso negado :(

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#390]
Executei `funcoeszz zzgoogle -n 1 ab-rephone github` e não retornou nada. Mudei pra ele guardar no `/tmp` uma cópia do HTML de retorno, antes dos filtros.

Apareceu isso:

> Error 403 (Forbidden)!!1
>
> Your client does not have permission to get URL <code>/search?q=ab-rephone+github&amp;num=1&amp;ie=UTF-8&amp;oe=UTF-8&amp;hl=pt-BR</code> from this server.  (Client IP address: 179.155.XXX.XXX)
>
> Please see Google's Terms of Service posted at http://www.google.com/terms_of_service.html

@itamarnet pra ti funciona esta função? Pelo que entendi bloquearam o lynx ou o meu IP, ou ambos.

**Comment by itamarnet** [comment]
@aureliojargas Esse problema já é antigo comigo, em casa eu não consigo usar mais a ``` zzgoogle ``` a muito tempo.

Aparentemente criam um tipo de bloqueio, que no começo era intermitente, mas depois ficou permanente.
Se acaso mudasse fisicamente de lugar, a função voltava a funcionar, então deve haver o componente IP nesse bloqueio.

Havia ou há ainda um problema com o uso de outros browsers, então já faz um tempo que inclui a opção de usar outros navegadores utilizando o https://duckduckgo.com no lugar do google. 
commit: 4284e52104bc7af128b683c9def45d519088bf48

**Comment by aureliojargas** [comment]
Então de repente aposentar ela e fazer a zzduckduckgo ou zzddg oi zzduck. Por a gente rodar os testes e ficar batendo lá, devem ter nos colocado na lista negra.

**Comment by itamarnet** [comment]
Pensei na possibilidade de uma nova zz antes, mas é tão automático associar buscas ao google que declinei da idéia e nem a coloquei em pauta. Já que vc também levantou a bola já acho que pode vingar.
Sobre a "blacklist", deve ser isso mesmo. Comigo começou quando estava fazendo testes para acertar justamente a ``` zzgoogle ``` junto com outras funções, as demais ok, mas ela, tive que fazer a gambiarra citada.
E a escolha do duckduckgo foi um paliativo, existem outras opções que pode considerar.

**Comment by aureliojargas** [comment]
Ou nem colocar nada no lugar. Afinal, há 85482572 maneiras de pesquisar no Google, não ter isso nas ZZ não é o fim do mundo :)

De repente simplesmente aposentar a `zzgoogle` e pronto.

Eu nunca usei o Duck, não sei se há demanda pra isso ou se vale o investimento em manter isso funcionando.
