### ISSUE TITLE
Eliminar a necessidade da 'zztool texto_em_iso'

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#395]
O ideal é que a `zzutf8` seja usada diretamente. Ela já converte para UTF-8 caso seja necessário.

A discussão sobre isso aconteceu em um Merge Request já encerrado: https://github.com/funcoeszz/funcoeszz/pull/319#issuecomment-260788320

Agora estou abrindo essa issue para podermos acompanhar o andamento.

**Comment by aureliojargas** [comment]
A `zzcinemais` já não usa mais :tada:

O que ainda sobrou é só isso aqui:

```console
$ git grep texto_em_iso
funcoeszz:              texto_em_iso)
zz/zzcinemais.sh:               zztool texto_em_iso |
zz/zzcinemais.sh:       zztool texto_em_iso |
zz/zzfeed.sh:                           iso) zztool texto_em_iso ;;
$
```

E por sua vez a zzfeed com essa opção especial só tem um única função que usa:

```console
$ git grep zzfeed.*iso
zz/zznoticiaslinux.sh:          zzfeed --iso -n $n "$url"
$ git grep zzfeed.*utf
zz/zzfeed.sh:#      zzfeed --utf http://aurelio.net/feed/  # O coding é utf-8
$
```

Então se resolver o problema da `zznoticiaslinux` não precisa mais ter as opções `--iso` e `--utf` na `zzfeed`, e as coisas voltam a ficar mais simples 😄

**Comment by itamarnet** [comment]
Não entendi!
A ``` zzcinemais ``` ainda usa a ``` texto_em_iso ```.

**Comment by aureliojargas** [comment]
Sim, tem que resolver a `zzcinemais` e a `zznoticiaislinux` pra poder solucionar esta issue. Vamos sem pressa, se der.

**Comment by itamarnet** [comment]
Voltando a questão da ``` zzutf8 -f ```, acho que poderia seguir a linha que adotei na``` zzmat ``` com a opção ``` -p ```.
Seria colocar o encoding desejado justaposto a opção ``` -f ``` e se não houver nada assumimos ``` iso-8859-1 ```

```
	if echo "$1" | grep '^-f' >/dev/null
	then
		encoding="${1#-f}"
		encoding="${encoding:-iso-8859-1}"
		shift
	fi
```

E trocar:
```
	# Qual a sua codificação atual?
	if test -z "$encoding"
	then
		encoding=$(zzencoding "$tmp")
	fi
```

E acho que a ``` zzencoding ``` não deveria ser mexida, pois me parece nitidamente um problema no arquivo de origem mal formatado, seja pelo ambiente onde roda ou talvez com o uso de algum framework que gera as páginas ou algum erro não previsto.

**Comment by aureliojargas** [comment]
Eu preferia que a `zzencoding` fosse confiável e não precisássemos desse tipo de remendo.

Pelos testes que fiz aqui (Mac, Ubuntu 12, Docker) com a `zznoticiaslinux v`, ela funcionou normalmente sem precisar da opção `--iso`.

Vasculhando os commits antigos aqui, eu achei quando isso mudou:

- zznoticiaslinux v: d0b39a7a6de933ae5255252665ef86a0b4a414b9 e d26b680320763de5510aead40732e6847378d880
- zzfeed --iso: ca877bf107c283cbc3af3213efec147cf31449c9

Mas nos commits não diz o porquê da mudança. Você lembra?

**Comment by aureliojargas** [comment]
> Não entendi!
> A zzcinemais ainda usa a texto_em_iso.

Agora que eu vi que eu tinha escrito `zzcinemais` em vez de `zzcinepolis` no comentário original :/

**Comment by aureliojargas** [comment]
Aqui pra mim a `zzcinemais` também funciona normal na primeira requisição:

```console
$ url='http://www.cinemais.com.br/programacao'
$ zztool source -o "ISO-8859-1" "$url" > foo
$ zzencoding foo
iso-8859-1
$
```

Já a segunda, com os nomes dos filmes, dá problema:

```console
$ codigo=9
$ zztool source  -o "ISO-8859-1" -u "Mozilla/5.0" "${url}/cinema.php?cc=${codigo}" > foo
$ zzencoding foo
unknown-8bit
$
```

Porém, se fizer primeiro o `grep` e depois testar o encoding, funciona:

```console
$ cat foo | grep -E '(<td><a href|<td><small|[0-9] a [0-9])' | zzencoding
iso-8859-1
$
```

Então essa dá pra salvar. Abri o PR #403 com as mudanças, vê se no teu lado está ok.

**Comment by itamarnet** [comment]
No commit:
 https://github.com/funcoeszz/funcoeszz/commit/d0b39a7a6de933ae5255252665ef86a0b4a414b9 tem um comentário que explica isso, é a mesma situação que a ``` zzcinemais ``` vive.
Na época eu lembro que o comando ``` file ``` falhava nessa identificação, da mesma forma que ocorre agora na ``` zzcinemais ```.

**Comment by aureliojargas** [comment]
Ah, eu procurei nas mensagens de commit do Git, esqueci de olhar os comentários do GitHub, foi mal.

Será que então isso foi arrumado lá no server? Que aqui nos meus testes funcionou normalmente. Esse erro era intermitente?

**Comment by aureliojargas** [comment]
Outra coisa que vi agora.

```bash
			source)
				curl -L -s "${user_agent:+-A}" "${user_agent}" "$1"
			;;
```

O `zztool source` ignora a opção `-o "ISO-8859-1"` que está recebendo na `zzcinemais`. Imagino que antes era usada outra ferramenta em vez do `curl` ali. De repente isso tem a ver com o negócio funcionar hoje.

**Comment by itamarnet** [comment]
Acho que achou o ponto de mudança.
Para dar flexibilidade ampliamos o leque de browsers, visto que nem sempre o lynx resolvia ou estava disponível, incluindo como opção links, links2, elinks e w3m.
Entre as possibilidades existentes com o lynx, e replicada com as novas opções, estava o ``` source ``` para obter o código fonte.
Como tivemos muitos problemas pelas diferenças inerentes de cada browser convergimos no uso do ``` curl ```.
E essa idéia é algo ainda a ser ampliado, pois temos ainda o issue #275, que aborda justamente essa questão
