### ISSUE TITLE
Lançar versão 18.03

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#404]
A última versão lançada das Funções ZZ foi a 15.5 ([anúncio](http://funcoeszz.net/anuncio-15.5.html)).

Agora que estamos com o testador tinindo, quase no 100%, podíamos fazer um esforço pra lançar uma versão agora em novembro.

@itamarnet que tal?

**Comment by itamarnet** [comment]
Até o número do issue é peculiar :)

Acho uma boa idéia, mas anda meio corrido no local onde trabalho, pois é época de orçamento para o próximo período e haverá dias que não conseguirei ser rápido no retorno.

Então se achar por bem, não aguarde meu ok nos PR para não atrasar. Pode ser um período tranquilo, o que duvido muito, mas minha disponibilidade é uma incónita então não posso dar certeza de estar esses dias focado nas Funcões.

Então "Continue a Nadar"
PS.: vai se acostumando a usar essas expressões lúdicas, serão parte do seu novo cotidiano.

**Comment by aureliojargas** [comment]
É mesmo, nem tinha visto que é a issue 404, massa! :smile: 

Quanto ao tempo livre, sem crise, vamos fazendo quando der. Pode ser novembro, dezembro, janeiro... A hora que estiver pronto, lançamos.

**Comment by itamarnet** [comment]
Novo horizonte se for possível: Versão 18.02

**Comment by aureliojargas** [comment]
Mais de um ano já passou, caramba!

**Comment by aureliojargas** [comment]
Opa, temos poucos dias pra fechar o release ainda em fevereiro, será que rola? Nos próximos dias conseguirei me dedicar às ZZ.

Estou olhando aqui [o build mais recente do Travis](https://travis-ci.org/funcoeszz/funcoeszz/builds/345612527):

- zzbrasileirao: OK - não começou ainda
- zzcep: Somente um de seus testes falhou, estranho...
- zzdistro - demora um século pra rodar cada teste e falhou tudo
- zzmariadb - erro simples de formatação

E só! O resto está tudo OK. Que excelente trabalho você fez @itamarnet, botou a casa em ordem!👏👏 👏 👏 👏

**Comment by itamarnet** [comment]
Confesso que não olhei o Travis nessa empreitada mais recente, então acho que esses poucos erros foram menos do que eu imaginava.
Por conta da ``` zzloteria ``` no Travis havia a instalação do ``` links ``` ou ``` elinks ```, mas devido a mudanças no site da caixa nem essa solução mais resolvia, então na PR #487 mudei a fonte de consulta.
Talvez ajude não precisar maus fazer essa instalação.

**Comment by itamarnet** [comment]
@aureliojargas Entre os pendentes:
 - zzcep: Parece haver uma instabilidade, e nos últimos testes não apresentou mais problemas e eu nada fiz.
 - zzmariadb: Fiz ajustes no PR #501 junto com a zzloteria.
 - zztweets: Não estava listado, mas consegui fazer um testador simples.
 - zzdistro: Não sei o que fazer, o testador nas máquinas rodam perfeitamente, mas no Travis o problema persiste e não consigo identificar o motivo. Lembro que houve algo parecido com a zzlinux, que acabou excluída dos teste por problemas com certificados digitais, mas nesse caso sequer consigo imaginar o motivo.

**Comment by itamarnet** [comment]
Lançada em 31/03/2018.
Aos 45 do segundo tempo !!!
