### ISSUE TITLE
zzfeed: a opção -u ainda é necessária?

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#410]
```
 -u para simular navegador Mozilla/Firefox (alguns sites precisam disso).
``` 

Acredito que esse é mais um resquício de quando usávamos o lynx para baixar os feeds (vide #395). Não encontrei nenhuma função que utiliza `zzfeed -u`:

```console
$ git grep 'zzfeed.*-u'
zz/zzfeed.sh:#      zzfeed -u funcoeszz.net                # UserAgent do lynx diferente
$
```

**Comment by itamarnet** [comment]
Tem razão.
A ``` zzfeed ``` tem como dependentes as funções: ``` zzlinuxnews ```, ``` zznoticiaslinux ```, ``` zznoticiassec ``` e ``` zzsecurity ``` e nenhuma delas faz uso dessa opção.

Mas pensando em termo de função auxiliar isso faz todo o sentido, todavia como uma função final essa opção pode ser útil a quem quiser agregar ao seu script ou em seu uso direto.

Particularmente não vejo mal em manter a opção disponível.

**Comment by aureliojargas** [comment]
Eu particularmente não gosto de ter coisas a mais, porque tem o custo adicional de manter funcionando, testar, documentar...

Mas tem razão. Neste caso a implementação é trivial e pode ser útil no futuro.
