### ISSUE TITLE
Erro configurando ZSH no macos sierra

### ISSUE THREAD

**Issue by tnarnold** [funcoeszz/funcoeszz#419]
No macos sierra não consegui entender porque no zsh as funcoeszz acusa esse erro:
/usr/local/bin/funcoeszz:11099: parse error near `)'

versão 15.5

No bash não tem problema.

**Comment by itamarnet** [comment]
@tnarnold Provavelmente isso não está no core das FuncoesZZ, pelo número da linha informado deve ser umas das funções que está junto ao core. Seria possível ir até a linha informada e verificar em qual função está dando erro?

**Comment by itamarnet** [comment]
Acredito que o problema esteja resolvido pela PR #495.
Todavia o efeito deverá ser efetivo na próxima versão ou no uso das funções diretamente do Github.

**Comment by tnarnold** [comment]
Estou com o high sierra agora e quando executo:
# source ../../funcoeszz/funcoeszz
Trava nessa PR... não sei bem como poderia depurar para saber onde trava.
No bash funciona normalmente.

**Comment by itamarnet** [comment]
Caro @tnarnold 
A versão que tem é a 15.5, e creio que não há como mudar isso no momento.

Se for possível pegar a versão corrente no Github acredito que o efeito da mudança seria sentido de imediato, e caso queira manter tudo em um arquivo só, poderia fazer por exemplo a chamada:
```
	funcoeszz --tudo-em-um > funcoeszz.new
	mv -f funcoeszz.new funcoeszz
```
e deixar apenas a linha ``` export ZZPATH=$ZZPATH ``` no arquivo ``` .zshrc ```.

Se puder fazer esse teste, será mais um ponto de conhecimento a ser registrado.

Infelizmente não tenho esse SO para testar.

Aguardo seu retorno.

**Comment by idgserpro** [comment]
@tnarnold tente chamar `emulate sh source ../../funcoeszz/funcoeszz;` ou algo similar pra ver se resolve. Leia sobre "emulate shell" em http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html.

Veja também outra forma em https://www.zsh.org/mla/users/2009/msg00090.html

**Comment by itamarnet** [comment]
@tnarnold Que tal experimentar a versão 18.3.

**Comment by itamarnet** [comment]
Testes efetuados na nova versão parecem ter mitigado o problema.
