### ISSUE TITLE
zznoticiaslinux: Viva o Linux à vezes vem zipado

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#42]
Em alguns sistemas as notícias vêm gzipadas, tendo que abrir com `gzip -d`. Reportado por Rodrigo Azevedo.

Eu não consigo reproduzir este bug, aqui sempre funcionou normal. Mais alguém com este problema?

```
$ zznoticiaslinux v

* Viva o Linux (http://www.vivaolinux.com.br):
Compilando PHP 5.4.X no Debian/Ubuntu
Falha na identificação em phpPgAdmin [Resolvido]
Customizando o Terminator com Solarized Color Scheme
Open Journal System (OJS) - Instalação prática no GNU/Linux
Problemas com driver Wi-Fi Broadcom b43 em netbook HP [Resolvido] -  Fedora 17
```

**Comment by itamarnet** [comment]
Alguém está com esse problema ainda das notícias gzipadas?
É possível saber mais detalhes das condições quando isso ocorre? horário, sistema, shell, locale, etc.?
Também não consigo reproduzir o problema.

**Comment by itamarnet** [comment]
Esse problema não foi reportado novamente e nem foi possível reproduzir depois de muitos testes.
Apenas posso supor que tenha sido um problema temporal ou localizado.
Não havendo mais detalhes que deem subsídios para repetir o evento, vou considerá-lo inexistente.
