### ISSUE TITLE
zzloteria com erro.

### ISSUE THREAD

**Issue by pauloneves123** [funcoeszz/funcoeszz#426]
<b>Em algumas das miniaplicações das funçõeszz, é necessário alguns programas externos para que funcionem tais aplicações, uma dessas miniaplicações é a "zzloteria". Para que funcione tal função, é necessário instalar um navegador de modo texto</b> "<i>links</i>", "<i>links2</i>"<b> ou </b>"<i>elinks</i>".
<b>Geralmente, pode ser instalado pelo comando:</b> <i>apt-get install "nome_do_tipo_de_navegador_que_deseja_instalar".</i>
<b>Exemplo:</b>

$ apt-get install links

<b>Se acontecer este erro:</b>

E: Não foi possível abrir arquivo de trava /var/lib/dpkg/lock - open (13: Permissão negada)
E: Não foi possível criar acesso exclusivo ao directório de administração (/var/lib/dpkg/), é root?

<b>É necessario a permissão de abrir arquivo de travar /var/lib/dpkg/lock , caso contrário não será possivel instalar o arquivo.
Se isso acontecer, digite:</b> <i>sudo apt-get install "nome_do_tipo_de_navegador_que_deseja_intalar".</i>

<b>Entretanto, o algoritmo não está recebendo algumas informações, o que mostra uma falha na miniaplicação das funcoeszz, dando como erro este texto:</b>

<i>"The page cannot be found The page you are looking for might have been removed, had its name changed, or is temporarily unavailable. ------------------------------------------------------------------- Please try the following: * Make sure that the Web site address displayed in the address bar of your browser is spelled and formatted correctly. * If you reached this page by clicking a link, contact the Web site administrator to alert them that the link is incorrectly formatted. * Click the Back button to try another link. HTTP Error 404 - File or directory not found. Internet Information Services (IIS) ------------------------------------------------------------------- Technical Information (for support personnel) * Go to Microsoft Product Support Services and perform a title search for the words HTTP and 404. * Open IIS Help, which is accessible in IIS Manager (inetmgr), and search for topics titled Web Site Setup, Common Administrative Tasks, and About Custom Error Messages."</i>
<b>
Como na imagem à seguir:</b>
![img1](https://user-images.githubusercontent.com/29262061/27804178-e30eb05c-6003-11e7-9e2b-6d91619781b5.png)

<h5>Testado na versão Ubuntu 14.04 - Oracle VM VirtualBox no dia 03/07/2017 às 14:50.</h5>

**Comment by itamarnet** [comment]
Caro @pauloneves123 eu não consegui reproduzir o erro, mas o site da Caixa Econômica Federal ocasionalmente tem esse problema de ficar instável.
O problema ainda persiste?

**Comment by pauloneves123** [comment]
Na maquina que estou testando ainda continua o erro... Ainda não testei em outra máquina. Vou ver em outra máquina para saber se o erro está na qual estou utilizando no momento.

**Comment by quaresmateo** [comment]
Provavelmente deve ser algum problema que houve durante a instalação das funçõeszz. Se for conveniente pode usar esse tutorial de instalação, que aborda algumas possibilidades que resultam no funcionamento incorreto de certas funções.
Se for de interesse segue um tutorial que considera algumas situações: https://plus.google.com/u/0/115950912259278428663/posts/jPHhcWVb1FG

**Comment by itamarnet** [comment]
@pauloneves123 Algum retorno?
Ainda não identifiquei o erro que citou.

**Comment by aureliojargas** [comment]
Por aqui está funcionando:

```console
$ zzloteria quina
quina:
Concurso 4575 (08/01/2018)
   10   31   33   49   52

   Estimativa de prêmio do próximo concurso 09/01/2018   R$ 9.500.000,00
   Acumulado próximo concurso R$ 8.258.872,63
   Acumulado para Sorteio Especial de São João R$ 58.771.913,84
  
   Quina números acertados   Não houve acertador
   Quadra números acertados   142  R$ 4.941,05
   Terno números acertados   10989  R$ 96,01
   Duque números acertados   238459  R$ 2,43

$
```
