### ISSUE TITLE
zzbrasileirao com uso do argumento -l não funciona

### ISSUE THREAD

**Issue by kellydosocorro** [funcoeszz/funcoeszz#427]
**Quando se usa a linha de comando:**

zzbrasileirao -l [nome clube] 

**A seguinte mensagem é exibida:**

Uso: zzbrasileirao [a|b|c] [numero rodada] ou zzbrasileirao -l [nome clube] 

**Testado na distribuição Ubuntu versão 14.04**

**Comment by itamarnet** [comment]
Obrigado @kellydosocorro, mas a opção ``` -l ``` está indisponível agora devido as mudanças do site fonte, o que ocorreu foi um esquecimento em atualizar o help adequadamente.
Na verdade o certo seria:
```
Uso: zzbrasileirao [a|b|c|d] [numero rodada]
```
Providenciarei a correção.

**Comment by kellydosocorro** [comment]
Obrigada pelo retorno @itamarnet, imaginei que seria algo do tipo.

**Comment by itamarnet** [comment]
Finalmente solucionado no PR #420
