### ISSUE TITLE
zztop não esta retornando nada 

### ISSUE THREAD

**Issue by erlonfonseca** [funcoeszz/funcoeszz#429]
A funçãozz zztop não esta retornando nada para meu terminal.

**Comment by itamarnet** [comment]
@erlonfonseca poderia me dar mais detalhes, não consegui reproduzir o erro.
Ao invocar a função ``` zztop ``` eu tenho uma resposta positiva.
Qualquer informação como seu ambiente, SO, shell usado poderia me dar um panorama melhor para avaliar.

**Comment by erlonfonseca** [comment]
quando digito no meu terminal zztop diz comando não encontrado

**Comment by erlonfonseca** [comment]
![captura de tela 2](https://user-images.githubusercontent.com/29806472/27875642-5a5da492-618a-11e7-8b69-78d0fcf04386.png)

**Comment by itamarnet** [comment]
@erlonfonseca Lamento a demora na resposta, mas está usando a versão 15.5?
Se for, tenta usar a versão que está no github, é uma versão que tem as atualizações mais recentes, mais ou menos.
Imprevistos comigo e com @aureliojargas nos deixaram afastados por um tempo, mas estamos retomando.
Aguardo seu retorno se possível.
