### ISSUE TITLE
zzve moedas e zzve tr dão erro

### ISSUE THREAD

**Issue by CaioSR** [funcoeszz/funcoeszz#431]
" sed: a sintaxe de classes de caracteres é [[:space:]], e não [:space:] "

![zzve2](https://user-images.githubusercontent.com/26325211/27888629-71f76a60-61bd-11e7-8711-22752931b1ac.png)

**Comment by itamarnet** [comment]
Caro @CaioSR nesse ponto está enganado, o que tem na primeira citação é uma classe de caracteres posix dentro de uma lista, e a segunda é a classe de caractere propriamente dita.
Veja em: http://aurelio.net/regex/guia/lista.html

Mas o erro reportado não tenho com verificar agora, mas olharei em detalhes.
Obrigado

**Comment by CaioSR** [comment]
O que eu comentei entre aspas é o que o programa retorna ao tentar utilizar as funções.

**Comment by itamarnet** [comment]
Desculpe-me @CaioSR interpretei errado.
Poderia dar mais detalhes do sistema onde acontece o erro? Como o SO, Shell, versão do ``` sed ```, ou qualquer outra informação.
Infelizmente esse erro nos ambientes onde testo não se manifestou.
Obrigado pelo retorno.

**Comment by CaioSR** [comment]
Ubuntu 17.4
Sed 4.4

Quais e como eu poderia adquirir outras informações? Não me familiarizei com essa ambiente ainda.

**Comment by itamarnet** [comment]
O Ubuntu costuma ter um local com uma interface gráfica que dá essas informações adicionais.
Infelizmente agora não estou usando a distro e de memória não lembro, mas um site bom para consultas sobre o assunto e recomendo para quem é iniciante é: http://www.diolinux.com.br.

Mas a priori poderia usar esses comandos para ter alguma informação na linha de comando
```
 locale
 lsb_release -a
 set
 zzzz --teste
```

**Comment by CaioSR** [comment]
![info](https://user-images.githubusercontent.com/26325211/27958802-1f4a7c6e-62fb-11e7-87ee-659b74a853f8.png)
![info2](https://user-images.githubusercontent.com/26325211/27958809-239e2c48-62fb-11e7-945e-71833e196693.png)

**Comment by martinbra** [comment]
zzve consulta o site da Valor Econômico http://www.valor.com.br/valor-data/ que está atualmente atrás de um "login-wall". 
Mesmo assim, o retorno aqui foi vazio (Linux Lite 3.4 (Ubuntu 16.04), sed 4.2.2):
```
martin@martin-K52Jc:~/Development/zzfunctions/zz$ zzve tr
martin@martin-K52Jc:~/Development/zzfunctions/zz$ zzve moedas
martin@martin-K52Jc:~/Development/zzfunctions/zz$ 
```
@itamarnet, Será que no sed 4.4 ele está reclamando por estar recebendo algum campo vazio?

**Comment by itamarnet** [comment]
@CaioSR @martinbra Não há o que se fazer no momento, as informações estão restritas a assinantes agora.
