### ISSUE TITLE
zztweets não retorna nada.

### ISSUE THREAD

**Issue by CaioSR** [funcoeszz/funcoeszz#432]
Bug local? Não sei, mas não retorna nada aqui.

Ubuntu 17.4

![zztweets](https://user-images.githubusercontent.com/26325211/27888605-58d24cd0-61bd-11e7-8cc9-c420f321a41b.png)

**Comment by italojohnny** [comment]
Mesmo problema aqui.

**Comment by itamarnet** [comment]
Corrigido no PR #450
