### ISSUE TITLE
zzfutebol não retorna o placar do campeonato espanhol

### ISSUE THREAD

**Issue by LucasFerraroCardoso** [funcoeszz/funcoeszz#435]
A função zzfutebol, de acordo com a definição, deveria ser capaz de retornar os resultados do espanhol. Não sei se o fato de não funcionar é devido a pausa da La Liga, mas não retorna nada. Também não encontrei referências ao campeonato espanhol no código.

**Comment by itamarnet** [comment]
Caro @LucasFerraroCardoso a função usa o que está na agenda do site UOL sobre jogos, não tendo nenhuma amarração com um campeonato em especial. A citação do campeonato espanhol no help é apenas um exemplo ilustrativo.
Como há uma pausa no campeonato, não consta nada na agenda elaborada pelo UOL, então realmente não haverá qualquer retorno.
Hoje por exemplo, usar libertadores ou sul-americana haverá retorno pois há jogos constando na agenda.
De toda forma obrigado pela citação.
