### ISSUE TITLE
Site desatualizado e zzpiada

### ISSUE THREAD

**Issue by LucasFerraroCardoso** [funcoeszz/funcoeszz#436]
A versão do funcoeszz para download no site está desatualizada. Quando se instala através do site algumas funções não funcionam corretamente e algumas funções que já fora desativadas ainda estão ativas. Um caso é o zzpiada, função que foi desativada por o site está fora do ar, acontece que o site está no ar e a função está funcionando normalmente.

**Comment by itamarnet** [comment]
@LucasFerraroCardoso Obrigado pela observação.
Na verdade ocasionalmente eu e o @aureliojargas lançamos versões da funcoeszz como uma todo, e o site pode ficar com uma versão desatualizada dependendo do momento em que é consultado, por isso incentivamos o uso da versão disponibilizada no github, que costumamos manter mais atualizada possível.
No momento por motivos pessoais, tanto eu como o @aureliojargas deixamos um pouco de lado a funcoeszz: o @aureliojargas é ``` papai fresco ``` e deve estar meio perdido/ocupado/enrolado ainda e eu por compromissos profissionais, além de uma filha que acabou de entrar na faculdade.

**Comment by itamarnet** [comment]
Sobre a ``` zzpiada ``` infelizmente há/houve uma intermitência no site, ficando grandes períodos fora do ar, por isso foi decidido encerrar a função devido a constantes problemas nesse sentido.
Mas havendo a possibilidade de retornar a função a ativa com uma estabilidade do site constante eu ficaria muito feliz, mas prefiro aguardar um pouco para confirmar essa tendência.
Até para esse tipo de caso há um ticket em aberto sobre tratar de sites que ficam indisponíveis: #287.

**Comment by LucasFerraroCardoso** [comment]
Entendo, imaginei que fosse isso. Obrigado pela resposta.
