### ISSUE TITLE
zzcinepolis não funciona com o código do cinema como parametro

### ISSUE THREAD

**Issue by AndreMP93** [funcoeszz/funcoeszz#437]
Quando se usa a linha de comando zzcinepolis [codigo_cinema] a função não retorna nada.

**Comment by itamarnet** [comment]
@AndreMP93 mas qual código foi usado no seu teste, ou nenhum código numérico funcionou?
Usando o nome da cidade funcionou?
No momento não posso testar, mas assim que puder verificarei.

**Comment by AndreMP93** [comment]
facomp@facomp-VirtualBox:~$ zzcinepolis belem
Cinépolis Boulevard Belem
facomp@facomp-VirtualBox:~$ zzcinepolis 2
facomp@facomp-VirtualBox:~$

**Comment by quaresmateo** [comment]
Provavelmente deve ser algum problema que houve durante a instalação das funçõeszz. Se for conveniente pode usar esse tutorial de instalação, que aborda algumas possibilidades que resultam no funcionamento incorreto de certas funções.
Se for de interesse segue um tutorial que considera algumas situações: https://plus.google.com/u/0/115950912259278428663/posts/jPHhcWVb1FG

**Comment by gustavopinto** [comment]
Oi @quaresmateo, não seria uma boa enviar esse tutorial como contribuição para o repositório das funcoeszz? Algo como um arquivo guida_de_instalacao.md?

**Comment by quaresmateo** [comment]
@gustavopinto Seguindo sua sugestão criei um install guide https://github.com/funcoeszz/funcoeszz/pull/438.

**Comment by itamarnet** [comment]
Função ``` zzcinepolis ``` foi desativada, pois não retornava mais resultados em qualquer forma de consulta. O site foi alterado para usar as técnicas AJAX, o que torna captura inviável.
Conforme PR #454
