### ISSUE TITLE
zzrastreamento - correio alterou sistema

### ISSUE THREAD

**Issue by martinbra** [funcoeszz/funcoeszz#440]
A página de rastreamento antiga dos correios foi aposentada.
A consulta é feita agora por POST à página http://www2.correios.com.br/sistemas/rastreamento/resultado.cfm
Mas existe uma página dos correios similar à anterior, e mais limpa para fazer o parser:
http://www2.correios.com.br/sistemas/rastreamento/resultado_semcontent.cfm

Usando lynx o resultado vem "bonitinho":
`echo "objetos=PO424862142BR" | lynx -post_data http://www2.correios.com.br/sistemas/rastreamento/resultado_semcontent.cfm`

Não consegui usar a zzbrowser para testar os outros navegadores, nem para testar o lynx. 
Mas, como foi citado na issue #275, devemos dar prioridade ao curl:

`curl -X POST -F objetos=PO424862142BR http://www2.correios.com.br/sistemas/rastreamento/resultado_semcontent.cfm`

mas o código resultante, mesmo passando pela zzxml ainda precisa ser limpo, sobram restos de CSS e JS.

**Comment by itamarnet** [comment]
Solucionado nos PR's #421 e #462
