### ISSUE TITLE
zzipinternet in not working here

### ISSUE THREAD

**Issue by lanuxx** [funcoeszz/funcoeszz#441]
$ zzipinternet 

Looking up www.getip.com
Making HTTP connection to www.getip.com
Alert!: Unable to connect to remote host.

lynx: Can't access startfile http://www.getip.com/

**Comment by itamarnet** [comment]
@lanuxx Lamento a demora em responder, problemas externos nos mantiveram afastados das atividades daqui.

Qual a versão está uitilzando?
Atualmente usamos o site ``` http://ipaddress.com/ ``` para retonar essa informação.

Recomendo usar a versão que etá no github.

Assim que for possível estaremos atualizando a versão no site.

**Comment by aureliojargas** [comment]
Just tested with the current GitHub version and it worked:

```console
$ zzipinternet 
208.113.153.233
$
```
