### ISSUE TITLE
Erro ao iniciar zzconvert-meta

### ISSUE THREAD

**Issue by robertopc** [funcoeszz/funcoeszz#464]
Toda vez que abra o terminal, dá o seguinte erro: `Função inexistente 'zzconvert-meta' (tente --help)`.

**Comment by itamarnet** [comment]
Caro @robertopc essa é uma mensagem de erro bem estranha, mas parece ser na tentativa de subir a função para memória ou algo que chama a função, ou talvez até um alias. Confesso não lembrar de nada parecido com essa linha de comando.
Poderia exibir aqui a saída do comando set?

**Comment by robertopc** [comment]
A saída tá no arquivo [set.txt](https://github.com/funcoeszz/funcoeszz/files/1664820/set.txt)

**Comment by itamarnet** [comment]
@robertopc Realmente não há nada ligado nas FunçoesZZ com o erro que reportou olhando o arquivo que passou. Estava imaginando que pudesse  ter alguma alteração acidental, mas não foi o que encontrei.

Não seria um alias editado incorretamente, uma entrada acidental no seu bashrc, ou até um dos arquivos da pasta ``` /etc/profile.d/ ``` que está provocando o erro?

**Comment by robertopc** [comment]
Achei onde está o problema, estou usando um dotfile `.inputrc` que obtive do repositório [webpro/dotfiles](https://github.com/webpro/dotfiles/blob/master/runcom/.inputrc).
E nesse arquivo têm opções que estão sendo setadas, e são essas as opções que o zz está conflitando. Eu comentei a linha 29 e em seguida ele mostrou o seguinte erro:
`Função inexistente 'zzoutput-meta' (tente --help)`

Comentei esta opção e voltou a acontecer com todas as outras:
```bash
roberto@telessaude funcoeszz [master] $ bash
Hello World! roberto
Função inexistente 'zzskip-completed-text' (tente --help)
roberto@telessaude funcoeszz [master] $ bash
Hello World! roberto
Função inexistente 'zzvisible-stats' (tente --help)
roberto@telessaude funcoeszz [master] $ bash
Hello World! roberto
Função inexistente 'zzvisible-stats' (tente --help)
roberto@telessaude funcoeszz [master] $ bash
Hello World! roberto
Função inexistente 'zzcompletion-query-items' (tente --help)
roberto@telessaude funcoeszz [master] $ bash
Hello World! roberto
Função inexistente 'zzoutput-meta' (tente --help)
```
Só desativando o include do `.inputrc` parou de dar os erros: https://github.com/robertopc/dotfiles/blob/master/.bashrc

**Comment by itamarnet** [comment]
Bom então não é algo que posso ajudar diretamente, mas posso sugerir como alternativa carregar as dotfiles por último, talvez elimine o problema no seu caso.

Como é algo bem específico em um caso que particularmente não há o que ser feito, vou fechar esse issue.
