### ISSUE TITLE
Cadastrar TODAS as funções no testador

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#47]
O testador informa rapidamente quando uma função está quebrada.

O testador te avisa caso suas mudanças tenham afetado o resultado da função.

O testador garante que sua função funciona 100%.

O testador é seu amigo!

O ideal é que todas as funções, sem exceção, tenham testes cadastrados no testador, para ser fácil identificar quando uma função quebrar ou mudar de comportamento. O ideal é que nenhum commit deveria passar se a função não passar no teste.

Mas não vivemos num mundo ideal, então infelizmente hoje apenas 60% das funções estão no testador.

```
#140 funções no total
#  85 no testador

prompt$ zzporcento 140 85
60,71%
```

Lista das funções já cadastradas no testador:

```
zzalfabeto       zzdiasuteis       zzlimpalixo      zzsecurity
zzansi2html      zzdicasl          zzlinha          zzsenha
zzarrumanome     zzdicbabylon      zzlinuxnews      zzseq
zzascii          zzdicjargon       zzlocale         zzsextapaixao
zzbeep           zzdicportugues    zzloteria        zzsigla
zzbissexto       zzdiffpalavra     zzmaiusculas     zzstr2hexa
zzbyte           zzdolar           zzmat            zztabuada
zzcalcula        zzdominiopais     zzmd5            zztac
zzcalculaip      zzecho            zzminusculas     zztempo
zzcarnaval       zzfeed            zzmoeda          zztool
zzchavepgp       zzfoneletra       zzmoneylog       zztrocaarquivos
zzcinclude       zzfreshmeat       zznatal          zztrocaextensao
zzcnpj           zzgoogle          zznomefoto       zztrocapalavra
zzcontapalavra   zzgravatar        zznoticiaslinux  zzunicode2ascii
zzcontapalavras  zzhexa2str        zznoticiassec    zzuniq
zzconverte       zzhora            zzpascoa         zzvira
zzcores          zzhoracerta       zzporcento       zzwhoisbr
zzcorpuschristi  zzhoramin         zzramones        zzwikipedia
zzcpf            zzhorariodeverao  zzromanos        zzxml
zzdata           zzhowto           zzrot13
zzdatafmt        zzipinternet      zzrot47
zzdiadasemana    zzjuntalinhas     zzrpmfind
```

Mesmo as já cadastradas ainda podem melhorar, adicionando mais testes para cobrir todas as situações e funcionalidades suportadas.

Mas o foco principal agora é que cada função tenha seu teste automatizado. Se você é autor de função e a sua ainda não está no testador, que tal colocá-la? Mesmo que você não seja autor, toda ajuda é bem-vinda para adicionar testes novos.

O ponto de partida é esta página wiki: https://github.com/aureliojargas/funcoeszz/wiki/Testes-Automaticos

Ao cadastrar uma função nova no testador, mencione este issue no commit, para que possamos acompanhar a evolução. Exemplo:

```
testador: adicionados testes zzfoobar [issue #47]
```

Lista das 54 funções ainda NÃO CADASTRADAS no testador em 2013-02-26:

``` 2013-02-26
zzanatel        zzdebgen           zzjquery       zzrandbackground
zzarrumacidade  zzdefine           zzkill         zzrastreamento
zzbicho         zzdefinr           zzlembrete     zzrelansi
zzblist         zzdelicious        zzlinux        zzsemacento
zzbolsas        zzdicesperanto     zzmaiores      zzshuffle
zzbrasileirao   zzdos2unix         zzminiurl      zzss
zzcapitalize    zzenglish          zzmudaprefixo  zzsubway
zzcbn           zzenviaemail       zznarrativa    zztradutor
zzchecamd5      zzestado           zznome         zztv
zzcidade        zzeuro             zzora          zztweets
zzcinemais      zzextensao         zzpalpite      zzunescape
zzcinemark15h   zzferiado          zzpiada        zzunix2dos
zzcineuci       zzfrenteverso2pdf  zzpronuncia
zzcorrida       zzglobo            zzquebramd5
```

**Comment by itamarnet** [comment]
Atualizando a lista das 9 funções NÃO CADASTRADAS no testador em 2016-09-11:
```
zzfrenteverso2pdf
zziostat
zzkill
zzplay
zzpronuncia
zzrandbackground
zzrelansi
zzss
zztweets
```
Essas funções restantes não imagino ainda como testar. Sugestões são bem vndas !

**Comment by itamarnet** [comment]
Em 30/03/2018 há 5 funções **não cadastradas**, a saber:
```
zzfrenteverso2pdf
zziostat
zzplay
zzpronuncia
zzss
```
Sugestões?

**Comment by itamarnet** [comment]
Em 01/05/2018 há 4 funções sem testador:
```
zzfrenteverso2pdf
zziostat
zzplay
zzss
```
Não vejo como essas possam ter um testador satisfatório pela natureza audio-visual das duas últimas, e a dependência de ferramentas externas a exemplo das duas primeiras.
Visto que não houve feedback adicionais, vou considerar esse issue resolvido.
