### ISSUE TITLE
Sugestão: zzf1 (Fórmula 1)

### ISSUE THREAD

**Issue by aureliojargas** [funcoeszz/funcoeszz#514]
> @plastico
> https://twitter.com/plastico/status/963826145400639490
>
> achei uma api aberta que exibe estatísticas da Fórmula 1, o que acha de uma "zzf1"? XD ~> https://ergast.com/api/f1/current/last/results.json

**Comment by pvital** [comment]
@aureliojargas se ninguem estiver trabalhando nisso pode me nomear que faço ele.

**Comment by itamarnet** [comment]
@pvital Fique a vontade, "forka" e depois "pulla"

**Comment by aureliojargas** [comment]
Dá-lhe @pvital!

**Comment by farribeiro** [comment]
Eu recomendaria que implantar alguma rotina utilitária para webhooks

**Comment by itamarnet** [comment]
Sugestão aceita e conchuída no PR #615
