### ISSUE TITLE
Goo.gl depreciado

### ISSUE THREAD

**Issue by farribeiro** [funcoeszz/funcoeszz#516]
Olá

Conforme matéria jornalistica[1] foi anunciado o shutdown[2] do serviço, o que faria o script miniurl[3] quebrar. Por gentileza debater a depreciação do script.

Conforme discutido na na Issue https://github.com/funcoeszz/funcoeszz/issues/287, solicita utilizar outra API, provavelmente o http://migre.me . Confirma?

[1] https://olhardigital.com.br/noticia/google-anuncia-fim-do-encurtador-de-links-goo-gl/74906
[2] https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html
[3] https://github.com/funcoeszz/funcoeszz/blob/master/zz/zzminiurl.sh

**Comment by itamarnet** [comment]
@farribeiro Obrigado pelo alerta, realmente não estava sabendo.

Na verdade a referência mais adequada seria a PR #442, que trata desse assunto ao informar que o serviço do http://migre.me parou de funcionar a época e parece que ainda continua, e a alternativa oferecida a época foi usar o serviço do google.

Uma opção é voltar a usar o https://is.gd/ que era uma alternativa para momentos de instabilidade do migre.me, e por isso era citada na issue #287, ou talvez usar outro como o https://bitly.com/

Qualquer sugestão é bem vinda.

**Comment by farribeiro** [comment]
Tranquilo... mas parece que a nova plataforma do Google é interessante, deem uma olhada

**Comment by vleite** [comment]
Olá pessoal, eu fiz o commit da versão nova alterando o serviço para o Bitly, conforme o Google recomenda.

**Comment by farribeiro** [comment]
Dois PRs para mesma finalidade?

@itamarnet ok?

**Comment by farribeiro** [comment]
Não há possibilidade de fechar rebase/cherry em um único PR?

**Comment by itamarnet** [comment]
@farribeiro O ideal seria mesmo, mas tudo bem.
Ambas estão referenciadas então é um problema menor e contornável.
Assim que possível testarei e espero "mergear" em breve.

**Comment by farribeiro** [comment]
Solicitei No último commit ser assim: `Closes #516`

**Comment by itamarnet** [comment]
Solucionado no PR citado.
