### ISSUE TITLE
zzdolar e zzcotacao com problemas

### ISSUE THREAD

**Issue by ellisonleao** [funcoeszz/funcoeszz#521]
- Sistema:  macOS Sierra

- Problema:

ambas as funções não estão mostrando o valor da cotação do dólar.

- Exemplo:

## zzcotacao 

```
❯ zzcotacao
Infomoney
                    Compra   Venda   Var(%)
Euro eu              4,247   4,249   +0,88

UOL - Economia
~
```

## zzdolar

```
❯ zzdolar
~
``` 

 Como o último commit para as alterações do dólar foram há 2 anos, acredito que o site do uol possa ter sofrido algumas alterações.

**Comment by itamarnet** [comment]
Caro @ellisonleao eu não consegui reproduzir o erro citado.
Infelizmente não possuo o macOS para testes mais próximos da sua realidade.
Seria possível você dar mais detalhes do ambiente, como o shell, a versão do sed e awk, qual o navegador de texto presente: lynx, links, elinks, links2, w3m ou qualquer outra informação que possa ser relevante

No momento não consigo diagnosticar e nem sugerir uma solução.

**Comment by ellisonleao** [comment]
```
❯ sed --version
sed (GNU sed) 4.4
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jay Fenlason, Tom Lord, Ken Pizzini,
and Paolo Bonzini.
GNU sed home page: <http://www.gnu.org/software/sed/>.
General help using GNU software: <http://www.gnu.org/gethelp/>.
E-mail bug reports to: <bug-sed@gnu.org>.
~
❯ awk --version
awk version 20070501

❯ w3m -version
w3m version w3m/0.5.3+git20180125, options lang=en,m17n,color,ansi-color,mouse,menu,cookie,ssl,ssl-verify,external-uri-loader,w3mmailer,nntp,ipv6,alarm,mark
```

**Comment by itamarnet** [comment]
Caro @ellisonleao acredito que o problema estivesse no comportamento do ``` w3m ``` para esses sites, então baseando na ideia já referenciada no issue #275 resolvi mudar a forma de consulta trocando ``` zztool dump ``` por ``` zztool source ```, conforme pode ser visto nos PRs #522 e #523.
Pode verificar se atende agora?

**Comment by ellisonleao** [comment]
agora está perfeito! Caso facilite, no futuro acho que daria pra usar [essa tabela](http://cotacoes.economia.uol.com.br/cambio/cotacoes-diarias.html?cod=BRL) para as cotações

**Comment by itamarnet** [comment]
Opa, gostei da sugestão do link, valeu @ellisonleao
