### ISSUE TITLE
zzcnpj dá erro quando o primeiro digito é zero

### ISSUE THREAD

**Issue by luzemario** [funcoeszz/funcoeszz#580]
Pessoal, favor implementar a mesma correção existente no zzcpf para o zzcnpj, que é desconsiderar o primeiro dígito zero antes de tratar o número, uma vez que números que começam com zero no shell são interpretados como números octais.

Exemplo:

`zzcnpj 02.674.113/0001-06 // CNPJ inválido (deveria terminar em 67)`
`zzcnpj 02674113000106 // CNPJ inválido (deveria terminar em 67)`
`zzcnpj 2674113000106 // CNPJ válido`

Notem que o algorítimo funcionou quando o zero à esquerda foi removido.

**Comment by itamarnet** [comment]
@luzemario Desculpa a demora em responder novamente, mas sua questão é bem mais séria do que vc afirma. Não é apenas questão de desconsiderar o zero no início, pois isso já é feito, mas um erro crasso intrínseco na ` zzcnpj ` e na ` zzcpf ` que passou desapercebido.
Há esses trechos nos códigos

zzcnpj: ` cnpj=$(echo "$cnpj" | sed 's/^0*//') `
zzcpf:  ` cpf=$(echo "$cpf" | sed 's/^0*//') `

Que na teoria impediriam esse problema, mas há esses outros trechos

zzcnpj: ` cnpj=$(printf "%014d" "$cnpj") `
zzcpf:  ` cpf=$(printf %011d "$cpf") `

Que volta com o problema e não estávamos percebendo

A questão não é apenas a ` zzcnpj `, mas corrigir também a ` zzcpf `.

Obrigado pelo aviso.

**Comment by itamarnet** [comment]
Resolvida no PR #581
