### ISSUE TITLE
zzgoogle ou similar

### ISSUE THREAD

**Issue by martinbra** [funcoeszz/funcoeszz#589]
Baseado [nesta necessidade](https://stackoverflow.com/questions/35186560/url-encode-in-windows-batch-script/35186784), de criar um batch (windows no caso) para fazer uma pesquisa no google (ou outro site de pesquisa qualquer). O que vocês acham de criarmos uma zz que retorne uma URL "encodada" a partir de um termo de busca?

Exemplo:
```
>zzbusca Funções ZZ
https://www.google.com/search?q=fun%C3%A7%C3%B5es+zz

>zzbusca --duckduckgo Funções ZZ
https://duckduckgo.com/?q=Fun%C3%A7%C3%B5es+zz
```

**Comment by mountaineerbr** [comment]
Você já viu

zz/zzcodchar.sh

Ele codifica as entidades em html.

Mas com o seguinte comando, não vi diferença nenhuma codificando ou não 
o cedilha e o til+o..

vimdiff <(w3m -dump 'https://www.google.com/search?q=funções+zz') <(w3m 
-dump 'https://www.google.com/search?q=fun%C3%A7%C3%B5es+zz')

**Comment by martinbra** [comment]
Pois é, depois eu vi que não fazia diferença.
Fazer a própria função zz chamar um navegador (GUI ou bash) sai do escopo das funções zz, correto? Mesmo se for um parâmetro ao estilo de
```
zzbusca firefox Funções ZZ
zzbusca --duckduckgo lynx Funções ZZ
zzbusca curl Funções ZZ
```

Se sai do escopo, podemos deixar apenas gerando links de busca para uma série de buscadores, e o usuário faz o que quiser com ele... 

ou fechamos a issue assim mesmo...

**Comment by mountaineerbr** [comment]
ia ser legal pegar a página de busca e fazer uma limpeza, pq vem muita bobagem junto..
até tenho uma função de shell para puxar o CEP do site dos correios massa, mas se eles mudarem algo lá, já era.
mas acho difícil manter uma função assim pq o google muda muito o código deles frequentemente. 
uma dica, não sei se se adequa a sua necessidade, veja o ddgr 
https://www.omgubuntu.co.uk/2017/11/duck-duck-go-terminal-app
parece que ele lê a variável de ambiente $BROWSER também..

**Comment by martinbra** [comment]
Hum os dois fazem o que preciso. Obrigado @mountaineerbr !
Acho que podemos deixar a issue aberta ainda, caso eu, você ou outro aventureiro queira implementar a ideia.

**Comment by itamarnet** [comment]
Olá @marcelma e @mountaineerbr 
Já existiu a zzgoogle ( https://github.com/funcoeszz/funcoeszz/blob/master/off/zzgoogle.sh ), mas foi desativada. Podem conferir o problema e a discussão no issue #390
