### ISSUE TITLE
zztradutor: Não retorna nenhuma tradução.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#590]
A ` zztradutor ` usa o translate do google, que não mais responde por adotar técnicas AJAX.
Sites alternativos como www.collinsdictionary.com, www.linguee.com.br, www.deepl.com/translator, www.babylon.com, www.bing.com/translator, tradukka.com, www.online-translator.com, etc. usam a mesma técnica ou se valem da engine do Google ou da Microsoft. E as APIs oferecidas ou são pagas ou necessitam de cadastro com a necessidade de uma chave, e mesmo assim as traduções deixam a desejar.
Sugiro nesse contexto a desativação dessa função e remoção dos códigos das outras funções que remetiam a ` zztradutor `  e recomendo o uso do ` Translate Shell ` ( https://www.soimort.org/translate-shell , https://github.com/soimort/translate-shell ) em substituição para quem necessite desse recurso.

**Comment by aureliojargas** [comment]
Eita, vamos desativar então. Essa web moderna está muito arredia com os pobres robôs...

**Comment by itamarnet** [comment]
Desativada, conforme PR #591
