### ISSUE TITLE
zzdolar não retorna nada

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#598]
A função zzdolar no momento não mostra nenhum resultado, pois consulta a seção de economia do site da UOL, que usa agora algum tipo de framework ou algum webservice, que embuti a estrutura HTML dentro de um script, que parece passível de mudança constante.
Reescrever o código a cada mudança ( que é constante ) parece uma tarefa ingrata, tenho duas sugestões:
 - Destivar a função visto que a ` zzcotacao ` cobre essa demanda, fornecendo dados adicionais.
 - Reescrever a ` zzdolar `, que ficaria dependente da ` zzcotacao ` trazendo apenas as informações sobre o Dólar.
 
Aguardo considerações.

**Comment by aureliojargas** [comment]
Gostei da segunda alternativa. Menos manutenção, e mantém a `zzdolar` ativa.

Acredito ser importante mantê-la ativa por ser uma função muito antiga (usuários devem estar bem acostumados a usá-la) e pelo dólar em geral ser mais importante que outras cotações, para o brasileiro em geral.

**Comment by itamarnet** [comment]
Resolvido no PR #600
