### ISSUE TITLE
Nanny: verificação de 'zztool uso'.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#639]
No momento que crio esse issue existem 183 funções ( sem contabilizar as do core ), das quais 99 são consideradas válidas por não usarem 'zztool uso', visto que invocar as mesmas sem parâmetros é válido.
Essa quantidade equivale a 54% de todas as funções, que pelo valor não caracteriza exceção, então ainda é necessária essa verificação?
É uma proposta a ser analisada sem qualquer urgência, mas que parece não fazer mais sentido devido a expressiva quantidade de funções que não precisam dessa característica.

**Comment by aureliojargas** [comment]
É, acho que a ideia ao criar essa verificação era que funções sem argumentos seriam a minoria. Mas sendo metade, realmente não faz muito sentido, é só trabalho manual chato. Vamos remover.

**Comment by itamarnet** [comment]
Resolvido no PR #643
