### ISSUE TITLE
zzchavepgp: Intermitência no site.

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#652]
A função ` zzchavepgp ` tem um comportamento errático devido a instabilidade do site, que eventualmente funciona, e em muitos momentos não responde, ou retorna erros relacionado ao "proxy" e ocasionalmente outros erros diversos.
Não sei bem o que fazer com relação a esse comportamente na função e ao site, pois é intermitente.

Sugestões são bem vindas.

**Comment by aureliojargas** [comment]
Temos mais exemplos de funções nessa situação? Talvez podemos ter uma categoria especial de testes que estão permitidos falharem, enquanto não achamos solução definitiva para o problema.

**Comment by itamarnet** [comment]
Nas que estão em teste não, mas houve uma solução de funções que não rodavam no Travis de jeito nenhum que contornamos fazendo delas exceções na hora de usar o CI, que foi adotada no PR #571, onde a zzdistro e zzlinux são excluídas do testes,
```
internet_travis=$(echo $internet | sed 's/ zz\(distro\|linux\)\.sh//g')
```
Talvez usar esse artifício com a ` zzchacepgp `.
O que acha?

**Comment by aureliojargas** [comment]
Ah, eu não tinha entendido que o problema é só no Travis. Rodando local funciona então? Beleza, vamod adicionar na `internet_travis` então.

**Comment by itamarnet** [comment]
Essa intermitência é independente do Travis, mas eventualmente funciona, apenas apresentei essa solução anterior como exemplo, que não funcionavam no Travis apenas, mas no caso da ` zzchavepgp ` esse mal funcionamento é maior.
Eu não vejo como solucionar esse caso, devido ao site, mas com relação ao CI essa poderia ser uma saída, um paliativo.

**Comment by aureliojargas** [comment]
Tudo bem, se o teste não.é confiável, acho que não faz sentido dependermos dele. Por mim pode colocar como exceção na `internet_travis`

**Comment by itamarnet** [comment]
Solução adotada na PR #660
