### ISSUE TITLE
GPLv2 license is deprecated 

### ISSUE THREAD

**Issue by chenrui333** [funcoeszz/funcoeszz#671]
👋  [GPLv2](https://spdx.org/licenses/GPL-2.0.html) is a deprecated license, can you add header into README or source code file to be clear about the license (either [GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only.html) or [GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html))

relates to https://github.com/Homebrew/homebrew-core/pull/69080

**Comment by aureliojargas** [comment]
Hi @chenrui333, thanks for bringing this issue to our attention. Our software is indeed GPL-2.0-only. 

It is now clarified in the README and in the source code:  https://github.com/funcoeszz/funcoeszz/pull/672

We also added that information to the website: https://github.com/funcoeszz/funcoeszz.github.io/pull/9

**Comment by chenrui333** [comment]
Thanks!!
