### ISSUE TITLE
zzcpf não valida CPF iniciado com 0

### ISSUE THREAD

**Issue by martinbra** [funcoeszz/funcoeszz#676]
Se o CPF a ser validado iniciar com zero e 0 zero estiver presente na string de entrada, a função compreende o numero como octal.

Exemplo:
```
$ zzcpf 012.345.678-90
C:\cygwin64\bin\bash: printf: 01234567890: número octal inválido
CPF inválido (deveria terminar em 19)

$ zzcpf 12.345.678-90
CPF válido
```

Aparentemente, a função também não gera cpfs que iniciam com 0.

Abri a issue para deixar registrado. Irei tentar resolver e criar um PR.

**Comment by itamarnet** [comment]
Ola @martinbra.

Vc está usando uma versão atualizada?
Pois esse procedimento já foi feito no PR #581 pelo colaborador @marcosbarbosadev 

Esses comandos que deu de exemplo retornam válidos em ambos os casos na versão que tenho.

**Comment by martinbra** [comment]
> Ola @martinbra.
> 
> Vc está usando uma versão atualizada?
> Pois esse procedimento já foi feito no PR #581 pelo colaborador @marcosbarbosadev 
> 
> Esses comandos que deu de exemplo retornam válidos em ambos os casos na versão que tenho.

Era isso. Desculpe nao verificar a versao antes de abrir a issue. Cheguei a pesquisar por outras issues, mas apenas as abertas.
