### ISSUE TITLE
zzipinternet com ipv6

### ISSUE THREAD

**Issue by martinbra** [funcoeszz/funcoeszz#720]
Estou pensando em incluir o ipv6 na resposta do `zzipinternet`.
Ou incluir um parâmetro `zzipinternet -6` seguindo o padrão -6 do ssh.
Ou criar o comando `zzipv6internet`.

O que vocês acham ser o melhor caminho?

algumas apis que achei pra recuperar o ipv6:
https://api64.ipify.org -- achei a mais interessante, por ser mais "aberta".
http://v6.ipv6-test.com/api/myip.php
https://v6.ident.me

**Comment by aureliojargas** [comment]
Oi @martinbra , boa ideia e muito obrigado pela sua contribuição!

Já que a `zzipinternet` só tem uma linha mesmo, acredito que adicionar a opção `-6` seja uma boa.

**Comment by martinbra** [comment]
Obrigado pela dica @aureliojargas . Segue o PR com a mudança e teste. 
A única questão que não implementei e nem testei, pensando em KISS, é que se o usuário passar um parâmetro errado, a função não retorna erro, mas o IPv4. 
De qualquer forma, era esse o comportamento anterior...

Se achar que devo alterar, só me avisar.

**Comment by aureliojargas** [comment]
Implementado na PR mencionada aqui. Valeu @martinbra!
