### ISSUE TITLE
Erro ao executar função zzcep

### ISSUE THREAD

**Issue by papodesysadmin** [funcoeszz/funcoeszz#735]
zzcep 09810-090
bash: /tmp/zz.alinhar.0ZOGcX: impossível sobrescrever arquivo existente
bash: /tmp/zz.xml.tag.eviJON: impossível sobrescrever arquivo existente
awk: /tmp/zz.xml.tag.eviJON:3: } {
awk: /tmp/zz.xml.tag.eviJON:3: ^ syntax error

**Comment by aureliojargas** [comment]
Oi @papodesysadmin, obrigado pelo aviso.

Eu não consigo reproduzir o erro aqui. Estou usando o Termux no Android, com a versão master do repositório das Funções ZZ:

```console
$ ./funcoeszz zzcep 09810-090
LOGRADOURO                                                        BAIRRO                    CIDADE/ESTADO
Rua Tota Nogueira (Vl Euro)                                       Assunção                  São Bernardo do Campo, SP
$
```

Qual seu sistema operacional?
Qual a saída do comando `funcoeszz --version`?

**Comment by aureliojargas** [comment]
Também testei agora com a última versão lançada das ZZ (21.1) e também funcionou.

**Comment by papodesysadmin** [comment]
Boa Tarde Verde é Linuxmen que lhe procura.
Um prazer poder falar contigo.
Vou descrever todos os passos que fiz para tu ver aonde errei.

Minha distribuição
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

Fiz o download no site e coloquei no meu home - /home/linuxmen
-rwxr-xr-x  1 linuxmen linuxmen   628049 jul  8 16:06  funcoeszz

Executei o comando - ./funcoeszz zzzz --bashrc

vim no .bashrc
# Instalacao das Funcoes ZZ (www.funcoeszz.net)
export ZZOFF=""  # desligue funcoes indesejadas
export ZZPATH="/home/linuxmen/funcoeszz"  # script
export ZZDIR=""    # pasta zz/
source "$ZZPATH"

Percebendo o arquivo acima vi que na instalação ele não criou as pastas ZZOFF e ZZDIR, acho que é isso.
Estou testando e volto com um posicionamento.
Tudo bem?

**Comment by aureliojargas** [comment]
Fala Linuxmen, bom falar contigo de novo!

Que erro mais estranho. É consistente essa situação? Toda vez que executa com `bash funcoeszz zzcep 09725-050` funciona e toda vez que executa direto `zzcep` dá o mesmo erro?

**Comment by papodesysadmin** [comment]
Sim acontece sempre, inclusive fiz em vm.
Me chama no telegram vamos papear @linuxmen

Em sáb., 17 de jul. de 2021 18:07, 'Aurelio Jargas' via Contato <
***@***.***> escreveu:

**Comment by aureliojargas** [comment]
Eu e o @papodesysadmin fizemos uma sessão de debug juntos e conseguimos encontrar a origem do problema.

O problema só acontecia quando o [Oh My Bash](https://github.com/ohmybash/oh-my-bash) estava ativado. Se o desligasse, tudo funcionava. Investigando, descobrimos [que ele liga a opção `noclobber`](https://github.com/ohmybash/oh-my-bash/blob/4db7436384e0ddfa62911a101b69dd03a0df53fe/lib/shopt.sh#L9), que impede que redirecionamentos que sobrescrevem arquivos sejam usados.

Exemplo de código que não funciona quando o `noclobber` está ativado:

https://github.com/funcoeszz/funcoeszz/blob/f0865902138f2609938dda5ca7c940b172ae3688/funcoeszz#L193-L195

Então no fim, não era um problema das ZZ, mas uma restrição na configuração do ambiente do usuário. De qualquer forma, a mensagem de erro ao tentar usar a `zzcep` (ou demais funções que façam esse tipo de redirecionamento) não é clara e pode ser melhorada.

É fácil detectarmos so o `noclobber` está ativado, e mostrar uma mensagem instruindo o usuário a desativá-lo. Fazer isso por função será incômodo, talvez fazer essa verificação no [`zzzz --teste`](http://funcoeszz.net/faq.html#requisitos) seja um meio termo aceitável:

```console
$ zzzz --teste
Procurando o comando awk...   OK
Procurando o comando bc...    OK
Procurando o comando cat...   OK
Procurando o comando chmod... OK
Procurando o comando clear... OK
Procurando o comando cp...    OK
Procurando o comando cpp...   OK
Procurando o comando cut...   OK
Procurando o comando diff...  OK
Procurando o comando du...    OK
Procurando o comando find...  OK
Procurando o comando grep...  OK
Procurando o comando lynx...  OK
Procurando o comando mv...    OK
Procurando o comando od...    OK
Procurando o comando play...  OK
Procurando o comando rm...    OK
Procurando o comando sed...   OK
Procurando o comando sleep... OK
Procurando o comando sort...  OK
Procurando o comando tr...    OK
Procurando o comando uniq...  OK
Verificando a codificação do sistema... UTF-8
Verificando a codificação das Funções ZZ... UTF-8
$

**Comment by aureliojargas** [comment]
O problema relatado por esta issue foi resolvido no lado do usuário, com uma configuração em seu ambiente:

```bash
set +o noclobber
```

Então essa issue pode ser fechada.

Mas eu abri a issue #749 para mostrar uma mensagem mais amigável ao usuário quando o `noclobber` estiver ativado.

Muito obrigado @papodesysadmin pelo retorno e por ter disponibilizado uma sessão remota para podermos debugar este problema! ❤️
