### ISSUE TITLE
Alterar zzfreshmeat para zzfreecode

### ISSUE THREAD

**Issue by itamarnet** [funcoeszz/funcoeszz#81]
Já não seria hora de mudar o nome da zzfreshmeat para zzfreecode.
Para quem é mais antigo, lembra que o site tinha esse nome, mas acho que a nova denominação faz mais sentido, e acredito que a função poderia acompanhar o novo nome.

O que acha? Vale a pena a mudança? ( Referência: https://github.com/aureliojargas/funcoeszz/blob/master/zz/zzfreshmeat.sh )

**Comment by aureliojargas** [comment]
Para referência quanto à desativação da zzfreshmeat, veja #143
