### ISSUE TITLE
nany zzsecurity

### ISSUE THREAD

**Issue by alexandre-mbm** [funcoeszz/funcoeszz#97]
Crio esta *issue* para dizer-lhes que estou trabalhando em um *branch* "trabalhos-de-nany". Comecei pelo mais fácil: sanando a nany para a ``zzsecurity``.

Nesse momento, estou terminando de sanar a nany para ``zzpais`` — #98. Não me apressarei em fazer a *pull request*. Quero sanar a nany para mais coisa, antes. Para cada sanação de função eu faço um commit no branch "trabalhos-da-nany".

Quero sugerir que esta e outras *issues* subsequentes sejam etiquetas "nany". Além disso, vou tentar manter o padrão de nomes "nany FUNÇÃO".

**Comment by aureliojargas** [comment]
Este é um issue antigo, de 2013. Atualmente todas as funções estão passando pela nanny.
